### ISSUE TITLE
AttributeError: 'list' object has no attribute 'file_id'

### ISSUE THREAD

**Issue by MrTret** [eternnoir/pyTelegramBotAPI#1013]
I want to resend photo back to user . This is code :

@bot.message_handler(content_types=['photo'])
def replyphoto(message):
	bot.send_photo(message.chat.id, message.photo.file_id)

This is what i got  :

2020-11-10 04:56:45,260 (util.py:75 WorkerThread2) ERROR - TeleBot: "AttributeError occurred, args=("'list' object has no attribute 'file_id'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "tbot.py", line 26, in replyphoto
    bot.send_photo(message.chat.id, message.photo.file_id)
AttributeError: 'list' object has no attribute 'file_id'
"
Traceback (most recent call last):
  File "tbot.py", line 33, in <module>
    bot.polling()
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 427, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 451, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 118, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "tbot.py", line 26, in replyphoto
    bot.send_photo(message.chat.id, message.photo.file_id)
AttributeError: 'list' object has no attribute 'file_id'

I alse tried this :

@bot.message_handler(content_types=['photo'])
def replyphoto(message):
	bot.sendPhoto(message.chat.id, message.photo.file_id)

but got this :

2020-11-10 05:01:34,136 (util.py:75 WorkerThread1) ERROR - TeleBot: "AttributeError occurred, args=("'TeleBot' object has no attribute 'sendPhoto'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "tbot.py", line 26, in replyphoto
    bot.sendPhoto(message.chat.id, message.photo.file_id)
AttributeError: 'TeleBot' object has no attribute 'sendPhoto'
"
Traceback (most recent call last):
  File "tbot.py", line 33, in <module>
    bot.polling()
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 427, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 451, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 118, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "tbot.py", line 26, in replyphoto
    bot.sendPhoto(message.chat.id, message.photo.file_id)
AttributeError: 'TeleBot' object has no attribute 'sendPhoto'

**Comment by BLUE-DEVIL1134** [comment]
U Need To get the photo data to local server (the host place) then convert to a File

Then Use This Function
```python
import os

file = open('./$FILENAME.EXTENSION')
bot.send_photo(message.chat.id, file)
del file
os.remove("./$FILENAME.EXTENSION")
```

**Comment by Badiboy** [comment]
message.photo is an ARRAY.
https://core.telegram.org/bots/api#message
