### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by wmchina** [eternnoir/pyTelegramBotAPI#1029]
Please answer these questions before submitting your issue. Thanks!

What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 3.6.7
What OS are you using?
Ubuntu 18 (64 бит)
What version of python are you using?
python3.8

How to solve this problem?

2020-12-02 04:30:29,480 (util.py:68 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telebot/__init__.py", line 281, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/telebot/__init__.py", line 251, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 199, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 65, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 84, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']
"
2020-12-02 04:30:29,485 (__init__.py:443 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']"
2020-12-02 04:30:32,985 (util.py:68 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telebot/__init__.py", line 281, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/telebot/__init__.py", line 251, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 199, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 65, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 84, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']
"
2020-12-02 04:30:32,987 (__init__.py:443 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']"

**Comment by BLUE-DEVIL1134** [comment]
Its A Basic Error When You Run The Same Bot With Two Different Scripts At The Same Time...

Try revoking the token and use one script..

**Comment by BLUE-DEVIL1134** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> What version of pyTelegramBotAPI are you using?
> pyTelegramBotAPI 3.6.7
> What OS are you using?
> Ubuntu 18 (64 бит)
> What version of python are you using?
> python3.8
> 
> How to solve this problem?
> 
> 2020-12-02 04:30:29,480 (util.py:68 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']',)
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/site-packages/telebot/util.py", line 62, in run
> task(*args, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/telebot/**init**.py", line 281, in __retrieve_updates
> updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
> File "/usr/local/lib/python3.8/site-packages/telebot/**init**.py", line 251, in get_updates
> json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
> File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 199, in get_updates
> return _make_request(token, method_url, params=payload)
> File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 65, in _make_request
> return _check_result(method_name, result)['result']
> File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 84, in _check_result
> raise ApiException(msg, method_name, result)
> telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
> [b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']
> "
> 2020-12-02 04:30:29,485 (**init**.py:443 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
> [b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']"
> 2020-12-02 04:30:32,985 (util.py:68 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']',)
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/site-packages/telebot/util.py", line 62, in run
> task(*args, **kwargs)
> File "/usr/local/lib/python3.8/site-packages/telebot/**init**.py", line 281, in __retrieve_updates
> updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
> File "/usr/local/lib/python3.8/site-packages/telebot/**init**.py", line 251, in get_updates
> json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
> File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 199, in get_updates
> return _make_request(token, method_url, params=payload)
> File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 65, in _make_request
> return _check_result(method_name, result)['result']
> File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 84, in _check_result
> raise ApiException(msg, method_name, result)
> telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
> [b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']
> "
> 2020-12-02 04:30:32,987 (**init**.py:443 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
> [b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"}']"

worked?

**Comment by BLUE-DEVIL1134** [comment]
@Badiboy seems that it worked and he wont reply also
can this be closed?
