### ISSUE TITLE
Running at boot

### ISSUE THREAD

**Issue by leaner50** [eternnoir/pyTelegramBotAPI#1037]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.4
2. What OS are you using?
Rasbian
3. What version of python are you using?
3.7.3

When i wan't to run a python script on boot it gives this errer. The last file doesn't  exist! How do i solve it?

Thank in advence!

Running at boot
Traceback (most recent call last):
  File "/home/pi/Downloads/...........py", line 2, in <module>
    import telebot
  File "build/bdist.linux-armv7l/egg/telebot/__init__.py", line 21, in <module>
  File "build/bdist.linux-armv7l/egg/telebot/apihelper.py", line 18, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyTelegramBotAPI-3.7.4-py2.7.egg/telebot/types.py", line 855
    def add(self, *args, row_width=None):
                                 ^
SyntaxError: invalid syntax

**Comment by Badiboy** [comment]
python 2 is not supported...

**Comment by BLUE-DEVIL1134** [comment]
> python 2 is not supported...

Not Even Python2
Its A Complete Syntax Error

Yesterday I Was Using On Python2.7 And It Worked..

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/101760064-6b7cd200-3aeb-11eb-84df-18523a3f850b.png)

I can give no more comments about Python 2.

**Comment by BLUE-DEVIL1134** [comment]
can this be closed now?
