### ISSUE TITLE
invalid syntax for types.py line 861

### ISSUE THREAD

**Issue by gades** [eternnoir/pyTelegramBotAPI#1071]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI==3.7.3 - 3.7.5

2. What OS are you using?
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

3. What version of python are you using?
 2.7.17 

`# python
Python 2.7.17 (default, Sep 30 2020, 13:38:04) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import telebot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/telebot/__init__.py", line 21, in <module>
  File "build/bdist.linux-x86_64/egg/telebot/apihelper.py", line 18, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyTelegramBotAPI-3.7.5-py2.7.egg/telebot/types.py", line 861
    def add(self, *args, row_width=None):
                                 ^
SyntaxError: invalid syntax
`

**Comment by Badiboy** [comment]
Python2 is not supported due to it's EOL.
