### ISSUE TITLE
Not Working on This Last Week. (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries ex...)

### ISSUE THREAD

**Issue by afrijayaps** [eternnoir/pyTelegramBotAPI#1141]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.7.7

2. What OS are you using? Centos 7

3. What version of python are you using? 3.7.8

Hello, my bot not working after last update.
This my simple Source (Not Working) :

```
import telebot

#import ssl
#ssl._create_default_https_context = ssl._create_unverified_context

TOKEN = '****'
bot = telebot.TeleBot(TOKEN, parse_mode="HTML")

# Handle /ip'
@bot.message_handler(commands=['me'])
def send_welcome(message):
    user=bot.getMe()
    bot.reply_to(message, user)

@bot.message_handler(func=lambda message: True)
def echo_message(message):
    rep="Upload foto anda untuk membuat Avatar Badge!"
    bot.reply_to(message,rep)
	
bot.polling()
```

return error :
```

 Apr 21 17:22:39 sv.centos7 rc.local[24824]: return _make_request(token, method_url, params=payload)
Apr 21 17:22:39 sv.centos7 rc.local[24824]: File "/www/server/panel/pyenv/lib/python3.7/site-packages/telebot/apihelper.py", line 128, in _make_request
Apr 21 17:22:39 sv.centos7 rc.local[24824]: timeout=(connect_timeout, read_timeout), proxies=proxy)
Apr 21 17:22:39 sv.centos7 rc.local[24824]: File "/www/server/panel/pyenv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
Apr 21 17:22:39 sv.centos7 rc.local[24824]: resp = self.send(prep, **send_kwargs)
Apr 21 17:22:39 sv.centos7 rc.local[24824]: File "/www/server/panel/pyenv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
Apr 21 17:22:39 sv.centos7 rc.local[24824]: r = adapter.send(request, **kwargs)
Apr 21 17:22:39 sv.centos7 rc.local[24824]: File "/www/server/panel/pyenv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
Apr 21 17:22:39 sv.centos7 rc.local[24824]: raise ConnectionError(e, request=request)
Apr 21 17:22:39 sv.centos7 rc.local[24824]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries ex...
Hint: Some lines were ellipsized, use -l to show in full.
```
Anyone can help me?

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/115539378-94854e80-a2a5-11eb-9d1e-e78d0013692f.png)

**Comment by afrijayaps** [comment]
@Badiboy 
what thas mean?
Limit from Telegram Server?

**Comment by BLUE-DEVIL1134** [comment]
Its a connection error problem from server side
Check your internet connection and retry...

<kbd>ConnectionError</kbd> means your server has some network error

**Comment by GabrielRF** [comment]
I'm having the same issue for a while. I have **multiple bots on one ScaleWay VPS** and I get **this error on only one** of them.

I've tried to make it send less messages and also ignore when a person sends more then two messages in one second. I'm not sure if it made any difference at all..
I'm still trying to figure this out.

Output: https://pastebin.com/Q7TpJuRG

**Comment by afrijayaps** [comment]
> I'm having the same issue for a while. I have **multiple bots on one ScaleWay VPS** and I get **this error on only one** of them.
> 
> I've tried to make it send less messages and also ignore when a person sends more then two messages in one second. I'm not sure if it made any difference at all..
> I'm still trying to figure this out.
> 
> Output: https://pastebin.com/Q7TpJuRG

sometimes it works, and sometime connectionError. 
maybe need proxy?

**Comment by IhsanPratama** [comment]
me too

xception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 456, in wrap_socket
    cnx.do_handshake()
  File "C:\Users\ASUS\anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1646, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "C:\Users\ASUS\anaconda3\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 459, in wrap_socket
    raise timeout('select timed out')
socket.timeout: select timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\ASUS\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\ASUS\anaconda3\lib\site-packages\urllib3\util\retry.py", line 368, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Users\ASUS\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)   

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ASUS\anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\ASUS\anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\telebot\__init__.py", line 496, in polling
    self.__threaded_polling(none_stop, interval, timeout, long_polling_timeout)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\telebot\__init__.py", line 555, in __threaded_polling
    raise e
  File "C:\Users\ASUS\anaconda3\lib\site-packages\telebot\__init__.py", line 517, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\ASUS\anaconda3\lib\site-packages\telebot\util.py", line 87, in raise_exceptions
    raise self.exception_info
  File "C:\Users\ASUS\anaconda3\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\telebot\__init__.py", line 322, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout, long_polling_timeout = long_polling_timeout)   
  File "C:\Users\ASUS\anaconda3\lib\site-packages\telebot\__init__.py", line 292, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\telebot\apihelper.py", line 281, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\telebot\apihelper.py", line 128, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ASUS\anaconda3\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)       



**so what's the solution?**

**Comment by IhsanPratama** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> 1. What version of pyTelegramBotAPI are you using? 3.7.7
> 2. What OS are you using? Centos 7
> 3. What version of python are you using? 3.7.8
> 
> Hello, my bot not working after last update.
> This my simple Source (Not Working) :
> 
> ```
> import telebot
> 
> #import ssl
> #ssl._create_default_https_context = ssl._create_unverified_context
> 
> TOKEN = '****'
> bot = telebot.TeleBot(TOKEN, parse_mode="HTML")
> 
> # Handle /ip'
> @bot.message_handler(commands=['me'])
> def send_welcome(message):
>     user=bot.getMe()
>     bot.reply_to(message, user)
> 
> @bot.message_handler(func=lambda message: True)
> def echo_message(message):
>     rep="Upload foto anda untuk membuat Avatar Badge!"
>     bot.reply_to(message,rep)
> 	
> bot.polling()
> ```
> 
> return error :
> 
> ```
> 
>  Apr 21 17:22:39 sv.centos7 rc.local[24824]: return _make_request(token, method_url, params=payload)
> Apr 21 17:22:39 sv.centos7 rc.local[24824]: File "/www/server/panel/pyenv/lib/python3.7/site-packages/telebot/apihelper.py", line 128, in _make_request
> Apr 21 17:22:39 sv.centos7 rc.local[24824]: timeout=(connect_timeout, read_timeout), proxies=proxy)
> Apr 21 17:22:39 sv.centos7 rc.local[24824]: File "/www/server/panel/pyenv/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
> Apr 21 17:22:39 sv.centos7 rc.local[24824]: resp = self.send(prep, **send_kwargs)
> Apr 21 17:22:39 sv.centos7 rc.local[24824]: File "/www/server/panel/pyenv/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
> Apr 21 17:22:39 sv.centos7 rc.local[24824]: r = adapter.send(request, **kwargs)
> Apr 21 17:22:39 sv.centos7 rc.local[24824]: File "/www/server/panel/pyenv/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
> Apr 21 17:22:39 sv.centos7 rc.local[24824]: raise ConnectionError(e, request=request)
> Apr 21 17:22:39 sv.centos7 rc.local[24824]: requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries ex...
> Hint: Some lines were ellipsized, use -l to show in full.
> ```
> 
> Anyone can help me?

same with me

**Comment by IhsanPratama** [comment]
help

**Comment by IhsanPratama** [comment]
### **PLEASE FIX IT :(**

**Comment by BLUE-DEVIL1134** [comment]
Its clearly the network use, try vpn or proxies

**Comment by GabrielRF** [comment]
@IhsanPratama Please, stop flooding. 
We are looking for help and trying to help each other. So, please, be polite and don't flood.

@afrijayaps I'll try using a proxy. Didn't think of that.

**Comment by IhsanPratama** [comment]
i use proxy and solved

**Comment by IhsanPratama** [comment]
> @IhsanPratama Please, stop flooding.
> We are looking for help and trying to help each other. So, please, be polite and don't flood.
> 
> @afrijayaps I'll try using a proxy. Didn't think of that.

OK sir sorry

**Comment by GabrielRF** [comment]
@afrijayaps Fixed it? How did you do it?

**Comment by BLUE-DEVIL1134** [comment]
> @afrijayaps Fixed it? How did you do it?

proxy
