### ISSUE TITLE
FR: Add raise when TOKEN is NoneType

### ISSUE THREAD

**Issue by ZurMaD** [eternnoir/pyTelegramBotAPI#1177]
Hello there,
I was working with ENV variables, so when I failed to load one variable with token the string returned was a None Type value, but TelegramBot fails after that, would be great if there will be validation of TOKENS by length or characters.

```bash
Traceback (most recent call last):
  File "/home/gdp/Desktop/git/telegram-private-bot/main.py", line 75, in <module>
    bot.polling(none_stop=False)
  File "/home/gdp/.local/lib/python3.9/site-packages/telebot/__init__.py", line 514, in polling
    self.__threaded_polling(none_stop, interval, timeout, long_polling_timeout)
  File "/home/gdp/.local/lib/python3.9/site-packages/telebot/__init__.py", line 573, in __threaded_polling
    raise e
  File "/home/gdp/.local/lib/python3.9/site-packages/telebot/__init__.py", line 535, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/gdp/.local/lib/python3.9/site-packages/telebot/util.py", line 87, in raise_exceptions
    raise self.exception_info
  File "/home/gdp/.local/lib/python3.9/site-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "/home/gdp/.local/lib/python3.9/site-packages/telebot/__init__.py", line 324, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout, long_polling_timeout = long_polling_timeout)
  File "/home/gdp/.local/lib/python3.9/site-packages/telebot/__init__.py", line 294, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "/home/gdp/.local/lib/python3.9/site-packages/telebot/apihelper.py", line 281, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/gdp/.local/lib/python3.9/site-packages/telebot/apihelper.py", line 76, in _make_request
    logger.debug("Request: method={0} url={1} params={2} files={3}".format(method, request_url, params, files).replace(token, token.split(':')[0] + ":{TOKEN}"))
AttributeError: 'NoneType' object has no attribute 'split'

```

Excepted Ouput:

```python
if len(TOKEN)<20:
    raise Exception(f'Invalid TOKEN: {TOKEN}')
```
```bash
Invalid TOKEN: ''
```

**Comment by Badiboy** [comment]
May be. :)

But if you use some unpredictable external value - I think it will be more safe to check it before passing it to the TeleBot. You can easily do this check in your program.

Also I should note that len >= 20 is not the sufficient check, so it will not cover all the cases thus not satisfy all users :)
