### ISSUE TITLE
bot.polling() does not respond after a network issue

### ISSUE THREAD

**Issue by MenshikovDmitry** [eternnoir/pyTelegramBotAPI#1211]
Please answer these questions before submitting your issue. Thanks!
Hey guys, Thanks for your effort. I really appreciate your contribution. I face the further issue:
When I start the polling thread, everything works like charm before the server experiences a network issue. After say switching between wi-fi networks the bot stops responding to the messages. The thread though keeps running while doing nothing.
So far I can not solve this problem. 

The code is absolutely basic:
```python
import telebot
bot = telebot.TeleBot(cfg.TELEGRAM_TOKEN, parse_mode='Markdown')

@bot.message_handler(commands=['ok'])
def start_message(message):
    bot.send_message(message.chat.id, 'running')

bot.polling()
```
1. What version of pyTelegramBotAPI are you using?
3.8.1
2. What OS are you using?
Ubuntu Linux 18.04/20.04
3. What version of python are you using?
3.6

**Comment by MenshikovDmitry** [comment]
Unfortunately, it does not solve the issue.
The polling keeps running but does not respond after reconnecting to another wi-fi network. Only killing helps.

**Comment by AndydeCleyre** [comment]
I can confirm this problem.

Years ago, I found that getting this lib to keep polling through problems was resulting in a still-running-but-not-functioning state, so I just have it fail under s6 process supervision which starts a replacement process immediately.

Seeing this report, I did some testing and see that if I disable wifi or disconnect and reconnect to the *same* network, the process gracefully waits until reconnection and then tries to resume.

BUT if I *switch* networks, as @MenshikovDmitry mentioned, it does *not* resume functionality, and just hangs, until/unless I reconnect to the *original* network.

Either gracefully resuming (as is done when reconnecting to the original network) or process-ending failure would be preferable to the current state.

**Comment by AndydeCleyre** [comment]
@MenshikovDmitry I suggest a rename for this issue to focus on switching to a different network, unless  you can reproduce the issue using only one network.

**Comment by Badiboy** [comment]
@AndydeCleyre thank you for the scenario. The problem was not solved because it cannot be reproduced. Now, if we have scenario (I'll test it later) - it opens the way to fix it.

**Comment by Badiboy** [comment]
@AndydeCleyre Could you please try/check this branch: https://github.com/eternnoir/pyTelegramBotAPI/pull/1223 ? I suppose issues should gone. 

PS: always use infinity_polling or your own infinity loop with exception handler...

**Comment by AndydeCleyre** [comment]
I tried it, and with `infinity_polling`. When switching networks, the process survived, but did not respond to events. Eventually, the following exception occurred:

```python
2021-07-09 23:28:15,356 (__init__.py:586 MainThread) ERROR - TeleBot: "Infinity polling exception: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)"
2021-07-09 23:28:15,356 (__init__.py:588 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/telebot/__init__.py", line 582, in infinity_polling
    self.polling(none_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/telebot/__init__.py", line 620, in polling
    self.__threaded_polling(none_stop, interval, timeout, long_polling_timeout, allowed_updates)
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/telebot/__init__.py", line 679, in __threaded_polling
    raise e
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/telebot/__init__.py", line 642, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/telebot/util.py", line 130, in raise_exceptions
    raise self.exception_info
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/telebot/util.py", line 82, in run
    task(*args, **kwargs)
  File "/home/andy/Code/codepic/app/./colorcodebot.py", line 164, in wrapper
    resp = original(*args, **kwargs)
  File "/home/andy/Code/codepic/app/./colorcodebot.py", line 278, in welcome
    self.bot.reply_to(
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/telebot/__init__.py", line 2152, in reply_to
    return self.send_message(message.chat.id, text, reply_to_message_id=message.message_id, **kwargs)
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/telebot/__init__.py", line 925, in send_message
    apihelper.send_message(
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/telebot/apihelper.py", line 257, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/telebot/apihelper.py", line 139, in _make_request
    result = _get_req_session().request(
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/andy/.local/share/venvs/0dda4f1e0a6c3d4825183a79e394ca41/venv/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
"
```

At this point the bot became responsive to any *new* events, but never "caught up" on the ones missed in the meantime.

**Comment by Badiboy** [comment]
@AndydeCleyre seems that it works for me in simple echo bot...

![image](https://user-images.githubusercontent.com/5613421/125155382-1c257f80-e168-11eb-8755-8bacb29f4136.png)

Could you enable debug logging:
1.
`telebot.logger.setLevel(logging.DEBUG) # Outputs debug messages to console.`
2.
`bot.infinity_polling(logger_level=logging.DEBUG, timeout=10, long_polling_timeout = 5)`

And check log after reconnect: how many updates bot receive after connection restored?

>   File "C:\Python3\lib\site-packages\requests\adapters.py", line 529, in send
>     raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=15)
> "
> 2021-07-10 10:15:44,957 (__init__.py:691 MainThread) INFO - TeleBot: "Started polling."
> 2021-07-10 10:15:44,957 (apihelper.py:83 MainThread) DEBUG - TeleBot: "Request: method=get url=https://api.telegram.org/..."
> 2021-07-10 10:15:45,092 (apihelper.py:141 MainThread) DEBUG - TeleBot: "The server returned: 'b'{"ok":true,"result":[{"update_id":748808187,\n"message"..."
> 2021-07-10 10:15:45,093 (__init__.py:398 MainThread) DEBUG - TeleBot: "Received 4 new updates"
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Does the NUMBER of received updates corresponds to number of messages you passed while the bot was offline?

**Comment by YauheniHerasimenka** [comment]
I am getting same issue. But I send a message to the bot fast and it is crashed. But I haven`t an exception when bot.pooling() is brake. I have a code 

> while True:
    try:
        bot.polling(none_stop=True)
    except Exception as e:
        tb = traceback.format_exc()
        logging.error("Error bot pooling", exc_info=True)  
        print(tb) 
        time.sleep(10)

**Comment by Badiboy** [comment]
Try with this parameters:
`bot.infinity_polling(timeout=10, long_polling_timeout = 5)`
