### ISSUE TITLE
bot.polling() throw read timed out exception

### ISSUE THREAD

**Issue by danillucky1234** [eternnoir/pyTelegramBotAPI#1217]
1. I use 3.7.9 version of pyTelegramBotAPI
2. OS: GNU/Linux, Distro: Manjaro
3. Python version 3.9.5

What is the problem?
I wrote a simple bot, which read the content of the directory, create from this files a list of buttons (using pyTelegramBotAPI telebot.types.InlineKeyboardMarkup() ) and send it to the chat in Telegram. Everything works fine, but after few hours I get this errors:
```
File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1345, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/util/retry.py", line 532, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 447, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/user/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 336, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=9999)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/path/to/the/directory/main.py", line 236, in <module>
    bot.polling()
  File "/home/user/.local/lib/python3.9/site-packages/telebot/__init__.py", line 514, in polling
    self.__threaded_polling(none_stop, interval, timeout, long_polling_timeout)
  File "/home/user/.local/lib/python3.9/site-packages/telebot/__init__.py", line 573, in __threaded_polling
    raise e
  File "/home/user/.local/lib/python3.9/site-packages/telebot/__init__.py", line 535, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/user/.local/lib/python3.9/site-packages/telebot/util.py", line 87, in raise_exceptions
    raise self.exception_info
  File "/home/user/.local/lib/python3.9/site-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "/home/user/.local/lib/python3.9/site-packages/telebot/__init__.py", line 324, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout, long_polling_timeout = long_polling_timeout)
  File "/home/user/.local/lib/python3.9/site-packages/telebot/__init__.py", line 294, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "/home/mosquito/.local/lib/python3.9/site-packages/telebot/apihelper.py", line 281, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/user/.local/lib/python3.9/site-packages/telebot/apihelper.py", line 126, in _make_request
    result = _get_req_session().request(
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.9/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=9999)
```

As far as I understand, the problem is in the bot.polling() function on 236 line in main.py (code below)
Code:
https://github.com/danillucky1234/memes-bot/blob/main/main.py

Honestly, I don't know what's causing the error, so even if it's not bot.polling(), I'd be happy to hear at least a tip on a possible cause.
Thanks in advance!

**Comment by Badiboy** [comment]
`requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=9999)
`

What is unclear here?

**Comment by AndydeCleyre** [comment]
@danillucky1234

Network timeouts are going to happen sometimes, and I recommend putting this process under some kind of resilient supervisior/monitor to auto-restart upon failure.

Some options:
- s6
- supervisord
- runit
- systemd
- docker/podman

supervisord is probably be smoothest to get started with if you don't already have experience with any of the others.

**Comment by Badiboy** [comment]
@AndydeCleyre Network timeouts raise exceptions and can be handled. 9999 read timeout looks enormous, it should be set to some appropriate value.

Also they are handled by infinity_polling, I don't think there is any need to use external supervisiors...

**Comment by danillucky1234** [comment]
@AndydeCleyre
Thank you very much for your reply. I really haven't worked with supervisors before, but now I know in which direction to look. 

I guess I can now close this issue

**Comment by AndydeCleyre** [comment]
@danillucky1234 

I *like* working with supervisors but as @Badiboy says you may not need to.

Lower the `timeout` you're passing (or don't pass it at all to use the default 20s), and try calling `bot.infinity_polling` instead of `bot.polling` to smooth over exceptions.

---

@Badiboy Good to know, thanks! I'd still probably want a supervisor on any long-running process but I haven't tried `infinity_polling` since at least 3 years ago so I'll keep it in mind.
