### ISSUE TITLE
CallbackQuery with no data for games.

### ISSUE THREAD

**Issue by studentenherz** [eternnoir/pyTelegramBotAPI#1228]
OS: Ubuntu 20.04.2 LTS
Python version : 3.8.10 
pyTelegramBotAPI version : 3.8.1 

Trying to handle callback query form a game with my bot:

```python
@bot.callback_query_handler(func=lambda call: True)
def callback_handler(call):
	print(call.game_short_name)
```

get this error:

```
Traceback (most recent call last):
  File "main.py", line 17, in <module>
    bot.polling()
  File "path-to-python-env/lib/python3.8/site-packages/telebot/__init__.py", line 619, in polling
    self.__threaded_polling(none_stop, interval, timeout, long_polling_timeout, allowed_updates)
  File "path-to-python-env/lib/python3.8/site-packages/telebot/__init__.py", line 678, in __threaded_polling
    raise e
  File "path-to-python-env/lib/python3.8/site-packages/telebot/__init__.py", line 640, in __threaded_polling
    polling_thread.raise_exceptions()
  File "path-to-python-env/lib/python3.8/site-packages/telebot/util.py", line 100, in raise_exceptions
    raise self.exception_info
  File "path-to-python-env/lib/python3.8/site-packages/telebot/util.py", line 82, in run
    task(*args, **kwargs)
  File "path-to-python-env/lib/python3.8/site-packages/telebot/__init__.py", line 390, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), 
  File "path-to-python-env/lib/python3.8/site-packages/telebot/__init__.py", line 363, in get_updates
    ret.append(types.Update.de_json(ju))
  File "path-to-python-env/lib/python3.8/site-packages/telebot/types.py", line 104, in de_json
    obj['callback_query'] = CallbackQuery.de_json(obj.get('callback_query'))
  File "path-to-python-env/lib/python3.8/site-packages/telebot/types.py", line 1146, in de_json
    return cls(**obj)
TypeError: __init__() missing 1 required positional argument: 'data'
```

In `types.py`:

```python
class CallbackQuery(JsonDeserializable):
    @classmethod
    def de_json(cls, json_string):
        if json_string is None: return None
        obj = cls.check_json(json_string)
        obj['from_user'] = User.de_json(obj.pop('from'))
        if 'message' in obj:
            obj['message'] = Message.de_json(obj.get('message'))
        return cls(**obj)

    def __init__(self, id, from_user, data, chat_instance, message=None, inline_message_id=None, game_short_name=None, **kwargs):
        self.id: int = id
        self.from_user: User = from_user
        self.message: Message = message
        self.inline_message_id: str = inline_message_id
        self.chat_instance: str = chat_instance
        self.data: str = data
        self.game_short_name: str = game_short_name
```

but, as said in the [API documentation](https://core.telegram.org/bots/api#callbackquery), only one of the fields `data` or `game_short_name` will be presented. I fixed this by setting `data` to `None` by default, but I don't know if that's the best way or if it could have other implications.

**Comment by Badiboy** [comment]
Yep, we'll fix.

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/1229
