### ISSUE TITLE
Error with lib

### ISSUE THREAD

**Issue by 13MrBlackCat13** [eternnoir/pyTelegramBotAPI#1258]
Ubuntu 20.04.02
Python 3.8
Error:
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from help import *
  File "/home/mimi/anonfiles/help.py", line 1, in <module>
    from telebot.types import InlineKeyboardMarkup, InlineKeyboardButton
  File "/home/mimi/.local/lib/python3.8/site-packages/telebot/types.py", line 12, in <module>
    from telebot import util
  File "/home/mimi/.local/lib/python3.8/site-packages/telebot/util.py", line 307, in <module>
    def user_link(user: types.User, include_id: bool=False) -> str:
AttributeError: partially initialized module 'telebot.types' has no attribute 'User' (most likely due to a circular import)

**Comment by Badiboy** [comment]
This:
![image](https://user-images.githubusercontent.com/5613421/128635488-beabd062-f63e-48e7-8bc4-ec2df8acc166.png)
works fine for me.

What is your code?
Do you use the most recent version?

**Comment by coder2020official** [comment]
Are you sure you are using pytelegrambotapi, not telebot?
Try:
pip uninstall telebot
pip install pytelegrambotapi

And, is it latest version of pytelegrambotapi?
