### ISSUE TITLE
TypeError: 'in <string>' requires string as left operand, not NoneType

### ISSUE THREAD

**Issue by pendurov** [eternnoir/pyTelegramBotAPI#1289]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.0.0
2. What OS are you using?
MacOS/Debian 20
3. What version of python are you using?
3.9

The code worked stably. After a while, an error began to appear. It comes out when processing text and, sometimes, commands. Attempts to change the version of Python and pyTelegramAPI did not lead to anything. The error occurs both on the server (Debian) and on the local machine (Mac OS)

Full error:
2021-09-05 11:35:41,901 (__init__.py:585 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/__init__.py", line 580, in infinity_polling
    allowed_updates=allowed_updates, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/__init__.py", line 617, in polling
    self.__threaded_polling(none_stop, interval, timeout, long_polling_timeout, allowed_updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/__init__.py", line 676, in __threaded_polling
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/__init__.py", line 638, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/util.py", line 100, in raise_exceptions
    raise self.exception_info
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/util.py", line 82, in run
    task(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/__init__.py", line 391, in __retrieve_updates
    self.process_new_updates(updates)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/__init__.py", line 467, in process_new_updates
    self.process_new_messages(new_messages)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/__init__.py", line 497, in process_new_messages
    self._notify_command_handlers(self.message_handlers, new_messages)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/__init__.py", line 2876, in _notify_command_handlers
    if self._test_message_handler(message_handler, message):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/__init__.py", line 2842, in _test_message_handler
    if not self._test_filter(message_filter, filter_value, message):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/__init__.py", line 2863, in _test_filter
    return test_cases.get(message_filter, lambda msg: False)(message)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/telebot/__init__.py", line 2859, in <lambda>
    'commands': lambda msg: msg.content_type == 'text' and util.extract_command(msg.text) in filter_value,
TypeError: 'in <string>' requires string as left operand, not NoneType

**Comment by Badiboy** [comment]
Somewhere you passed STRING as command filter, not LIST. Check _commands_ parameters in your _message_handler_ handlers

**Comment by pendurov** [comment]
This is my content_type handler:

@bot.message_handler(content_types=['text'])
def handle_messages(message):

and command handler:

@bot.message_handler(commands=["start"])
def cmd_start(message):

**Comment by Badiboy** [comment]
Your bot have only two handlers at all? No error can happen here.

**Comment by coder2020official** [comment]
i think this is not your full code.
Also note that command handler should be first, then content types handler should go

**Comment by pendurov** [comment]
> i think this is not your full code.
> Also note that command handler should be first, then content types handler should go

Of course, this is not all my code. With this code, I showed that I use a LIST, not a STRING.
My content types handler this is the last procedure in the code before if __name__ == '__main__'
Now the error only goes to content type handler, everything is ok for the commands

**Comment by Badiboy** [comment]
> With this code, I showed that I use a LIST, not a STRING.

If you used STRING - your bot would never work. My concern is that SOMEWHERE in your handlers you used string instead of list. By mistake.

**Comment by pendurov** [comment]
> My concern is that SOMEWHERE in your handlers you used string instead of list. By mistake.

You're right! I carefully looked at the entire code and found an error:

@boot. message_handler(command= 'stop')
def self_delete(message):

After I fixed it, everything worked. Thank you very much!
