### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by rafdizon** [eternnoir/pyTelegramBotAPI#1420]
Hello, I'm having issues with this error:
Traceback (most recent call last):
  File "c:\Users\63955\Documents\CODES\python\gramv1_bot\main.py", line 2, in <module>
    import telebot
  File "C:\Users\63955\AppData\Local\Programs\Python\Python39\lib\site-packages\telebot\__init__.py", line 463
    def async():
        ^
SyntaxError: invalid syntax

What should I do? Thank y'all in advance!

pyTelegramBotAPI version: 0.3.0
OS: Windows 11
python version: 3.9.1

**Comment by coder2020official** [comment]
pip uninstall telebot
pip install -U pytelegrambotapi
