### ISSUE TITLE
Hopefully someone can help me 

### ISSUE THREAD

**Issue by PhenomAmd** [eternnoir/pyTelegramBotAPI#1443]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
latest

2. What OS are you using?
ubuntu focal
3. What version of python are you using?
python3.8

well you guys dont provide too much help about webhooks currently im learning python however it gets me so confused when reverse proxy or whatever 

expected behavior webhook working flawlessly

im getting `Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 334, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
`

server has AIOHTTP, nginx, letsencrypt ssl 

current nginx vhost file:

`server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # SSL configuration
        #
         listen 443 ssl default_server;
         listen [::]:443 ssl default_server;
                 server_name domain.com, www.domain.com;
                ssl_certificate  /etc/letsencrypt/live/domain.com/fullchain.pem;
        ssl_certificate_key  /etc/letsencrypt/live/domain.com/privkey.pem;
        root /var/www/html;
 index index.php index.html index.htm index.nginx-debian.html;

        server_name domain.com, www.domain.com;
 location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
        #
        #       # With php7.0-cgi alone:
        #       fastcgi_pass 127.0.0.1:9000;
        #       # With php7.0-fpm:
                fastcgi_pass unix:/run/php/php7.4-fpm.sock;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        location ~ /\.ht {
                deny all;
        }
}

server {
        listen 80;
        listen 443 ssl;
        server_name bot.caliente.help;
        ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;
        location /var/www/html/TOKEN {
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Scheme $scheme;
            proxy_pass http://127.0.0.1:8443/TOKEN/;
    }
}

`
current bot im using its a modified version of this api (it has mysql already on it)

`

# Enable / disable the airdrop
airdrop_live = True

# Telegram
api_token = (
    "TOKEN"  # More: https://core.telegram.org/bots#3-how-do-i-create-a-bot
)

host = "bot.caliente.help"  # ip/host where the bot is running

log_channel = 0  # Channel ID. Example: -1001355597767
admins = []  # Telegram User ID's. Admins are able to execute command "/airdroplist"
airdrop_cap = 100  # Max airdrop submissions that are being accepted
wallet_changes = 3  # How often a user is allowed to change their wallet address

# MySQL Database
mysql_host = "localhost"
mysql_db = ""
mysql_user = ""
mysql_pw = ""

`

my main.py

`import re
import ssl
from io import BytesIO
from time import gmtime, strftime

import pymysql
import telebot
from aiohttp import web
from telebot import types
from telebot.types import InlineKeyboardButton, InlineKeyboardMarkup

import config

WEBHOOK_HOST = config.host
WEBHOOK_PORT = 8443  # 443, 80, 88 or 8443 (port needs to be 'open')
WEBHOOK_LISTEN = "0.0.0.0"  # In some VPS you may need to put here the IP addr.

WEBHOOK_SSL_CERT = "/etc/letsencrypt/live/caliente.help/fullchain.pem"  # Path to the ssl certificate
WEBHOOK_SSL_PRIV = "/etc/letsencrypt/live/caliente.help/privkey.pem"  # Path to the ssl private key

WEBHOOK_URL_BASE = "https://{}:{}".format(WEBHOOK_HOST, WEBHOOK_PORT)
WEBHOOK_URL_PATH = "/{}/".format(config.api_token)

bot = telebot.TeleBot(config.api_token)

app = web.Application()

def get_connection():
    connection = pymysql.connect(
        host=config.mysql_host,
        user=config.mysql_user,
        password=config.mysql_pw,
        db=config.mysql_db,
        charset="utf8mb4",
        cursorclass=pymysql.cursors.DictCursor,
        autocommit=True,
    )
create_db_tables = create_tables()
airdrop_users = get_airdrop_users()
airdrop_wallets = get_airdrop_wallets()

bot.enable_save_next_step_handlers(delay=2)
bot.load_next_step_handlers()

create_db_tables

# Remove webhook, it fails sometimes the set if there is a previous webhook
bot.remove_webhook()

# Set webhook
bot.set_webhook(
    url=WEBHOOK_URL_BASE + WEBHOOK_URL_PATH, certificate=open(WEBHOOK_SSL_CERT, "r")
)

# Process webhook calls
async def handle(request):
    if request.match_info.get("token") == bot.token:
        request_body_dict = await request.json()
        update = telebot.types.Update.de_json(request_body_dict)
        bot.process_new_updates([update])
        return web.Response()
    else:
        return web.Response(status=403)

app.router.add_post("/{token}/", handle)

# Start aiohttp server
web.run_app(
    app,
    host="0.0.0.0",
    port=WEBHOOK_PORT
)
`

i removed ssl context as somehwere people said that if you use nginx reverse proxy you dont need to set ssl again  
i feel is something really dumb from myself something im missing but its been 2 days since im trying to figure it out

**Comment by coder2020official** [comment]
Hello.
What line is this error happening?
Are you sure about your configuration?
