### ISSUE TITLE
Can't patch by gevent

### ISSUE THREAD

**Issue by jiajunhuang** [eternnoir/pyTelegramBotAPI#1537]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.5.0
2. What OS are you using?
Linux
3. What version of python are you using?
3.9.5

When I add gevent patch in top of the `main.py`, and run it, I got this exception:

```python
2022-05-08 08:58:07,849 (__init__.py:575 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/home/jiajun/.pyenv/versions/3.9.5/lib/python3.9/site-packages/telebot/__init__.py", line 569, in infinity_polling
    self.polling(none_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/home/jiajun/.pyenv/versions/3.9.5/lib/python3.9/site-packages/telebot/__init__.py", line 618, in polling
    self.__threaded_polling(non_stop, interval, timeout, long_polling_timeout, allowed_updates)
  File "/home/jiajun/.pyenv/versions/3.9.5/lib/python3.9/site-packages/telebot/__init__.py", line 628, in __threaded_polling
    or_event = util.OrEvent(
  File "/home/jiajun/.pyenv/versions/3.9.5/lib/python3.9/site-packages/telebot/util.py", line 426, in OrEvent
    orify(e, changed)
  File "/home/jiajun/.pyenv/versions/3.9.5/lib/python3.9/site-packages/telebot/util.py", line 402, in orify
    e._set = e.set
AttributeError: 'gevent._gevent_cevent.Event' object has no attribute '_set'
```

the minimal demo:

```python
from gevent.monkey import patch_all
patch_all(patch_all=True)

import logging
import multiprocessing

import telebot

from config import config

bot = telebot.TeleBot(config.BOT_TOKEN, parse_mode="MARKDOWN", num_threads=multiprocessing.cpu_count() * 2)


if __name__ == '__main__':
    logging.info("starting bot...")
    bot.infinity_polling(logger_level=logging.INFO)
```

**Comment by coder2020official** [comment]
This error has nothing to do with telebot ...

**Comment by coder2020official** [comment]
Let me check util file

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/167314497-0e54da7e-b0d7-4a04-ae7b-e2b9fdc0465a.png)

You patched **something**. So it make **some** replacements, one of which is not compatible with pyTelegramBotAPI calls. 

Do not use patches. ¯\_(ツ)_/¯
