### ISSUE TITLE
missing 1 required positional argument: 'file_path'

### ISSUE THREAD

**Issue by re3turn** [eternnoir/pyTelegramBotAPI#1539]
1. What version of pyTelegramBotAPI are you using?
4.5.1
2. What OS are you using?
debian([python:3.10](https://hub.docker.com/_/python))

3. What version of python are you using?
 3.10.4

Call upload_sticker_file() and I get the following error:
```Python traceback
Traceback (most recent call last):
  File "/service/app/sticker.py", line 185, in create_sticker_set
    uploaded_file = await bot.upload_sticker_file(user_id, png)
   File "/usr/local/lib/python3.10/site-packages/telebot/async_telebot.py", line 3302, in upload_sticker_file
     return types.File.de_json(result)
   File "/usr/local/lib/python3.10/site-packages/telebot/types.py", line 910, in de_json
     return cls(**obj)
 TypeError: File.__init__() missing 1 required positional argument: 'file_path'
```

sample code
```python
    async def create_sticker_set(user_id, png_path):
            with open(png_path, 'rb') as png:
                uploaded_file = await bot.upload_sticker_file(user_id, png)
```

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/1540

Check, pls.

**Comment by re3turn** [comment]
thanks for fixing!
