### ISSUE TITLE
module 'telebot' has no attribute 'TeleBot'

### ISSUE THREAD

**Issue by ffeldbauer** [eternnoir/pyTelegramBotAPI#1554]
I have seen this issue already in #341 but that issue was closed without an answer to the original question.

OS: Debian 11.3
Python 3.9.2

I installed pyTelegramBotAPI with
```
pip3 install pyTelegramBotAPI
```

My test script:
```python
import telebot

bot = telebot.TeleBot("YOUR_BOT_TOKEN")

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
	bot.reply_to(message, "Howdy, how are you doing?")

@bot.message_handler(func=lambda message: True)
def echo_all(message):
	bot.reply_to(message, message.text)

bot.infinity_polling()
```
Running the script results in:
```bash
python3 baa.py 
Traceback (most recent call last):
  File "/home/florian/foo/baa.py", line 3, in <module>
    bot = telebot.TeleBot("YOUR_BOT_TOKEN")
AttributeError: module 'telebot' has no attribute 'TeleBot'
```

**Comment by coder2020official** [comment]
```
pip3 uninstall telebot
pip3 install pyTelegramBotAPI
```

**Comment by ffeldbauer** [comment]
```
pip3 uninstall telebot
WARNING: Skipping telebot as it is not installed.

pip3 install pyTelegramBotAPI
Requirement already satisfied: pyTelegramBotAPI in ./.local/lib/python3.9/site-packages (4.5.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from pyTelegramBotAPI) (2.25.1)

python3 baa.py 
Traceback (most recent call last):
  File "/home/florian/foo/baa.py", line 3, in <module>
    bot = telebot.TeleBot("YOUR_BOT_TOKEN")
AttributeError: module 'telebot' has no attribute 'TeleBot'
```

**Comment by coder2020official** [comment]
Are you running file using python3?

**Comment by Badiboy** [comment]
> Requirement already satisfied: pyTelegramBotAPI in ./.local/lib/python3.9/site-packages (4.5.1)

Your package are locally installed.

Try
`sudo pip3 uninstall telebot`

**Comment by ffeldbauer** [comment]
`sudo` is disabled by default on Debian and as I never install python packages using pip as super user, it will result in the same as above. Also I never ran `pip3 install telebot` in the first place.

And yes, as you can see from my post above, I'm running my file with python3

**Comment by Badiboy** [comment]
Okay...
How about this?

```
import telebot
print(dir(telebot))
```

**Comment by ffeldbauer** [comment]
I could get it working if I modify above script like this:

```python
import telebot
from telebot import TeleBot

bot = TeleBot("YOUR_BOT_TOKEN")
...
```

But without the 2nd line it keeps telling me telebot does not have an attribute TeleBot

```
>>> import telebot
>>> print(dir(telebot))
['AdvancedCustomFilter', 'Any', 'BaseMiddleware', 'Callable', 'CancelUpdate', 'ExceptionHandler', 'FileHandlerBackend', 'Handler', 'List', 'MemoryHandlerBackend', 'Optional', 'REPLY_MARKUP_TYPES', 'SimpleCustomFilter', 'SkipHandler', 'StateMemoryStorage', 'StatePickleStorage', 'TeleBot', 'Union', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'apihelper', 'console_output_handler', 'custom_filters', 'datetime', 'formatter', 'handler_backends', 'inspect', 'logger', 'logging', 're', 'storage', 'sys', 'telebot', 'threading', 'time', 'traceback', 'types', 'util']
```
But TeleBot is listed here

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/168774470-4176b00d-77cf-4c25-aa40-aa3a654a6ae3.png)

It works fine for me. You should further deal with your system and your packages, locations etc.
