### ISSUE TITLE
TeleBot().edit_message_media() function is not does not work

### ISSUE THREAD

**Issue by foxi0802** [eternnoir/pyTelegramBotAPI#1600]
### Code of my function:
```
@bot.callback_query_handler(func=lambda call: True)
def callback_query(call):
	if call.data == "some_call":
		bot.edit_message_media(call.message.chat.id, call.message.id, media=open("some_image.jpg", "rb"))
		bot.edit_message_text(call.message.chat.id, call.message.id, text="Some text.")
```

### Error:
2022-06-30 16:04:12,763 (__init__.py:615 MainThread) ERROR - TeleBot: "Infinity polling exception: TeleBot.edit_message_media() got multiple values for argument 'media'"
2022-06-30 16:04:12,780 (__init__.py:617 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 611, in infinity_polling
    self.polling(none_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 658, in polling
    self.__threaded_polling(non_stop, interval, timeout, long_polling_timeout, allowed_updates)
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 720, in __threaded_polling
    raise e
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 680, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 135, in raise_exceptions
    raise self.exception_info
  File "C:\Users\Professional\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 87, in run
    task(*args, **kwargs)
  File "C:\Users\Professional\Desktop\Cybertrack\bot.py", line 15, in callback_query
    bot.edit_message_media(call.message.chat.id, call.message.id, media=open("some_image.jpg", "rb"), caption="Some text")
TypeError: TeleBot.edit_message_media() got multiple values for argument 'media'

**Comment by Badiboy** [comment]
https://core.telegram.org/bots/api#editmessagemedia

No caption in edit_message_media.

**Comment by Badiboy** [comment]
Also wrong parameters order.

![image](https://user-images.githubusercontent.com/5613421/176687898-9a2c9a6d-5c50-432b-988e-7a32b6ce92b7.png)

**Comment by foxi0802** [comment]
### I'm edited code of function:
`@bot.callback_query_handler(func=lambda call: True)
def callback_query(call):
	if call.data == "some_call":
		bot.edit_message_media(open("some_image.jpg", "rb"), call.message.chat.id, call.message.id)
		bot.edit_message_text("Some text.", call.message.chat.id, call.message.id)`

### But there is another error:
2022-06-30 16:34:33,941 (__init__.py:688 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: parameter "media" is required"

**Comment by Badiboy** [comment]
Try this:

```
media = types.InputMediaPhoto(open("some_image.jpg", "rb"), caption="Some text")
bot.edit_message_media(media , call.message.chat.id, call.message.id)
```
