### ISSUE TITLE
Error with sending text/placeholders with underscore ("_") when parsing mode is MARKDOWN

### ISSUE THREAD

**Issue by EdwyReed** [eternnoir/pyTelegramBotAPI#1608]
Hi!
I'm working on bot for my public and i need to send messages that contains my username. But my username contains underscore (@edwy_reed) and when i sending message - it raises an Exception below.

1. What version of pyTelegramBotAPI are you using? - pyTelegramBotAPI==4.6.0

2. What OS are you using? - Windows 10

3. What version of python are you using? - 3.10

```
2022-07-06 16:50:10,615 (__init__.py:660 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 5"
2022-07-06 16:50:10,615 [MainThread  ] [ERROR]  Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 5
2022-07-06 16:50:10,617 (__init__.py:662 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 651, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "c:\Users\wadel\Documents\beariy\bot\telegram-bot\main.py", line 192, in unknown_command
    bot.send_message(message.chat.id, "@edwy_reed", reply_markup=markup)
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 1019, in send_message
    apihelper.send_message(
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\apihelper.py", line 267, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\apihelper.py", line 152, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\apihelper.py", line 179, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 5
"
2022-07-06 16:50:10,617 [MainThread  ] [ERROR]  Exception traceback:
Traceback (most recent call last):
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 651, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\util.py", line 93, in run
    task(*args, **kwargs)
  File "c:\Users\wadel\Documents\beariy\bot\telegram-bot\main.py", line 192, in unknown_command
    bot.send_message(message.chat.id, "@edwy_reed", reply_markup=markup)
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\__init__.py", line 1019, in send_message
    apihelper.send_message(
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\apihelper.py", line 267, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\apihelper.py", line 152, in _make_request
    json_result = _check_result(method_name, result)
  File "C:\Users\wadel\AppData\Local\Programs\Python\Python310\lib\site-packages\telebot\apihelper.py", line 179, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 5
```

**Comment by EdwyReed** [comment]
> **Telegram** parser

I was thinking that tg use double underscore for italic, isn't it?

**Comment by coder2020official** [comment]
Use formatting, it automatically escapes sich characters:
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/formatting_example.py

**Comment by EdwyReed** [comment]
Switched to HTML parser, it's a lot simplier to use inside of complicated string with a variables. But thanx for explanation and help!

**Comment by Badiboy** [comment]
👍
