### ISSUE TITLE
Unclear exception when using class middlewares with `ENABLE_MIDDLEWARE = True`

### ISSUE THREAD

**Issue by Jaakkonen** [eternnoir/pyTelegramBotAPI#1622]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.6.0

2. What OS are you using?
Arch linux

3. What version of python are you using?
3.10.5

When adding `from telebot import apihelper; apihelper.ENABLE_MIDDLEWARE = True` to a bot using class middlewares one gets an unclear error message.

For example adding that to the basic class middleware example https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/middleware/class_based/basic_example.py one gets following error when the bot tries to handle a message

```
2022-07-13 02:08:39,671 (__init__.py:576 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/telebot/__init__.py", line 570, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/python3.10/site-packages/telebot/__init__.py", line 621, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/usr/lib/python3.10/site-packages/telebot/__init__.py", line 695, in __threaded_polling
    raise e
  File "/usr/lib/python3.10/site-packages/telebot/__init__.py", line 650, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/usr/lib/python3.10/site-packages/telebot/util.py", line 111, in raise_exceptions
    raise self.exception_info
  File "/usr/lib/python3.10/site-packages/telebot/util.py", line 93, in run
    task(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/telebot/__init__.py", line 363, in __retrieve_updates
    self.process_new_updates(updates)
  File "/usr/lib/python3.10/site-packages/telebot/__init__.py", line 393, in process_new_updates
    self.process_middlewares(update)
  File "/usr/lib/python3.10/site-packages/telebot/__init__.py", line 523, in process_middlewares
    for update_type, middlewares in self.typed_middleware_handlers.items():
AttributeError: 'TeleBot' object has no attribute 'typed_middleware_handlers'
```

The error should probably tell that class middlewares are unsupported when having `ENABLE_MIDDLEWARE = True` on, or support for class middlewares to work with that option added.

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/178697409-6fb19645-80df-4fc1-96f7-642579555258.png)
