### ISSUE TITLE
A request to the Telegram API was unsuccessful

### ISSUE THREAD

**Issue by carlosgrillet** [eternnoir/pyTelegramBotAPI#1658]
Hi! I'm currently running pyTelegramBotAPI in the version 4.6.1, in a server with Ubuntu 22.04.1 LTS x86_64, using Python 3.10.4

I have this code
```
import telebot

API_TOKEN = "MY-API-KEY"
bot = telebot.TeleBot(API_TOKEN)

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
        bot.reply_to(message, "Howdy, how are you doing?")

@bot.message_handler(func=lambda message: True)
def echo_all(message):
        bot.reply_to(message, message.text)

bot.infinity_polling()
```

Just copied the code from the documentation. But I have this error when I run ```python3 program.py```
```
2022-08-09 11:18:46,670 (__init__.py:986 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first"
2022-08-09 11:18:46,672 (__init__.py:988 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/home/operip/.local/lib/python3.10/site-packages/telebot/__init__.py", line 976, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/operip/.local/lib/python3.10/site-packages/telebot/util.py", line 116, in raise_exceptions
    raise self.exception_info
  File "/home/operip/.local/lib/python3.10/site-packages/telebot/util.py", line 98, in run
    task(*args, **kwargs)
  File "/home/operip/.local/lib/python3.10/site-packages/telebot/__init__.py", line 601, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "/home/operip/.local/lib/python3.10/site-packages/telebot/__init__.py", line 575, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "/home/operip/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 324, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/operip/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 152, in _make_request
    json_result = _check_result(method_name, result)
  File "/home/operip/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 179, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first
```

Any idea of what could it be?

**Comment by Badiboy** [comment]
> telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: **Conflict: can't use getUpdates method while webhook is active; use deleteWebhook to delete the webhook first**

Seems clear, no?

**Comment by carlosgrillet** [comment]
Thank you for reply me. I found the solution in other page. What I have to do is add ```bot.set_webhook()```  in the code, so it will looks like this
```
import telebot

API_TOKEN = "MY-API-KEY"
bot = telebot.TeleBot(API_TOKEN)
bot.set_webhook()

@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
        bot.reply_to(message, "Howdy, how are you doing?")

@bot.message_handler(func=lambda message: True)
def echo_all(message):
        bot.reply_to(message, message.text)

bot.infinity_polling()
```
