### ISSUE TITLE
Threaded polling exception 409 "make sure that only one bot instance is running"

### ISSUE THREAD

**Issue by setovi** [eternnoir/pyTelegramBotAPI#1778]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

pyTelegramBotAPI   4.7.1

2. What OS are you using?

docker images in Mac OS Ventura and Ubuntu 22.04 on Raspberry Pi 4. Same behaviour.

3. What version of python are you using?

3.8-buster
3.9-bullseye

Same behaviour.

The bot runs fine but the following appears continuously in the logs. First every few seconds, some time later about 30+ seconds every exception.

2022-11-02 10:02:01,917 (__init__.py:1089 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/telebot/__init__.py", line 1077, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/usr/local/lib/python3.8/site-packages/telebot/util.py", line 116, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.8/site-packages/telebot/util.py", line 98, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telebot/__init__.py", line 653, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "/usr/local/lib/python3.8/site-packages/telebot/__init__.py", line 627, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 334, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

Obviously no more than one instance running.

Thanks in advance

**Comment by Badiboy** [comment]
> Obviously no more than one instance running.

Not obviously without any details. If Telegram says it does - it definitely does. 
Check your code, may be it runs in parallel.

**Comment by setovi** [comment]
But this is the code 😀 :

from config import *
import telebot

bot = telebot.TeleBot(TELEGRAM_TOKEN)

@bot.message_handler(commands=["start", "help"])
def cmd_start(message):
    bot.reply_to(message, "Hi!")

if __name__ == "__main__":
    print("Starting bot")
    bot.infinity_polling()
    print("End")


Maybe when one run is finished, the Telegram API does not know so the next bot execution triggers the message?

**Comment by Badiboy** [comment]
print("Starting bot")

1. Show the console output after program starts and before Telegram error.
2. Show the config which you imports.

**Comment by setovi** [comment]
Console output:

`Starting bot
2022-11-03 13:45:22,690 (__init__.py:1087 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running"                                       
2022-11-03 13:45:22,691 (__init__.py:1089 MainThread) ERROR - TeleBot: "Exception traceback:                                                                                                                                                                                                                               
Traceback (most recent call last):                                                                                                                                                                                                                                                                                         
  File "/home/user/.local/lib/python3.10/site-packages/telebot/__init__.py", line 1077, in __threaded_polling                                                                                                                                                                                                             
    polling_thread.raise_exceptions()                                                                                                                                                                                                                                                                                      
  File "/home/user/.local/lib/python3.10/site-packages/telebot/util.py", line 116, in raise_exceptions                                                                                                                                                                                                                    
    raise self.exception_info                                                                                                                                                                                                                                                                                              
  File "/home/user/.local/lib/python3.10/site-packages/telebot/util.py", line 98, in run                                                                                                                                                                                                                                  
    task(*args, **kwargs)                                                                                                                                                                                                                                                                                                  
  File "/home/user/.local/lib/python3.10/site-packages/telebot/__init__.py", line 653, in __retrieve_updates                                                                                                                                                                                                              
    updates = self.get_updates(offset=(self.last_update_id + 1),                                                                                                                                                                                                                                                           
  File "/home/user/.local/lib/python3.10/site-packages/telebot/__init__.py", line 627, in get_updates                                                                                                                                                                                                                     
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates, long_polling_timeout)                                                                                                                                                                                                        
  File "/home/user/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 334, in get_updates                                                                                                                                                                                                                    
    return _make_request(token, method_url, params=payload)                                                                                                                                                                                                                                                                
  File "/home/user/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 162, in _make_request                                                                                                                                                                                                                  
    json_result = _check_result(method_name, result)                                                                                                                                                                                                                                                                       
  File "/home/user/.local/lib/python3.10/site-packages/telebot/apihelper.py", line 189, in _check_result                                                                                                                                                                                                                  
    raise ApiTelegramException(method_name, result, result_json)                                                                                                                                                                                                                                                           
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 409. Description: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running                                                                                                    
"                                                                                                                                                                                                                                    
`

The config.py is just one line,

TELEGRAM_TOKEN = "mybotprivatetoken"

**Comment by Badiboy** [comment]
Can you try to simply remove this line?
`if name == "main":`

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/199735195-2c5578e4-6b5c-45d7-b1a0-c69ef0dd2c0b.png)

Everything is fine for me.

**Comment by Badiboy** [comment]
![image](https://user-images.githubusercontent.com/5613421/199735321-fa1de5fc-a375-4cb5-a8f1-481ebc457ac3.png)

Everything is fine for me.

**Comment by CATTYCorolCat** [comment]
у меня версия бота - 0.9.9.3
ОП - windows 10
python 3.12

могу помочь, если до сих пор актуально, перейди в папку пайтона(у меня C:\Users\компьютер\AppData\Local\Programs\Python\Python312). 
Зайди в папку Lib\site-packages и удали все папки TeleBotapi. Потом заново зайди в CMD и с помощью pip попробуй снова установить(pip install teleBotAPI). Мне помогло. 
Как я понял ошибка вызывается из-за множества версий установленного telebotapi.
Надеюсь я помог!
