### ISSUE TITLE
TeleBot: "module 'collections' has no attribute 'Hashable'"

### ISSUE THREAD

**Issue by InevitablePG** [eternnoir/pyTelegramBotAPI#1819]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

pyTelegramBotAPI 4.8.0

2. What OS are you using?

Linux

3. What version of python are you using?

Python 3.11.0

I have an async timer bot but since Python 3.10 it's giving me an error. I also tried the example code of an async timer bot on the repository but same as well.

here is the code

```
import asyncio
import aioschedule
from telebot.async_telebot import AsyncTeleBot

API_TOKEN = ''
bot = AsyncTeleBot(API_TOKEN)


async def beep(chat_id) -> None:
    """Send the beep message."""
    await bot.send_message(chat_id, text='Beep!')
    aioschedule.clear(chat_id)  # return schedule.CancelJob not working in aioschedule use tag for delete


@bot.message_handler(commands=['help', 'start'])
async def send_welcome(message):
    await bot.reply_to(message, "Hi! Use /set <seconds> to set a timer")


@bot.message_handler(commands=['set'])
async def set_timer(message):
    args = message.text.split()
    if len(args) > 1 and args[1].isdigit():
        sec = int(args[1])
        aioschedule.every(sec).seconds.do(beep, message.chat.id).tag(message.chat.id)
    else:
        await bot.reply_to(message, 'Usage: /set <seconds>')


@bot.message_handler(commands=['unset'])
def unset_timer(message):
    aioschedule.clean(message.chat.id)


async def scheduler():
    while True:
        await aioschedule.run_pending()
        await asyncio.sleep(1)


async def main():
    await asyncio.gather(bot.infinity_polling(), scheduler())


if __name__ == '__main__':
    asyncio.run(main())
```

And the error I get is this one

```
2022-11-30 21:47:49,410 (async_telebot.py:543 MainThread) ERROR - TeleBot: "module 'collections' has no attribute 'Hashable'"
2022-11-30 21:47:54,678 (async_telebot.py:367 MainThread) ERROR - TeleBot: "Infinity polling: polling exited"
2022-11-30 21:47:54,679 (async_telebot.py:369 MainThread) ERROR - TeleBot: "Break infinity polling"
Traceback (most recent call last):
  File "/storage/emulated/0/Takealot/sendVideo.py", line 52, in <module>
    asyncio.run(main())
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/storage/emulated/0/Takealot/sendVideo.py", line 48, in main
    await asyncio.gather(bot.infinity_polling(), scheduler())
  File "/storage/emulated/0/Takealot/sendVideo.py", line 43, in scheduler
    await aioschedule.run_pending()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/aioschedule/__init__.py", line 544, in run_pending
    await default_scheduler.run_pending()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/aioschedule/__init__.py", line 111, in run_pending
    return await asyncio.wait(jobs, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
sys:1: RuntimeWarning: coroutine 'Job.run' was never awaited

```

Thank you.

**Comment by Badiboy** [comment]
The cause is the novell Python. We'll check.

**Comment by Badiboy** [comment]
@coder2020official 
https://bugs.python.org/issue37324

**Comment by coder2020official** [comment]
It is aioschedules issue?

**Comment by coder2020official** [comment]
https://github.com/ablab/spades/issues/873#issuecomment-1011073085
found smth

**Comment by Badiboy** [comment]
@InevitablePG I do not see any "Hashable" in the library. Check other libraries you used...

**Comment by InevitablePG** [comment]
I used the <a href="https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/asynchronous_telebot/timer_bot_async.py" >examples</a> code exacly as it is. I didn't add any libraries.

**Comment by Badiboy** [comment]
https://github.com/ibrb/python-aioschedule/pull/2

This is the problem in aioschedule. You should wait until they fix it...

But last commit there was 5 years ago:
![image](https://user-images.githubusercontent.com/5613421/205386073-d1523181-67d5-405d-a8b6-16fe7a41ec5a.png)
so i advice you to use something else...

**Comment by InevitablePG** [comment]
I understand, thank you.

**Comment by coder2020official** [comment]
I'd recommend using apscheduler instead of aioschedule. I use it myself and find it comfortable to use
