### ISSUE TITLE
Sending videos

### ISSUE THREAD

**Issue by cc00010** [eternnoir/pyTelegramBotAPI#1857]
How do I send videos using `open`?

Telebot version: `4.8.0`
Python: `Python 3.9.7 (default, Sep  3 2021, <>) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin`

I tried this:
```python3
# Python version: 3
fd = open(<path_to_file>, "rb")
bot.send_video(<chat_id_here>, fd) # or telebot.types.InputFile(fd)
```

and it's giving this error: `A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: there is no video in the request`

The traceback is here:
```
Traceback (most recent call last):                                                                                                                                                        
  File "/Users/<>/cc/ihatebots/src/main.py", line 4, in <module>                                                                                                                        
    import scopes.<>                                                                                                                                                               
  File "/Users/<>/cc/ihatebots/src/scopes/<>.py", line 23, in <module>                                                                                                           
    bot.send_video(chat_id=<>, video=buf)                                                                                                                
  File "/Users/<>/cc/ihatebots/lib/python3.9/site-packages/telebot/__init__.py", line 2213, in send_video                                                                               
    apihelper.send_video(                                                                                                                                                                 
  File "/Users/<>/cc/ihatebots/lib/python3.9/site-packages/telebot/apihelper.py", line 705, in send_video                                                                               
    return _make_request(token, method_url, params=payload, files=files, method='post')                                                                                                   
  File "/Users/<>/cc/ihatebots/lib/python3.9/site-packages/telebot/apihelper.py", line 162, in _make_request                                                                            
    json_result = _check_result(method_name, result)                                                                                                                                      
  File "/Users/<>/cc/ihatebots/lib/python3.9/site-packages/telebot/apihelper.py", line 189, in _check_result                                                                            
    raise ApiTelegramException(method_name, result, result_json)                                                                                                                          
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: there is no video in the request
```

**Comment by cc00010** [comment]
Same thing with `bot.send_photo`

**Comment by coder2020official** [comment]
Never encountered this before. Version?

**Comment by cc00010** [comment]
@coder2020official it's: `__version__ = '4.8.0'`

**Comment by coder2020official** [comment]
And py version?

**Comment by cc00010** [comment]
@coder2020official 3

**Comment by coder2020official** [comment]
Too old, lib supports python 3.6+

**Comment by cc00010** [comment]
@coder2020official I mean it's `3.9.7`

**Comment by coder2020official** [comment]
Can u give a sample code so I can reproduce the issue?

**Comment by cc00010** [comment]
@coder2020official the code I posted is the whole code. 

Okay, seems like something is wrong with my `virtualenv`. I created a new one and installed the package, and it's working somehow. Weird..
