### ISSUE TITLE
aiohttp invalid method encountered

### ISSUE THREAD

**Issue by almaz5000** [eternnoir/pyTelegramBotAPI#1871]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI ==4.8.0
2. What OS are you using?
Debian==11 (bullseye)
3. What version of python are you using?
Python==3.9.2
4. Used module versions
aiohttp==3.8.3

I use webhooks for delivering messages and **aiohttp** framework. 
My bot was in idle for last one day. I suppose no one user sent any request in a bot.
But any way I catch this error. What can it be?
Btw, bot is working, it is just strange error...

**Bot`s code**
```
import telebot
from telebot import types
import ssl
from aiohttp import web

API_TOKEN = conf.token
DATABASE = conf.database

WEBHOOK_HOST = conf.host
WEBHOOK_PORT = 443  # 443, 80, 88 or 8443 (port need to be 'open')
WEBHOOK_LISTEN = '0.0.0.0'  # In some VPS you may need to put here the IP addr

WEBHOOK_SSL_CERT = './webhook_cert.pem'  # Path to the ssl certificate
WEBHOOK_SSL_PRIV = './webhook_pkey.pem'  # Path to the ssl private key

WEBHOOK_URL_BASE = "https://{}:{}".format(WEBHOOK_HOST, WEBHOOK_PORT)
WEBHOOK_URL_PATH = "/{}/".format(API_TOKEN)

logger = telebot.logger
telebot.logger.setLevel(logging.DEBUG)

bot = telebot.TeleBot(conf.token)
user = User(DATABASE)
app = web.Application()


async def handle(request):
    if request.match_info.get('token') == bot.token:
        request_body_dict = await request.json()
        update = telebot.types.Update.de_json(request_body_dict)
        bot.process_new_updates([update])
        return web.Response()
    else:
        return web.Response(status=403)


app.router.add_post('/{token}/', handle)


@bot.message_handler(commands=['start'])
def start(message):
   starting_message()

bot.remove_webhook()
sleep(1)
# Set webhook
bot.set_webhook(url=WEBHOOK_URL_BASE + WEBHOOK_URL_PATH,
                certificate=open(WEBHOOK_SSL_CERT, 'r'))

# Build ssl context
context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
context.load_cert_chain(WEBHOOK_SSL_CERT, WEBHOOK_SSL_PRIV)

# Start aiohttp server
web.run_app(
    app,
    host=WEBHOOK_LISTEN,
    port=WEBHOOK_PORT,
    ssl_context=context,
)

```
**Error`s traceback**
```
: Error handling request
: Traceback (most recent call last):
:   File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_protocol.py", line 332, in data_received
:     messages, upgraded, tail = self._request_parser.feed_data(data)
:   File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
: aiohttp.http_exceptions.BadStatusLine: 400, message="Bad status line 'Invalid method encountered'"
: Error handling request
: Traceback (most recent call last):
:   File "/usr/local/lib/python3.9/dist-packages/aiohttp/web_protocol.py", line 332, in data_received
:     messages, upgraded, tail = self._request_parser.feed_data(data)
:   File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
: aiohttp.http_exceptions.BadHttpMessage: 400, message='Pause on PRI/Upgrade'
```

**Comment by Badiboy** [comment]
Looks like something on aiohttp side.

Try to read this:

**Comment by coder2020official** [comment]
How often are you encountering this error?

**Comment by almaz5000** [comment]
> How often are you encountering this error?

One or two times in a day. It has never coincided with the actions of the users. It just appears in log sometime.
