### ISSUE TITLE
File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 189, in _check_result     raise ApiTelegramException(method_name, result, result_json) telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Character '=' is reserved and must be escaped with the preceding '\'

### ISSUE THREAD

**Issue by SL-Hydra** [eternnoir/pyTelegramBotAPI#1908]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?  Latest

2. What OS are you using? Android termux

3. What version of python are you using?  Latest

023-02-08 13:03:31,406 (__init__.py:1083 MainThread) ERROR - TeleBot: "Threaded polling exception: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Character '=' is reserved and must be escaped with the preceding '\'"
2023-02-08 13:03:31,423 (__init__.py:1085 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telebot/__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telebot/util.py", line 156, in raise_exceptions
    raise self.exception_info
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telebot/util.py", line 100, in run
    task(*args, **kwargs)                                                                 File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telebot/__init__.py", line 6308, in _run_middlewares_and_handler                                               result = handler['function'](message)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                 File "/data/data/com.termux/files/home/HYDRA-TG-BOT/tbot.py", line 113, in command_animation1                                                                                     msg = bot.reply_to(m, "=>           [10%]")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telebot/__init__.py", line 4320, in reply_to
    return self.send_message(message.chat.id, text, reply_to_message_id=message.message_id, **kwargs)                                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telebot/__init__.py", line 1549, in send_message
    apihelper.send_message(
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 264, in send_message
    return _make_request(token, method_url, params=payload, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 162, in _make_request                                                              json_result = _check_result(method_name, result)                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/telebot/apihelper.py", line 189, in _check_result                                                              raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Character '=' is reserved and must be escaped with the preceding '\\'                                           
"

Bro, how to solve this error?

**Comment by Badiboy** [comment]
Request: can't parse entities: **Character '=' is reserved and must be escaped with the preceding '\'**

PS. Make normal issue header or it will be closed.
