### ISSUE TITLE
Request timeout. Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000021CCDE23DC0> files=None request_timeout=300

### ISSUE THREAD

**Issue by Zapzatron** [eternnoir/pyTelegramBotAPI#1993]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 4.10.0

2. What OS are you using? Windows

3. What version of python are you using? 3.10.9

I get the following error after every message from telegram (webhook):
```
Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\telebot\async_telebot.py", line 516, in _run_middlewares_and_handlers
    result = await handler['function'](message)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\Zapzatron_Bot_WebHook_Async.py", line 1346, in get_command_text
    await about_us(message_2)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\Zapzatron_Bot_WebHook_Async.py", line 428, in about_us
    await bot.send_message(chat_id, about_us_text)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\telebot\async_telebot.py", line 2415, in send_message
    await asyncio_helper.send_message(
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 306, in send_message
    return await _process_request(token, method_name, params=params)
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\telebot\asyncio_helper.py", line 105, in _process_request
    raise RequestTimeout("Request timeout. Request: method={0} url={1} params={2} files={3} request_timeout={4}".format(method, url, params, files, request_timeout, current_try))
telebot.asyncio_helper.RequestTimeout: Request timeout. Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000021CCDE23DC0> files=None request_timeout=300
```

And I also get the following error:
```
2023-05-27 23:09:06,381 (asyncio_helper.py:103 MainThread) ERROR - TeleBot: "Unknown error: RuntimeError"
```

How can I fix this?

**Comment by Badiboy** [comment]
RequestTimeout: Request timeout.

1. Have better internet connecton.
2. Handle exception properly.

**Comment by Zapzatron** [comment]
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/100136305/19301dca-ab48-426d-9bf2-d814407050a6)

**Comment by Zapzatron** [comment]
I built the same version but without asynchrony and it works fine

**Comment by coder2020official** [comment]
Your internet is not always stable. If it rarely happens then it is fine
You have to set non_stop=True in polling in order to avoid bot failures

**Comment by Zapzatron** [comment]
I don't have polling. I have webhook

**Comment by coder2020official** [comment]
Then you don't have to worry about non stop

**Comment by Zapzatron** [comment]
I have RequestTimeout only when I use Async bot

**Comment by Creat55** [comment]
same error with async sendmessage
ERROR - TeleBot: "Unknown error: RuntimeError"
ERROR: Request timeout. Request: method=get url=sendMessage params=<aiohttp.formdata.FormData object at 0x0000029186C9C790> files=None request_timeout=300
