### ISSUE TITLE
TypeError: attribute name must be string, not 'int'

### ISSUE THREAD

**Issue by Mr-X-2100** [eternnoir/pyTelegramBotAPI#2032]
1. What version of pyTelegramBotAPI are you using? 4.12.0

2. What OS are you using? windows 11

3. What version of python are you using? 3.11.0

Hello
I created the following class for next_step_backend, but I get an error that I don't understand what the problem is.

```
class MySQLHandlerBackend:
    def __init__(self):
        self.connection = mysql.connector.connect(
            host="localhost",
            user="root",
            password="",
            database="Telegram_Bot",
            charset="utf8mb4",
        )

    def get_handlers(self, chat_id):
        cursor = self.connection.cursor()
        cursor.execute("SELECT data FROM next_step WHERE chat_id = %s", (chat_id,))
        result = cursor.fetchone()
        if result is not None:
            return pickle.loads(base64.b64decode(result[0]))
        return None

    def register_handler(self, chat_id, data):
        cursor = self.connection.cursor()
        cursor.execute(
            "REPLACE INTO next_step (chat_id, data) VALUES (%s, %s)",
            (chat_id, base64.b64encode(pickle.dumps(data)).decode('utf-8')),
        )
        self.connection.commit()

    def delete_handlers(self, chat_id):
        cursor = self.connection.cursor()
        cursor.execute("DELETE FROM next_step WHERE chat_id = %s", (chat_id,))
        self.connection.commit()

    def cleanup(self, timeout):
        pass
```

error:
```
2023-08-20 01:21:04,234 (__init__.py:960 MainThread) ERROR - TeleBot: "Infinity polling exception: attribute name must be string, not 'int'"
2023-08-20 01:21:04,235 (__init__.py:962 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 955, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1118, in __threaded_polling
    raise e
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 1073, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    raise self.exception_info
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\util.py", line 90, in run
    task(*args, **kwargs)
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 652, in __retrieve_updates
    self.process_new_updates(updates)
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 740, in process_new_updates
    self.process_new_messages(new_messages)
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 772, in process_new_messages
    self._notify_next_handlers(new_messages)
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 5523, in _notify_next_handlers
    for handler in handlers:
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\telebot\__init__.py", line 70, in __getitem__
    return getattr(self, item)
           ^^^^^^^^^^^^^^^^^^^
TypeError: attribute name must be string, not 'int'
```

**Comment by Mr-X-2100** [comment]
Please help if anyone knows what the problem is. I have had this problem for a few days and could not find a solution.

**Comment by coder2020official** [comment]
Are you sure you shouldn't inherit from a class from handler_backends file?
Tbh I don't remember steps class concept, only thing I can recommend u is to switch to states

**Comment by Mr-X-2100** [comment]
> Are you sure you shouldn't inherit from a class from handler_backends file? Tbh I don't remember steps class concept, only thing I can recommend u is to switch to states

Can you figure out what class exactly I should inherit from?
I tried the things I guessed but it didn't solve the problem.
