### ISSUE TITLE
Raises Exception While Sending the Photo Successfully

### ISSUE THREAD

**Issue by alienscientist** [eternnoir/pyTelegramBotAPI#2087]
I am working on Windows and using pytelegrambotapi  4.14.0 in python 3.10.0. When I am using send_photo function, it successfully sends the photo but after that raises ApiTelegramException exception in __check_result. So, I could not check whether it is successful or not, and continue to try sending the photo infinitly. The exception log record is here:

main                           :: ERROR    :: 2023-11-29 21:52:46,826 :: A request to the Telegram API was unsuccessful. Error code: 429. Description: Too Many Requests: retry after 23
Traceback (most recent call last):
  File "/app/tg_scheduled_bot.py", line 165, in kitchen_status_report
    bot.send_photo(params.hq["chat_id"], open(image_path, 'rb'), reply_to_message_id=int(params.status_updates["topic_id"]), caption=f"{kitchen_name} kapalı marka-app raporu (son statü değişiklik tarihi):")
  File "/usr/local/lib/python3.12/site-packages/telebot/_init_.py", line 1825, in send_photo
    apihelper.send_photo(
  File "/usr/local/lib/python3.12/site-packages/telebot/apihelper.py", line 494, in send_photo
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telebot/apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telebot/apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 429. Description: Too Many Requests: retry after 23
main                           :: ERROR    :: 2023-11-29 21:53:54,908 :: A request to the Telegram API was unsuccessful. Error code: 429. Description: Too Many Requests: retry after 16
Traceback (most recent call last):
  File "/app/tg_scheduled_bot.py", line 165, in kitchen_status_report
    bot.send_photo(params.hq["chat_id"], open(image_path, 'rb'), reply_to_message_id=int(params.status_updates["topic_id"]), caption=f"{kitchen_name} kapalı marka-app raporu (son statü değişiklik tarihi):")
  File "/usr/local/lib/python3.12/site-packages/telebot/_init_.py", line 1825, in send_photo
    apihelper.send_photo(
  File "/usr/local/lib/python3.12/site-packages/telebot/apihelper.py", line 494, in send_photo
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telebot/apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/telebot/apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 429. Description: Too Many Requests: retry after 16
main                           :: ERROR    :: 2023-11-29 22:00:02,700 :: A request to the Telegram API was unsuccessful. Error code: 429. Description: Too Many Requests: retry after 23

**Comment by Badiboy** [comment]
> A request to the Telegram API was unsuccessful. Error code: 429. Description: Too Many Requests: retry after 23

Telegram retruns error - you got it... What is not clear?...

**Comment by alienscientist** [comment]
It sends the message to the given chat successfully but still raises an exception. In general, exceptions are raised if the given command is not fullfilled successfully.

**Comment by alienscientist** [comment]
> > A request to the Telegram API was unsuccessful. Error code: 429. Description: Too Many Requests: retry after 23
> 
> Telegram retruns error - you got it... What is not clear?...

It sends the message to the given chat successfully but still raises an exception. In general, exceptions are raised if the given command is not fullfilled successfully.

**Comment by Badiboy** [comment]
So? You want ask **us** why **Telegram** do this?

**Comment by alienscientist** [comment]
> So? You want ask **us** why **Telegram** do this?

Is that from Telegram or __check_result function fails?
