### ISSUE TITLE
ApiTelegramException: Wrong port number

### ISSUE THREAD

**Issue by tank-sman** [eternnoir/pyTelegramBotAPI#2133]
I was trying to upload a voice message for my self

```
Traceback (most recent call last):
  File "d:\github-repo\AW-bot\test.py", line 36, in <module>
    bot.send_voice("1124728101",VoicePath)
  File "D:\github-repo\AW-bot\.venv\Lib\site-packages\telebot\__init__.py", line 2341, in send_voice
    apihelper.send_voice(
  File "D:\github-repo\AW-bot\.venv\Lib\site-packages\telebot\apihelper.py", line 792, in send_voice
    return _make_request(token, method_url, params=payload, files=files, method='post')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github-repo\AW-bot\.venv\Lib\site-packages\telebot\apihelper.py", line 164, in _make_request
    json_result = _check_result(method_name, result)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\github-repo\AW-bot\.venv\Lib\site-packages\telebot\apihelper.py", line 191, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: invalid file HTTP URL specified: Wrong port number specified in the URL
```

1. What version of pyTelegramBotAPI are you using?
4.15.2 

2. What OS are you using?
Windows

3. What version of python are you using?
3.11.2

**Comment by tank-sman** [comment]
`2024-01-17 10:22:22,318 (apihelper.py:87 MainThread) DEBUG - TeleBot: "Request: method=post url=https://api.telegram.org/bot6606542786:{TOKEN}/sendVoice params={'chat_id': '1124728101', 'voice': '$home\Desktop\\shaomao.ogg'} files=None"`

Why URL is `api.telegram.org/bot6606542786:{TOKEN}/` ?

**Comment by tank-sman** [comment]
Solved
