### ISSUE TITLE
ChatBoostSource.de_json(obj['source']) KeyError: 'source'

### ISSUE THREAD

**Issue by jcrush2** [eternnoir/pyTelegramBotAPI#2137]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
last
2. What OS are you using?
debian
3. What version of python are you using?
4. 3.7

2024-01-21 14:08:46,971 (__init__.py:1021 MainThread) ERROR - TeleBot: "Infinity polling exception: 'source'"
2024-01-21 14:08:46,972 (__init__.py:1023 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 1018, in infinity_polling
    *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 1105, in polling
    logger_level=logger_level, allowed_updates=allowed_updates)
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 1179, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 1140, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/usr/local/lib/python3.7/dist-packages/telebot/util.py", line 110, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.7/dist-packages/telebot/util.py", line 92, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 663, in __retrieve_updates
    timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 636, in get_updates
    return [types.Update.de_json(ju) for ju in json_updates]
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 636, in <listcomp>
    return [types.Update.de_json(ju) for ju in json_updates]
  File "/usr/local/lib/python3.7/dist-packages/telebot/types.py", line 207, in de_json
    chat_boost = ChatBoost.de_json(obj.get('chat_boost'))
  File "/usr/local/lib/python3.7/dist-packages/telebot/types.py", line 9152, in de_json
    obj['source'] = ChatBoostSource.de_json(obj['source'])
KeyError: 'source'
"
2024-01-21 14:08:50,017 (__init__.py:1021 MainThread) ERROR - TeleBot: "Infinity polling exception: 'source'"
2024-01-21 14:08:50,017 (__init__.py:1023 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 1018, in infinity_polling
    *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 1105, in polling
    logger_level=logger_level, allowed_updates=allowed_updates)
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 1179, in __threaded_polling
    raise e
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 1140, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/usr/local/lib/python3.7/dist-packages/telebot/util.py", line 110, in raise_exceptions
    raise self.exception_info
  File "/usr/local/lib/python3.7/dist-packages/telebot/util.py", line 92, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 663, in __retrieve_updates
    timeout=timeout, long_polling_timeout=long_polling_timeout)
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 636, in get_updates
    return [types.Update.de_json(ju) for ju in json_updates]
  File "/usr/local/lib/python3.7/dist-packages/telebot/__init__.py", line 636, in <listcomp>
    return [types.Update.de_json(ju) for ju in json_updates]
  File "/usr/local/lib/python3.7/dist-packages/telebot/types.py", line 207, in de_json
    chat_boost = ChatBoost.de_json(obj.get('chat_boost'))
  File "/usr/local/lib/python3.7/dist-packages/telebot/types.py", line 9152, in de_json
    obj['source'] = ChatBoostSource.de_json(obj['source'])
KeyError: 'source'

**Comment by coder2020official** [comment]
@badiboy can you take a look

**Comment by coder2020official** [comment]
This could have happened because we are using wrong class:
https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/types.py#L207

**Comment by coder2020official** [comment]
It supposed to be chatboostupdated

**Comment by jcrush2** [comment]
downgrade pyTelegramBotAPI/@4.14.1 to and it worked

**Comment by Badiboy** [comment]
@coder2020official 

![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/5613421/5ee949e3-0e1a-416a-97dc-4ae641c86283)
https://core.telegram.org/bots/api#chatboost

Everything in code is correct. Looks like API bug.

**Comment by Badiboy** [comment]
I propose to make it optional to prevent errors.

**Comment by Badiboy** [comment]
PS. Parsing ChatBoostSource types is incorrect (I'll fix), but it's not the subject of the error.

**Comment by coder2020official** [comment]
I don't think this is an API error. But just in case, I will ask levlam about it, and will try to test on how boosts work

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/2138

**Comment by Badiboy** [comment]
@coder2020official So?

**Comment by XuliGan4eg2006** [comment]
getting same error, any fixes?

**Comment by Badiboy** [comment]
Fix released. You can update library.
