### ISSUE TITLE
My bot cant start:  2024-02-08 16:52:44,121 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): 'type'"

### ISSUE THREAD

**Issue by Sonys9** [eternnoir/pyTelegramBotAPI#2159]
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/137277008/fa0c053a-790a-4aac-a7e6-8f2f659ba91b)

2024-02-08 16:52:44,121 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): 'type'"
2024-02-08 16:52:44,180 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): 'type'"
2024-02-08 16:52:44,232 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): 'type'"
2024-02-08 16:52:44,307 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): 'type'"
2024-02-08 16:52:44,363 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): 'type'"
2024-02-08 16:52:44,423 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): 'type'"
2024-02-08 16:52:44,475 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): 'type'"
2024-02-08 16:52:44,530 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): 'type'"

**Comment by Sonys9** [comment]
i tested on host(linux) and on my pc(windows)

**Comment by Sonys9** [comment]
new bots works for 2-3 days and stops

**Comment by Badiboy** [comment]
> My bot cant start

or

> new bots works for 2-3 days and stops

?

**Comment by Badiboy** [comment]
pyTelegramBotAPI version?

**Comment by Sonys9** [comment]
> pyTelegramBotAPI version?

![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/137277008/68f608ce-bb5b-4bcf-9749-b74edf074ca7)

**Comment by Sonys9** [comment]
Newly created bots work for a couple of days, but for some reason they die

> > My bot cant start
> 
> or
> 
> > new bots works for 2-3 days and stops
> 
> ?

i sorry i mean Newly created bots work for a couple of days, but for some reason they die  (google-translator)

**Comment by Sonys9** [comment]
I've updated the module, but I'm getting another error
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/137277008/dcd9c25e-5b01-42c0-9a4f-0f6afe2e9829)
: "Unhandled exception (full traceback for debug level): object.__init__() takes exactly one argument (the instance to initialize)"
2024-02-08 17:29:14,796 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): object.__init__() takes exactly one argument (the instance to initialize)"
2024-02-08 17:29:14,841 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): object.__init__() takes exactly one argument (the instance to initialize)"
2024-02-08 17:29:14,887 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): obj

**Comment by Badiboy** [comment]
Set logger.level = DEBUG and check traceback.

**Comment by Sonys9** [comment]
![image](https://github.com/eternnoir/pyTelegramBotAPI/assets/137277008/72041e3e-c366-4efe-a46b-273342fa1429)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.telegram.org:443
DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "GET /bot6750424697:AAFBJaULW08E7m9T3Lu4AizybWE0d_ZV6Ic/getMe HTTP/1.1" 200 231
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.telegram.org:443
DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "GET /bot6750424697:AAFBJaULW08E7m9T3Lu4AizybWE0d_ZV6Ic/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 4572
2024-02-08 17:34:31,840 (__init__.py:1021 MainThread) ERROR - TeleBot: "Infinity polling exception: object.__init__() takes exactly one argument (the instance to initialize)"
ERROR:TeleBot:Infinity polling exception: object.__init__() takes exactly one argument (the instance to initialize)
2024-02-08 17:34:31,843 (__init__.py:1023 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1016, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1104, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,        
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1179, in __threaded_polling
    raise e
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1140, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Program Files\Python310\lib\site-packages\telebot\util.py", line 110, in raise_exceptions
    raise self.exception_info
  File "C:\Program Files\Python310\lib\site-packages\telebot\util.py", line 92, in run
    task(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 661, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 636, in get_updates
    return [types.Update.de_json(ju) for ju in json_updates]
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 636, in <listcomp>
    return [types.Update.de_json(ju) for ju in json_updates]
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 206, in de_json
    removed_chat_boost = ChatBoostRemoved.de_json(obj.get('removed_chat_boost'))
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 8993, in de_json
    obj['source'] = ChatBoostSource.de_json(obj['source'])
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 9025, in de_json
    return ChatBoostSourcePremium.de_json(obj)
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 9056, in de_json
    return cls(user)
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 9059, in __init__
    super().__init__('premium')
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
"
ERROR:TeleBot:Exception traceback:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1016, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1104, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,        
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1179, in __threaded_polling
    raise e
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1140, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Program Files\Python310\lib\site-packages\telebot\util.py", line 110, in raise_exceptions
    raise self.exception_info
  File "C:\Program Files\Python310\lib\site-packages\telebot\util.py", line 92, in run
    task(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 661, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 636, in get_updates
    return [types.Update.de_json(ju) for ju in json_updates]
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 636, in <listcomp>
    return [types.Update.de_json(ju) for ju in json_updates]
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 206, in de_json
    removed_chat_boost = ChatBoostRemoved.de_json(obj.get('removed_chat_boost'))
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 8993, in de_json
    obj['source'] = ChatBoostSource.de_json(obj['source'])
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 9025, in de_json
    return ChatBoostSourcePremium.de_json(obj)
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 9056, in de_json
    return cls(user)
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 9059, in __init__
    super().__init__('premium')
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.telegram.org:443
DEBUG:urllib3.connectionpool:https://api.telegram.org:443 "GET /bot6750424697:AAFBJaULW08E7m9T3Lu4AizybWE0d_ZV6Ic/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 4572
2024-02-08 17:34:35,004 (__init__.py:1021 MainThread) ERROR - TeleBot: "Infinity polling exception: object.__init__() takes exactly one argument (the instance to initialize)"
ERROR:TeleBot:Infinity polling exception: object.__init__() takes exactly one argument (the instance to initialize)
2024-02-08 17:34:35,007 (__init__.py:1023 MainThread) ERROR - TeleBot: "Exception traceback:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1016, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1104, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,        
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1179, in __threaded_polling
    raise e
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1140, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Program Files\Python310\lib\site-packages\telebot\util.py", line 110, in raise_exceptions
    raise self.exception_info
  File "C:\Program Files\Python310\lib\site-packages\telebot\util.py", line 92, in run
    task(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 661, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 636, in get_updates
    return [types.Update.de_json(ju) for ju in json_updates]
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 636, in <listcomp>
    return [types.Update.de_json(ju) for ju in json_updates]
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 206, in de_json
    removed_chat_boost = ChatBoostRemoved.de_json(obj.get('removed_chat_boost'))
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 8993, in de_json
    obj['source'] = ChatBoostSource.de_json(obj['source'])
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 9025, in de_json
    return ChatBoostSourcePremium.de_json(obj)
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 9056, in de_json
    return cls(user)
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 9059, in __init__
    super().__init__('premium')
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
"
ERROR:TeleBot:Exception traceback:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1016, in infinity_polling
    self.polling(non_stop=True, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1104, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,        
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1179, in __threaded_polling
    raise e
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 1140, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Program Files\Python310\lib\site-packages\telebot\util.py", line 110, in raise_exceptions
    raise self.exception_info
  File "C:\Program Files\Python310\lib\site-packages\telebot\util.py", line 92, in run
    task(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 661, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1),
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 636, in get_updates
    return [types.Update.de_json(ju) for ju in json_updates]
  File "C:\Program Files\Python310\lib\site-packages\telebot\__init__.py", line 636, in <listcomp>
    return [types.Update.de_json(ju) for ju in json_updates]
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 206, in de_json
    removed_chat_boost = ChatBoostRemoved.de_json(obj.get('removed_chat_boost'))
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 8993, in de_json
    obj['source'] = ChatBoostSource.de_json(obj['source'])
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 9025, in de_json
    return ChatBoostSourcePremium.de_json(obj)
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 9056, in de_json
    return cls(user)
  File "C:\Program Files\Python310\lib\site-packages\telebot\types.py", line 9059, in __init__
    super().__init__('premium')
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

**Comment by Badiboy** [comment]
Thanks. See the issue. This class is unhappy...

**Comment by Badiboy** [comment]
Try this branch pls.
https://github.com/eternnoir/pyTelegramBotAPI/pull/2162

**Comment by Badiboy** [comment]
Try to install and use current GIT version:
`pip install -U git+https://github.com/eternnoir/pyTelegramBotAPI.git`
If will not be updated - run:
`pip uninstall --yes pyTelegramBotAPI`
before.

**Comment by Sonys9** [comment]
thank you!!!
