### ISSUE TITLE
ChatBoostSourceGiveaway de_json raises KeyError when the bot starts

### ISSUE THREAD

**Issue by KimmyXYC** [eternnoir/pyTelegramBotAPI#2173]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
4.15.5
2. What OS are you using?
Ubuntu 20.04.5 LTS x86_64
3. What version of python are you using?
3.8.10

```
2024-02-17 05:17:29,390 (async_telebot.py:455 MainThread) ERROR - TeleBot: "Unhandled exception (full traceback for debug level): 'user'"
2024-02-17 05:17:29,390 (async_telebot.py:456 MainThread) DEBUG - TeleBot: "Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telebot/async_telebot.py", line 421, in _process_polling
    updates = await self.get_updates(offset=self.offset, allowed_updates=allowed_updates, timeout=timeout, request_timeout=request_timeout)
  File "/usr/local/lib/python3.8/dist-packages/telebot/async_telebot.py", line 223, in get_updates
    return [types.Update.de_json(ju) for ju in json_updates]
  File "/usr/local/lib/python3.8/dist-packages/telebot/async_telebot.py", line 223, in <listcomp>
    return [types.Update.de_json(ju) for ju in json_updates]
  File "/usr/local/lib/python3.8/dist-packages/telebot/types.py", line 207, in de_json
    chat_boost = ChatBoostUpdated.de_json(obj.get('chat_boost'))
  File "/usr/local/lib/python3.8/dist-packages/telebot/types.py", line 8960, in
de_json
    obj['boost'] = ChatBoost.de_json(obj['boost'])
  File "/usr/local/lib/python3.8/dist-packages/telebot/types.py", line 9174, in
de_json
    obj['source'] = ChatBoostSource.de_json(source) if source else None
  File "/usr/local/lib/python3.8/dist-packages/telebot/types.py", line 9032, in
de_json
    return ChatBoostSourceGiveaway.de_json(obj)
  File "/usr/local/lib/python3.8/dist-packages/telebot/types.py", line 9124, in
de_json
    obj['user'] = User.de_json(obj['user'])
KeyError: 'user'
```

**Comment by Badiboy** [comment]
ChatBoostSource is the most unhappy sh*t in the last 2 years of updates. :)

**Comment by coder2020official** [comment]
oh my god. is the code broken again?

**Comment by Badiboy** [comment]
I fixed.
