### ISSUE TITLE
TypeError: StickerSet.__init__() missing 2 required positional arguments: 'is_animated' and 'is_video'

### ISSUE THREAD

**Issue by Kuchizu** [eternnoir/pyTelegramBotAPI#2212]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

Name: pyTelegramBotAPI
Version: 4.16.1
Summary: Python Telegram bot api.
Home-page:
Author:
Author-email: eternnoir <eternnoir@gmail.com>
License: GPL2
Location: /root/FaceSwappers/ManSwapper/venv/lib/python3.10/site-packages
Requires: requests
Required-by:

2. What OS are you using?

Ubuntu 22.04

3. What version of python are you using?

Python 3.10.12

Problem:

bot.get_sticker_set(sticker_set_name)

Traceback (most recent call last):
  File "/root/FaceSwappers/BrotherSwapper/swapper.py", line 67, in process_queue
    self.create_sticker_pack(message, face)
  File "/root/FaceSwappers/BrotherSwapper/logger.py", line 52, in wrapper
    result = method(*args, **kwargs)
  File "/root/FaceSwappers/BrotherSwapper/swapper.py", line 132, in create_sticker_pack
    self.send_sticker_set(message.from_user.id, sticker_set_name)
  File "/root/FaceSwappers/BrotherSwapper/swapper.py", line 191, in send_sticker_set
    pack = self.bot.get_sticker_set(sticker_set_name)
  File "/root/FaceSwappers/ManSwapper/venv/lib/python3.10/site-packages/telebot/__init__.py", line 5457, in get_sticker_set
    return types.StickerSet.de_json(
  File "/root/FaceSwappers/ManSwapper/venv/lib/python3.10/site-packages/telebot/types.py", line 6309, in de_json
    return cls(**obj)
TypeError: StickerSet.__init__() missing 2 required positional arguments: 'is_animated' and 'is_video'

**Comment by coder2020official** [comment]
We have to do something 😢
Yes, we are aware of the issue. It was caused by bot API update

**Comment by Kuchizu** [comment]
https://github.com/python-telegram-bot/python-telegram-bot/issues/4181#issuecomment-2029046687

There's a temporary solution of this from another library, does TeleBot have some similar method to do raw api requests?

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/2217
