### ISSUE TITLE
409 Conflict

### ISSUE THREAD

**Issue by Kondra007** [eternnoir/pyTelegramBotAPI#25]
I've been getting 409 API Error 5 times today in line
```python
Traceback (most recent call last):
  File "meduzabot.py", line 79, in <module>
    tb.get_update()  # cache exist message
  File "/usr/local/lib/python3.4/dist-packages/telebot/__init__.py", line 50, in get_update
    updates = apihelper.get_updates(self.token, offset=(self.last_update_id + 1), timeout=20)
  File "/usr/local/lib/python3.4/dist-packages/telebot/apihelper.py", line 68, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.4/dist-packages/telebot/apihelper.py", line 22, in _make_request
    raise ApiException(method_name, result)
telebot.apihelper.ApiException: getUpdates failed. Returned result: <Response [409]>
```

Is it something wrong with my code or these are Telegram servers' faults?

**Comment by eternnoir** [comment]
I never confront this problem. I'll test tomorrow.

**Comment by GabrielRF** [comment]
''' 
Start
getUpdates failed. Returned result: <Response [409]>
Traceback (most recent call last):
  File "rastreiobot.py", line 113, in <module>
    tb.get_update()  # cache exist message
  File "/home/gabriel/pyTelegramBotAPI/telebot/__init__.py", line 106, in get_update
    updates = apihelper.get_updates(self.token, offset=(self.last_update_id + 1), timeout=20)
  File "/home/gabriel/pyTelegramBotAPI/telebot/apihelper.py", line 68, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/gabriel/pyTelegramBotAPI/telebot/apihelper.py", line 22, in _make_request
    raise ApiException(method_name, result)
telebot.apihelper.ApiException: getUpdates failed. Returned result: <Response [409]>
''' 
I'm getting the same error now.

**Comment by eternnoir** [comment]
In different places with the same API TOKEN?

**Comment by Kondra007** [comment]
For me the problem is gone. Only 502 Error and `('Connection aborted.', gaierror(-5, 'No address associated with hostname'))` sometimes

**Comment by mahrens917** [comment]
I get a 409 error as well - right on start up and only half the time - not sure what is it causing it other than "Conflict: terminated by other long poll or webhook"

**Comment by mahrens917** [comment]
The comments here https://github.com/lukefx/hubot-telegram/issues/9 may help resolve this issue.

**Comment by mahrens917** [comment]
I discovered my issue - I was running another instance of my program and didn't know it.  Stopping that instance resolved the issue.
