### ISSUE TITLE
Error: HTTPSConnectionPool

### ISSUE THREAD

**Issue by SyrianProgrammer** [eternnoir/pyTelegramBotAPI#264]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI==2.2.3

2. What OS are you using?
Linux Mint 18 Sarah 64-bit

3. What version of python are you using?
Python 3.5.2

py==1.4.29
pytest==3.0.2
requests==2.7.0
six==1.9.0
wheel==0.24.0

**I do not know why this error shows:**
`
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 374, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/packages/six.py", line 310, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 376, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 304, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/home/conan/Documents/PyCharm2016.3/PycharmProjects/SyrianProgrammerBot/main.py", line 798, in <module>
    MyBot.polling()
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 196, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 219, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 659, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 126, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 96, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 145, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 34, in _make_request
    result = requests.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)
`

**Comment by eternnoir** [comment]
This seems to be the problem of requests. https://github.com/kennethreitz/requests/issues/1915

Try `pip install --upgrade requests`.

**Comment by SyrianProgrammer** [comment]
this code for closed error:

while True:  # Don't let the main Thread end.
    try:

        # Use none_stop flag let polling will not stop when get new message occur error.
        MyBot.polling(none_stop=True)
    except Exception as err:
        logging.error(err)
        sleep(5)
