### ISSUE TITLE
AttributeError: 'module' object has no attribute 'logger'

### ISSUE THREAD

**Issue by bekerov** [eternnoir/pyTelegramBotAPI#282]
Please answer these questions before submitting your issue. Thanks!

```
Traceback (most recent call last):
  File "some/path/app.py", line 13, in <module>
    logger = telebot.logger
AttributeError: 'module' object has no attribute 'logger'
```

On line 13.
![image](https://cloud.githubusercontent.com/assets/2405629/22366137/21c0a7e0-e48c-11e6-922d-075c2f874dd8.png)

In sourecode i cant find `logger`

1. What version of pyTelegramBotAPI are you using?
telebot==0.0.3

2. What OS are you using?
Windows 7 x64

3. What version of python are you using?
Python34

**Comment by eternnoir** [comment]
Can you paste more code about how to import telebot?

**Comment by monajalal** [comment]
I get the same error:
```
mona@pascal:~/computer_vision/instagram/insta$ scrapy crawl instagramspider
2017-03-02 20:15:28-0600 [scrapy] INFO: Scrapy 0.14.4 started (bot: insta)
2017-03-02 20:15:28-0600 [scrapy] DEBUG: Enabled extensions: LogStats, TelnetConsole, CloseSpider, WebService, CoreStats, MemoryUsage, SpiderState
/usr/lib/python2.7/dist-packages/scrapy/__init__.pyc
2017-03-02 20:15:30-0600 [scrapy] DEBUG: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, RedirectMiddleware, CookiesMiddleware, HttpCompressionMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-03-02 20:15:30-0600 [scrapy] DEBUG: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-03-02 20:15:30-0600 [scrapy] DEBUG: Enabled item pipelines: 
2017-03-02 20:15:30-0600 [instagramspider] INFO: Spider opened
2017-03-02 20:15:30-0600 [instagramspider] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-03-02 20:15:30-0600 [scrapy] DEBUG: Telnet console listening on 0.0.0.0:6024
2017-03-02 20:15:30-0600 [scrapy] DEBUG: Web service listening on 0.0.0.0:6081
2017-03-02 20:15:30-0600 [instagramspider] DEBUG: Crawled (200) <GET https://www.instagram.com/buzzfeed/?__a=1> (referer: None)
2017-03-02 20:15:30-0600 [instagramspider] ERROR: Spider error processing <GET https://www.instagram.com/buzzfeed/?__a=1>
	Traceback (most recent call last):
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 1201, in mainLoop
	    self.runUntilCurrent()
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/base.py", line 824, in runUntilCurrent
	    call.func(*call.args, **call.kw)
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 380, in callback
	    self._startRunCallbacks(result)
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 488, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/usr/local/lib/python2.7/dist-packages/Twisted-13.1.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 575, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/mona/computer_vision/instagram/insta/insta/spiders/spider.py", line 98, in parse
	    self.logger.info('%s doesnt exist', response.url)
	exceptions.AttributeError: 'InstagramSpider' object has no attribute 'logger'
	
2017-03-02 20:15:30-0600 [instagramspider] INFO: Closing spider (finished)
2017-03-02 20:15:30-0600 [instagramspider] INFO: Dumping spider stats:
	{'downloader/request_bytes': 213,
	 'downloader/request_count': 1,
	 'downloader/request_method_count/GET': 1,
	 'downloader/response_bytes': 2807,
	 'downloader/response_count': 1,
	 'downloader/response_status_count/200': 1,
	 'finish_reason': 'finished',
	 'finish_time': datetime.datetime(2017, 3, 3, 2, 15, 30, 463881),
	 'scheduler/memory_enqueued': 1,
	 'spider_exceptions/AttributeError': 1,
	 'start_time': datetime.datetime(2017, 3, 3, 2, 15, 30, 110402)}
2017-03-02 20:15:30-0600 [instagramspider] INFO: Spider closed (finished)
2017-03-02 20:15:30-0600 [scrapy] INFO: Dumping global stats:
	{'memusage/max': 127741952, 'memusage/startup': 127741952}
```
