### ISSUE TITLE
Herroku error

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [eternnoir/pyTelegramBotAPI#329]
Hello faced with the problem to use the bot on the server herroku

1.pyTelegramBotAPI==2.3.2

2. herroku server

3. python verson 3.5.0

code

 
`
import os
import telebot
import cherrypy
import time

token = "token"

WEBHOOK_HOST = '0.0.0.0'
WEBHOOK_PORT = int(os.environ.get('PORT', 5000))
WEBHOOK_LISTEN = '0.0.0.0'

WEBHOOK_SSL_CERT = './webhook_cert.pem'
WEBHOOK_SSL_PRIV = './webhook_pkey.pem'

WEBHOOK_URL_BASE = "https://%s:%s" % (WEBHOOK_HOST, WEBHOOK_PORT)
WEBHOOK_URL_PATH = "/%s/" % (token)

bot = telebot.TeleBot(token)

class WebhookServer(object):
    @cherrypy.expose
    def index(self):
        if 'content-length' in cherrypy.request.headers and \
                        'content-type' in cherrypy.request.headers and \
                        cherrypy.request.headers['content-type'] == 'application/json':
            length = int(cherrypy.request.headers['content-length'])
            json_string = cherrypy.request.body.read(length).decode("utf-8")
            update = telebot.types.Update.de_json(json_string)

            bot.process_new_updates([update])
            return ''
        else:
            raise cherrypy.HTTPError(403)

@bot.message_handler(func=lambda message: True, content_types=['text'])
def echo_message(message):
    bot.reply_to(message, message.text)

bot.remove_webhook()

time.sleep(5)

bot.set_webhook(url=WEBHOOK_URL_BASE + WEBHOOK_URL_PATH,certificate=open(WEBHOOK_SSL_CERT, 'r'))

cherrypy.config.update({
    'server.socket_host': '0.0.0.0',
    'server.socket_port': int(os.environ.get('PORT', 5000)),
    'server.ssl_module': 'builtin',
    'server.ssl_certificate': WEBHOOK_SSL_CERT,
    'server.ssl_private_key': WEBHOOK_SSL_PRIV
})

cherrypy.quickstart(WebhookServer(), WEBHOOK_URL_PATH, {'/bot': {}})`

error
`2017-05-13T20:17:47.401966+00:00 heroku[web.1]: Starting process with command `python3 main.py`

2017-05-13T20:17:55.269877+00:00 heroku[web.1]: Process exited with status 1

2017-05-13T20:17:55.280209+00:00 heroku[web.1]: State changed from starting to crashed

2017-05-13T20:17:55.145523+00:00 app[web.1]: Traceback (most recent call last):

2017-05-13T20:17:55.145546+00:00 app[web.1]:   File "main.py", line 47, in <module>

2017-05-13T20:17:55.145650+00:00 app[web.1]:     bot.set_webhook(url=WEBHOOK_URL_BASE + WEBHOOK_URL_PATH,certificate=open(WEBHOOK_SSL_CERT, 'r'))

2017-05-13T20:17:55.145651+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/telebot/__init__.py", line 81, in set_webhook

2017-05-13T20:17:55.145760+00:00 app[web.1]:     return apihelper.set_webhook(self.token, url, certificate, max_connections, allowed_updates)

2017-05-13T20:17:55.145761+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/telebot/apihelper.py", line 138, in set_webhook

2017-05-13T20:17:55.145890+00:00 app[web.1]:     return _make_request(token, method_url, params=payload, files=files)

2017-05-13T20:17:55.145890+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/telebot/apihelper.py", line 44, in _make_request

2017-05-13T20:17:55.145974+00:00 app[web.1]:     return _check_result(method_name, result)['result']

2017-05-13T20:17:55.145974+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/telebot/apihelper.py", line 63, in _check_result

2017-05-13T20:17:55.146071+00:00 app[web.1]:     raise ApiException(msg, method_name, result)

2017-05-13T20:17:55.146087+00:00 app[web.1]: telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:

2017-05-13T20:17:55.146089+00:00 app[web.1]: [b'{"ok":false,"error_code":400,"description":"Bad Request: bad webhook: Webhook can be set up only on ports 80, 88, 443 or 8443"}']`

I understand that the telegram server require a different port
but herroku open only 1 of 5000

**Comment by Kylmakalle** [comment]
It's not telebot problem

**Comment by eternnoir** [comment]
Telegram bot api only accept webhook use 80, 88, 443, 8443. You cannot set other ports.
