### ISSUE TITLE
Error after a while

### ISSUE THREAD

**Issue by soermejo** [eternnoir/pyTelegramBotAPI#339]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?  last

2. What OS are you using? ubuntu

3. What version of python are you using? 

``` 
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/namoso/findstranger/new1/control.py", line 84, in alreadyrun
    bot.send_message(chat_id, gen(lenguage, "matched"))
  File "/home/namoso/.local/lib/python2.7/site-packages/telebot/__init__.py", line 397, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/home/namoso/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 123, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/home/namoso/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 42, in _make_request
    result = req_session.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/home/namoso/.local/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/namoso/.local/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/namoso/.local/lib/python2.7/site-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))

Traceback (most recent call last):
  File "main.py", line 179, in <module>
    bot.polling(none_stop=True)
  File "/home/namoso/.local/lib/python2.7/site-packages/telebot/__init__.py", line 222, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/home/namoso/.local/lib/python2.7/site-packages/telebot/__init__.py", line 245, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/home/namoso/.local/lib/python2.7/site-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/home/namoso/.local/lib/python2.7/site-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/home/namoso/.local/lib/python2.7/site-packages/telebot/__init__.py", line 136, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/namoso/.local/lib/python2.7/site-packages/telebot/__init__.py", line 106, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/namoso/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 163, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/namoso/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 42, in _make_request
    result = req_session.request(method, request_url, params=params, files=files, timeout=(connect_timeout, read_timeout))
  File "/home/namoso/.local/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/namoso/.local/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/namoso/.local/lib/python2.7/site-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error("(104, 'ECONNRESET')",))

```

**Comment by eternnoir** [comment]
This is network connection error. Make sure connection is no issue between your bot and telegram bot api server.

**Comment by seby2000** [comment]
it is running on a vps, it is the last cause

**Comment by Stihotvor** [comment]
Same problem. Bot is working on Google Compute Engine. All network access is granted.

**Comment by alexshavelev44** [comment]
same problem

**Comment by vlnerable** [comment]
Same problem as you

**Comment by kosmokato** [comment]
Same problem. And that's sad, because Bots are awesome.
Mine, at least.
