### ISSUE TITLE
Error In pyTelegramBotAPI ???

### ISSUE THREAD

**Issue by AliBahaari** [eternnoir/pyTelegramBotAPI#384]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? Latest

2. What OS are you using? Ubuntu

3. What version of python are you using? 3

Hello, I want to run my Telegram Bot on server, But this error shows me a message :
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/util.py", line 144, in _validate_timeout
    float(value)
TypeError: float() argument must be a string or a number, not 'tuple'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Bot.py", line 69, in <module>
    bot.polling()
  File "/usr/local/lib/python3.4/dist-packages/telebot/__init__.py", line 263, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/usr/local/lib/python3.4/dist-packages/telebot/__init__.py", line 286, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/usr/local/lib/python3.4/dist-packages/telebot/util.py", line 73, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/usr/lib/python3/dist-packages/six.py", line 536, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/telebot/util.py", line 54, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python3.4/dist-packages/telebot/apihelper.py", line 172, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.4/dist-packages/telebot/apihelper.py", line 51, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 316, in send
    timeout = TimeoutSauce(connect=timeout, read=timeout)
  File "/usr/lib/python3/dist-packages/urllib3/util.py", line 116, in __init__
    self._connect = self._validate_timeout(connect, 'connect')
  File "/usr/lib/python3/dist-packages/urllib3/util.py", line 147, in _validate_timeout
    "int or float." % (name, value))
ValueError: Timeout value connect was (3.5, 30), but it must be an int or float.
```
I don't know what should I do ..., Can please help me ?

**Comment by AliBahaari** [comment]
sudo pip3 install --upgrade pyTelegramBotAPI
This Works ...
