### ISSUE TITLE
Random crash on startup

### ISSUE THREAD

**Issue by maxkrivich** [eternnoir/pyTelegramBotAPI#390]
1. What version of pyTelegramBotAPI are you using?
3.2.0
2. What OS are you using?
Ubuntu 16.04 LTS
3. What version of python are you using?
3.5.2

I'm deploying my bot on Heroku. This happens after relaunching dynos and send command in the first time. I think the problem in decorator and steps know why bot crashes, but after few messages, that's stop.

```py
@bot.message_handler(commands=['phone_add'])
def phone_add(message):
	markup = telebot.types.ForceReply(selective=False)
	msg = bot.send_message(message.chat.id, messages.ADD_PHONE_MESSAGE, parse_mode="HTML", reply_markup=markup)
	steps[message.chat.id] = 1

@bot.message_handler(func=lambda message: message.reply_to_message is not None and steps[message.chat.id] == 1, content_types=['text'])
def phone_add_handler(message):
	phone_number = message.text.strip()
	if utils.validate_mobile(phone_number):
		phone_number = phone_number.replace('+38', '')
		try:
			dbworker.DataBaseWorker.add_phone(message.from_user.id, phone_number)
			bot.send_message(message.chat.id, messages.ADD_PHONE_SUCCESS_MESSAGE, parse_mode="HTML")
		except Exception as e:
			logging.exception(e)
	else:
		bot.send_message(message.chat.id, messages.ADD_PHONE_ERROR_MESSAGE, parse_mode="HTML")
	steps[message.chat.id] == -1
``` 

``` sh
Exception on /8fa204f72e6fc2d1b7d0aafa92d26a [POST]
2017-08-22T07:27:40.010494+00:00 app[web.1]: Traceback (most recent call last):
2017-08-22T07:27:40.010495+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
2017-08-22T07:27:40.010496+00:00 app[web.1]:     response = self.full_dispatch_request()
2017-08-22T07:27:40.010497+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
2017-08-22T07:27:40.010497+00:00 app[web.1]:     rv = self.handle_user_exception(e)
2017-08-22T07:27:40.010498+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
2017-08-22T07:27:40.010498+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
2017-08-22T07:27:40.010499+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
2017-08-22T07:27:40.010499+00:00 app[web.1]:     raise value
2017-08-22T07:27:40.010500+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
2017-08-22T07:27:40.010500+00:00 app[web.1]:     rv = self.dispatch_request()
2017-08-22T07:27:40.010501+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
2017-08-22T07:27:40.010501+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
2017-08-22T07:27:40.010502+00:00 app[web.1]:   File "/app/app/views.py", line 45, in getMessage
2017-08-22T07:27:40.010503+00:00 app[web.1]:     bot.process_new_updates([telebot.types.Update.de_json(request.stream.read().decode("utf-8"))])
2017-08-22T07:27:40.010503+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/telebot/__init__.py", line 197, in process_new_updates
2017-08-22T07:27:40.010509+00:00 app[web.1]:     self.process_new_messages(new_messages)
2017-08-22T07:27:40.010509+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/telebot/__init__.py", line 218, in process_new_messages
2017-08-22T07:27:40.010510+00:00 app[web.1]:     self._notify_command_handlers(self.message_handlers, new_messages)
2017-08-22T07:27:40.010511+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/telebot/__init__.py", line 1198, in _notify_command_handlers
2017-08-22T07:27:40.010511+00:00 app[web.1]:     if self._test_message_handler(message_handler, message):
2017-08-22T07:27:40.010512+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/telebot/__init__.py", line 1180, in _test_message_handler
2017-08-22T07:27:40.010512+00:00 app[web.1]:     if not self._test_filter(filter, filter_value, message):
2017-08-22T07:27:40.010513+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/telebot/__init__.py", line 1193, in _test_filter
2017-08-22T07:27:40.010513+00:00 app[web.1]:     return test_cases.get(filter, lambda msg: False)(message)
2017-08-22T07:27:40.010514+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.5/site-packages/telebot/__init__.py", line 1190, in <lambda>
2017-08-22T07:27:40.010514+00:00 app[web.1]:     'func': lambda msg: filter_value(msg)
2017-08-22T07:27:40.010515+00:00 app[web.1]:   File "/app/app/views.py", line 104, in <lambda>
2017-08-22T07:27:40.010515+00:00 app[web.1]:     @bot.message_handler(func=lambda message: message.reply_to_message is not None and steps[message.chat.id] == 1, content_types=['text'])
2017-08-22T07:27:40.010518+00:00 app[web.1]: KeyError: 296266
```

**Comment by mostafaqanbaryan** [comment]
Change your lambda to this and test again:
`@bot.message_handler(func=lambda message: message.reply_to_message is not None and message.chat.id in steps and steps[message.chat.id] == 1, content_types=['text'])`
