### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by painstyle01** [eternnoir/pyTelegramBotAPI#399]
1. What version of pyTelegramBotAPI are you using? 
Latest

2. What OS are you using?
KDE Neon

3. What version of python are you using?
3

Feedback-bot is crashing after 30 mins of work.

Logs:
`2017-10-10 19:56:38,850 (util.py:64 WorkerThread2) ERROR - TeleBot: "ConnectionError occurred, args=(ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')),)
Traceback (most recent call last):
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/painstyle01/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "main.py", line 49, in ping
    bot.send_message(chatId, 'Да работаю я бл***')
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 439, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 135, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
"
Traceback (most recent call last):
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/painstyle01/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/painstyle01/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 64, in <module>
    bot.polling(none_stop=True)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 264, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 288, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 107, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/usr/local/lib/python3.5/dist-packages/six.py", line 693, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "main.py", line 49, in ping
    bot.send_message(chatId, 'Да работаю я бл***')
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 439, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 135, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.5/dist-packages/telebot/apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/painstyle01/.local/lib/python3.5/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

Code:
`import telebot
import constants
from telebot import types

bot = telebot.TeleBot(constants.token)
markup = types.ReplyKeyboardMarkup(True)
markup.row('/request')
markup.row('/feedback')
markup2 = types.ReplyKeyboardMarkup(True)
markup2.row('/restart')

@bot.message_handler(commands=['start'])
def keyboard(message):
    chatId = message.chat.id
    if chatId == -1001124048974:
        bot.send_message(chatId,'Вам делать нечего? ЗА РАБОТУ!')
    bot.send_message(chatId, 'Привет. Выбери что ты хочешь сделать из пункта ниже:',  reply_markup=markup)

@bot.message_handler(commands=['request'])
def request(message):
    chatId = message.chat.id
    if chatId == -1001124048974:
        bot.send_message(chatId,'Вам делать нечего? ЗА РАБОТУ!')
    bot.send_message(chatId, 'Есть интересная новость? Расскажи её нам! (/send "Текст новости".'
                             'Если хочешь вернуться в меню нажми "/restart"', reply_markup=markup2)

@bot.message_handler(commands=['feedback'])
def request(message):
    chatId = message.chat.id
    if chatId == -1001124048974:
        bot.send_message(chatId,'Вам делать нечего? ЗА РАБОТУ!')
    bot.send_message(chatId, 'Жалоба, предложение или идея? Отправь её нам! (/send "Текст обращения").'
                             'Если хочешь вернуться в меню нажми "/restart"', reply_markup=markup2)

@bot.message_handler(commands=['restart'])
def restart(message):
    chatId = message.chat.id
    if chatId == -1001124048974:
        bot.send_message(chatId,'Вам делать нечего? ЗА РАБОТУ!')
    bot.send_message(chatId, 'Отменено.')
    bot.send_message(chatId, 'Привет. Тут ты можешь оставить свой отзыв', reply_markup=markup)

@bot.message_handler(commands=['ping'])
def ping(message):
    chatId = message.chat.id
    bot.send_message(chatId, 'Да работаю я бл***')

@bot.message_handler(commands=['send'])
def send(message):
    username = '@' + str(message.from_user.username)
    if username == '@None':
        username = message.from_user.first_name
    chatId = message.chat.id
    text = message.text
    bot.send_message(chatId, 'Ты отправил в редакцию слова: ' + str(text))
    bot.send_message(chatId, 'Отправлено! Что то ещё?', reply_markup=markup)
    bot.send_message(-1001124048974,'Господа, к нам обращение от ' + str(username))
    bot.send_message(-1001124048974, str(text))

if __name__ == '__main__':
     bot.polling(none_stop=True)`

LAN connection, stable.

**Comment by andreworg** [comment]
Same here. arch linux ARM, pyTelegramBotAPI 3.5.1, virtualenv, same behaviour under both Python 2.7.14 and Python 3.6.4.
