### ISSUE TITLE
Telegram read timeout

### ISSUE THREAD

**Issue by Andermutu** [eternnoir/pyTelegramBotAPI#401]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
Lastest
2. What OS are you using?
Ubuntu
3. What version of python are you using?
2.7.9

Dear Community;

I have a small project with Telegram and this API works fine. But sometimes, I thinks that it is because my internet is unstable I get a error in python while running my script. This is the error:

2017-10-20 18:39:05,960 (util.py:64 PollingThread) ERROR - TeleBot: "ReadTimeout occurred, args=(ReadTimeoutError("HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)",),)
Traceback (most recent call last):
  File "/home/ander/Documentos/Telegram/pyTelegramBotAPI-master/telebot/util.py", line 58, in run
    task(*args, **kwargs)
  File "/home/ander/Documentos/Telegram/pyTelegramBotAPI-master/telebot/__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/ander/Documentos/Telegram/pyTelegramBotAPI-master/telebot/__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/ander/Documentos/Telegram/pyTelegramBotAPI-master/telebot/apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/ander/Documentos/Telegram/pyTelegramBotAPI-master/telebot/apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 433, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)

Has anyone any idea? Any suggestion is welcomed. Thanks in  advance.

**Comment by kotinder** [comment]
hi there, did you solved an issue? i've got same. tried to work it out with exception handler but failed.

**Comment by Andermutu** [comment]
Yes it is solved. Instead of bot.polling() use this:

while True:
        try:
                bot.polling(none_stop=True)
        except Exception as err:
                logging.error(err)
                time.sleep(5)
                print "Internet error!"

**Comment by weblanss** [comment]
same issue

**Comment by sviat9440** [comment]
Try fix #484
