### ISSUE TITLE
TeleBot: "UnicodeEncodeError occurred when sending a non-ASCII file, python 2.7

### ISSUE THREAD

**Issue by BennyThink** [eternnoir/pyTelegramBotAPI#403]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.2.1, the latest version.
2. What OS are you using?
Windows 10 x64 & Ubuntu 16.04 x64
3. What version of python are you using?
Python 2.7

Hi there,
I tried to send a non-ASCII file(a Chinese file name, in my example it's `中文.txt`):
```
@bot.message_handler(commands=['you'])
def bot_test(message):
    doc = open(u'中文.txt', 'rb')
    bot.send_document(message.chat.id, doc)
```
And then exception raised, the full exception  is showed as follows:
```
2017-10-24 10:57:04,361 (util.py:64 WorkerThread1) ERROR - TeleBot: "UnicodeEncodeError occurred, args=('ascii', u'\u4e2d\u6587.txt', 0, 2, 'ordinal not in range(128)')
Traceback (most recent call last):
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\util.py", line 58, in run
    task(*args, **kwargs)
  File "C:/Users/myusername/Documents/ExpressBot/chi_test.py", line 20, in bot_test
    bot.send_document(message.chat.id, doc)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\__init__.py", line 523, in send_document
    disable_notification, timeout, caption=caption))
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\apihelper.py", line 416, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\requests\models.py", line 308, in prepare
    self.prepare_body(data, files, json)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\requests\models.py", line 496, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\requests\models.py", line 162, in _encode_files
    rf.make_multipart(content_type=ft)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\urllib3\fields.py", line 174, in make_multipart
    (('name', self._name), ('filename', self._filename))
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\urllib3\fields.py", line 134, in _render_parts
    parts.append(self._render_part(name, value))
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\urllib3\fields.py", line 114, in _render_part
    return format_header_param(name, value)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\apihelper.py", line 865, in wrapper
    return '{0}={1}'.format(key, val)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
"
Traceback (most recent call last):
  File "C:/Users/myusername/Documents/ExpressBot/chi_test.py", line 23, in <module>
    bot.polling()
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\__init__.py", line 264, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\__init__.py", line 288, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\util.py", line 107, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\util.py", line 58, in run
    task(*args, **kwargs)
  File "C:/Users/myusername/Documents/ExpressBot/chi_test.py", line 20, in bot_test
    bot.send_document(message.chat.id, doc)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\__init__.py", line 523, in send_document
    disable_notification, timeout, caption=caption))
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\apihelper.py", line 416, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\requests\sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\requests\sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\requests\models.py", line 308, in prepare
    self.prepare_body(data, files, json)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\requests\models.py", line 496, in prepare_body
    (body, content_type) = self._encode_files(files, data)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\requests\models.py", line 162, in _encode_files
    rf.make_multipart(content_type=ft)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\urllib3\fields.py", line 174, in make_multipart
    (('name', self._name), ('filename', self._filename))
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\urllib3\fields.py", line 134, in _render_parts
    parts.append(self._render_part(name, value))
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\urllib3\fields.py", line 114, in _render_part
    return format_header_param(name, value)
  File "C:\Users\myusername\Documents\ExpressBot\ENV\lib\site-packages\telebot\apihelper.py", line 865, in wrapper
    return '{0}={1}'.format(key, val)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```

This exception occurs **both in Windows and Ubuntu** as long as I use python 2, however, python 3(3.5, 3.6) works fine for me.
By the way, sending a English filename works fine under Python 2.7

Any suggestions?
Thanks in advance!

**Comment by eternnoir** [comment]
Try to add `# -*- coding: utf-8 -*-` at first line in your .py file.

**Comment by BennyThink** [comment]
Hi there,
thanks for you reply.
But the utf-8 has already been in my first line in my .py file, and it didn't work out either.
@eternnoir
