### ISSUE TITLE
500 Internal

### ISSUE THREAD

**Issue by heyt0ny** [eternnoir/pyTelegramBotAPI#406]
Hi, today I encountered this error a lot of times:

> telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 500 Internal Server Error. Response body:
> <html>
> <head><title>500 Internal Server Error</title></head>
> <body bgcolor="white">
> <center><h1>500 Internal Server Error</h1></center>
> <hr><center>nginx/1.10.0</center>
> </body>
> </html>

 
pyTelegramBotAPI 3.2.1

Till yesterday it was working fine.

**Comment by MasterGroosha** [comment]
Seems like these were problems with Bot API itself. Is everything okay now?

**Comment by heyt0ny** [comment]
Yes, I was having trouble only in that day. Since then it was working fine.

**Comment by MasterGroosha** [comment]
Do you still have this issue? If no, please consider closing it.

**Comment by Doncode** [comment]
Hi.  I have the same  issue today and a week ago.
`pyTelegramBotAPI==3.6.7` 
The bot gets stuck after this error.

```
2020-05-23 00:28:26,815 (util.py:66 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 500 Internal Server Error. Response body:\n[b\'{"ok":false,"error_code":500,"description":"Internal Server Error: restart"}\']',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python3.8/dist-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.8/dist-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.8/dist-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 500 Internal Server Error. Response body:
[b'{"ok":false,"error_code":500,"description":"Internal Server Error: restart"}']
"
```

**Comment by MasterGroosha** [comment]
@Doncode This error means Bot API restarting. Unfortunately, pyTelegramBotAPI cannot handle this error (yet). Consider switching to webhooks.
