### ISSUE TITLE
How can i use telebot through a proxy

### ISSUE THREAD

**Issue by Ivan1512** [eternnoir/pyTelegramBotAPI#416]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
latest
2. What OS are you using?
Windows Server 2012
3. What version of python are you using?
2.7

Hi, i want to configure my telebot file to run across a proxy. ¿Can you help me?

**Comment by Ivan1512** [comment]
It give me this error:
2017-11-20 07:50:18,670 (util.py:64 PollingThread) ERROR - TeleBot: "ConnectTimeout occurred, args=(MaxRetryError("HTTPS
ConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot484111216:AAF5gDgBWB_5MYoHQ18wmlp-
ydnpFXxkXdI/getUpdates?timeout=20&offset=1 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection ob
ject at 0x035D8FD0>, 'Connection to api.telegram.org timed out. (connect timeout=3.5)'))",),)
Traceback (most recent call last):
  File "build\bdist.win32\egg\telebot\util.py", line 58, in run
    task(*args, **kwargs)
  File "build\bdist.win32\egg\telebot\__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "build\bdist.win32\egg\telebot\__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "build\bdist.win32\egg\telebot\apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "build\bdist.win32\egg\telebot\apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot484111216:AAF
5gDgBWB_5MYoHQ18wmlp-ydnpFXxkXdI/getUpdates?timeout=20&offset=1 (Caused by ConnectTimeoutError(<urllib3.connection.Verif
iedHTTPSConnection object at 0x035D8FD0>, 'Connection to api.telegram.org timed out. (connect timeout=3.5)'))
"
2017-11-20 07:50:18,717 (python.py:235 MainThread) ERROR - TeleBot: "HTTPSConnectionPool(host='api.telegram.org', port=4
43): Max retries exceeded with url: /bot484111216:AAF5gDgBWB_5MYoHQ18wmlp-ydnpFXxkXdI/getUpdates?timeout=20&offset=1 (Ca
used by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x035D8FD0>, 'Connection to api.telegr
am.org timed out. (connect timeout=3.5)'))"

I set proxy with:
import os
os.environ["https_proxy"] = "https://10.82.32.254:80/"
os.environ["http_proxy"] = "http://10.82.32.254:80/"

**Comment by MasterGroosha** [comment]
Have you read the corresponding part of [Readme](https://github.com/eternnoir/pyTelegramBotAPI#proxy) ?
