### ISSUE TITLE
When sending message to bot : AttributeError: 'list' object has no attribute 'chat'

### ISSUE THREAD

**Issue by N07070** [eternnoir/pyTelegramBotAPI#42]
```
Exception in thread WorkerThread1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/n07070/.local/lib/python2.7/site-packages/telebot/__init__.py", line 39, in run
    task(*args, **kwargs)
  File "main.py", line 47, in echo_messages
    chatid = m.chat.id
AttributeError: 'list' object has no attribute 'chat'
```

**Comment by N07070** [comment]
Nevermind, I just forgot to take out the * from the example...
