### ISSUE TITLE
Slow Bot Work

### ISSUE THREAD

**Issue by andronpl93** [eternnoir/pyTelegramBotAPI#433]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.5.1
2. What OS are you using?
Windows 7, 64-b
3. What version of python are you using?
3.6

Hello!
In the last two days, the bot is very slow.
One response is sometimes answered instantaneously, sometimes two minutes, at some does not answer at all.
I did not change my bot code, just in case I rolled back to an older and stable version, but it did not help.
I tried to run the bot on different computers with different versions of the python, but everywhere the same problem.

I looked at the library, updates from the server to the Telegram come quickly, everything is working fine, it's sent to the queue, somewhere it hangs for 2 minutes, then it calls the functions I wrote. Some functions it does not call at all.

Translated Google translator, sorry

**Comment by andronpl93** [comment]
Addition
Console gives Expecting value: line 1 column 1 (char 0)
I suspect that json can not decipher the answer

**Comment by eternnoir** [comment]
Could you paste exception's stack trace?

**Comment by andronpl93** [comment]
this message is output by the logger, it does not report the line

**Comment by andronpl93** [comment]
2017-12-11 10:59:22,084 (util.py:64 PollingThread) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:\n[b\'{"ok":false,"error_code":409,"description":"Conflict: terminated by other long poll or webhook"}\']',)
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\telebot\util.py", line 58, in run
    task(*args, **kwargs)
  File "D:\Python36\lib\site-packages\telebot\__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "D:\Python36\lib\site-packages\telebot\__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "D:\Python36\lib\site-packages\telebot\apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "D:\Python36\lib\site-packages\telebot\apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "D:\Python36\lib\site-packages\telebot\apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other long poll or webhook"}']
"
2017-12-11 10:59:22,084 (__init__.py:292 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 409 Conflict. Response body:
[b'{"ok":false,"error_code":409,"description":"Conflict: terminated by other long poll or webhook"}']"
2017-12-11 10:59:22,085 (__init__.py:299 MainThread) INFO - TeleBot: "Waiting for 64.0 seconds until retry"

**Comment by andronpl93** [comment]
Sorry, **not that**
2017-12-11 11:05:11,591 (apihelper.py:55 WorkerThread2) DEBUG - TeleBot: "The server returned: 'b'{"ok":true,"result":{"message_id":,"from":{"id":,"is_bot":true,"first_name":"","username":""},"chat":{"id":,"first_name":"","last_name":"","username":"","type":"private"},"date":,"text":""}}''"
2017-12-11 11:05:26,922 (util.py:59 WorkerThread1) DEBUG - TeleBot: "Task complete"
Expecting value: line 1 column 1 (char 0)
2017-12-11 11:05:28,405 (apihelper.py:55 PollingThread) DEBUG - TeleBot: "The server returned: 'b'{"ok":true,"result":[]}''"

all that is

**Comment by andronpl93** [comment]
I already do not understand anything.
I'm looking at the code between getting the update and calling my functions.
In debug mode, line by line, everything works, the code does not additionally address the server.
But in the normal mode of operation between getting the update and calling my function, he gives me the error 504 (in html format). I do not understand where the library communicates with the server

**Comment by andronpl93** [comment]
The problem was completely in the telegram itself.
They only needed a week to fix it
