### ISSUE TITLE
ImportError: cannot import name 'logger'"

### ISSUE THREAD

**Issue by SkinFish** [eternnoir/pyTelegramBotAPI#448]
Hi there, could you help me with the little problem.
I tried to run telegram bot on the heroku, but he says 
"Traceback (most recent call last):
File "app.py", line 4, in <module>
File "/app/.heroku/python/lib/python3.6/site-packages/telebot/util.py", line 17, in <module>
from telebot import util
File "/app/.heroku/python/lib/python3.6/site-packages/telebot/types.py", line 10, in <module>
ImportError: cannot import name 'logger'"
But I haven't in my code any logger

1. pyTelegramBotAPI - 3.5.1
2. OS: Windows 10
3. Python 3.6.2

requirements.txt - 
"certifi==2018.1.18
chardet==3.0.4
cheroot==6.0.0
CherryPy==13.1.0
idna==2.6
more-itertools==4.0.1
portend==2.2
pyTelegramBotAPI==3.5.1
pytz==2017.3
requests==2.7.0
six==1.11.0
telebot==0.0.3
tempora==1.10
urllib3==1.22"

And piece of code where imports goes:
"import config
import telebot
import requests
from telebot import types
from time import sleep
import datetime"

Sorry for my bad english :/

**Comment by trevorgentry** [comment]
I'm having the same problem. Running Windows 7, Python 3.6.4 (64-bit).
My imports are:
import telebot
import time
from telebot import types

The error it returns:
Traceback (most recent call last):
  File "myfile.py", line 3, in (module)
    from telebot import types
  File "C:\Users\My Username\AppData\Local\Programs\Python\Python36\lib\site-packages\telebot\types.py", line 10, in (module)
    from telebot import util
  File "C:\Users\My Username\AppData\Local\Programs\Python\Python36\lib\site-packages\telebot\util.py", line 17, in (module)
    from telebot import logger
ImportError: cannot import name 'logger'

**Comment by eternnoir** [comment]
Hi @SkinFish, 

Is this problem only happen on heroku?

Hi @trevorgentry,

I tested same import order on my windows pc(windows 10). It works fine. Can you give me some example?

**Comment by trevorgentry** [comment]
@eternnoir I figured it out. When I uninstalled telebot and pyTelegramBotAPI, then installed pyTelegramBotAPI without installing telebot, it worked.

**Comment by fogside** [comment]
Having the same problem.
Running on Ubuntu 17.10, Python 3.6.3 (64 bit).
Error occurs when I do `from telebot import types`
It started to occur when I has upgraded telebot via pip.

> Collecting telebot
>   Downloading telebot-0.0.3.tar.gz
> Collecting requests==2.7.0 (from telebot)
>   Downloading requests-2.7.0-py2.py3-none-any.whl (470kB)
>     100% |████████████████████████████████| 471kB 1.2MB/s 
> Building wheels for collected packages: telebot
>   Running setup.py bdist_wheel for telebot ... done
>   Stored in directory: /home/fogside/.cache/pip/wheels/61/82/d9/dab7ee28d89c8be66333a16abc67c13fba4980a7045fbb6cda
> Successfully built telebot
> Installing collected packages: requests, telebot
>   Found existing installation: requests 2.18.4
>     Uninstalling requests-2.18.4:
>       Successfully uninstalled requests-2.18.4
> Successfully installed requests-2.7.0 telebot-0.0.3

**Error traceback:**
Traceback (most recent call last):
  File "/home/fogside/Projects/NLPCourseBot/quizzes/QuizClasses.py", line 2, in <module>
    from telebot import types
  File "/home/fogside/virtualenvs/py3/lib/python3.6/site-packages/telebot/types.py", line 10, in <module>
    from telebot import util
  File "/home/fogside/virtualenvs/py3/lib/python3.6/site-packages/telebot/util.py", line 17, in <module>
    from telebot import logger
ImportError: cannot import name 'logger'

**Comment by arudmin** [comment]
the same problem

**Comment by eternnoir** [comment]
I will remove import logger from telebot. util module will use there own logger. 48e67576

**Comment by arudmin** [comment]
Thanks, now it works for me.

**Comment by medishettyhruthik** [comment]
2020-05-28T16:07:06.906877+00:00 app[web.1]: Traceback (most recent call last):
2020-05-28T16:07:06.906902+00:00 app[web.1]:   File "b2.py", line 12, in <module>
2020-05-28T16:07:06.907074+00:00 app[web.1]:     from telebot import types
2020-05-28T16:07:06.907075+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/telebot/types.py", line 10, in <module>
2020-05-28T16:07:06.907184+00:00 app[web.1]:     from telebot import util
2020-05-28T16:07:06.907184+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/telebot/util.py", line 16, in <module>
2020-05-28T16:07:06.907301+00:00 app[web.1]:     from telebot import logger
2020-05-28T16:07:06.907303+00:00 app[web.1]: ImportError: cannot import name 'logger'
2020-05-28T16:07:06.987838+00:00 heroku[web.1]: Process exited with status 1
2020-05-28T16:07:07.026439+00:00 heroku[web.1]: State changed from starting to crashed


please give solution to slove this
