### ISSUE TITLE
ERROR - TeleBot: "ConnectionError occurred, args=(ProtocolError('Connection aborted.', TimeoutError(110, 'Connection timed out')),)

### ISSUE THREAD

**Issue by toxidxd** [eternnoir/pyTelegramBotAPI#453]
2018-01-29 08:32:07,077 (util.py:64 WorkerThread1) ERROR - TeleBot: "ConnectionError occurred, args=(ProtocolError('Connection aborted.', TimeoutError(110, 'Connection timed out')),)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 936, in _send_output
    self.send(message_body)
  File "/usr/lib/python3.5/http/client.py", line 908, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.5/ssl.py", line 891, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
TimeoutError: [Errno 110] Connection timed out

1. What version of pyTelegramBotAPI are you using?
Name: pyTelegramBotAPI
Version: 3.5.2

2. What OS are you using?
Linux Mint 18.2

3. What version of python are you using?
Python 3.5.2

**Comment by eternnoir** [comment]
Is it always happen? It seems network problem between your device and telegram bot api server.

**Comment by eatbas** [comment]
Same here after like an 10 min bot gets disconnected help pls

**Comment by eatbas** [comment]
@eternnoir hello man it happens all the time for me. If i leave the bot un attended like 10 min. I instantly get this error. I am using latest version of the bot, windows 10 pycharm and python version 3.5.2 waiting for your answer. I can send the code if you like mostly I am using

bot.register_next_step_handler(msg, trade_type_step)

Waiting for your reply.

**Comment by eatbas** [comment]
2018-02-10 11:38:32,416 (util.py:64 WorkerThread1) ERROR - TeleBot: "ConnectionError occurred, args=(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)),)
Traceback (most recent call last):
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telebot\util.py", line 58, in run
    task(*args, **kwargs)
  File "C:/Users/Eren/Desktop/Projects/boats/cizmeci_V7.py", line 87, in balances_cmd
    bot.reply_to(message, get_balances(), reply_markup=markup)
  File "C:/Users/Eren/Desktop/Projects/boats/cizmeci_V7.py", line 283, in get_balances
    balances['binance'] = my_binance.get_account()['balances']
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 1438, in get_account
    return self._get('account', True, data=params)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 206, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 180, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 174, in _request
    response = getattr(self.session, method)(uri, **kwargs)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
"
2018-02-10 11:38:32,421 (__init__.py:269 MainThread) INFO - TeleBot: "Started polling."
2018-02-10 11:38:32,422 (util.py:55 PollingThread) DEBUG - TeleBot: "Received task"
2018-02-10 11:38:32,422 (apihelper.py:45 PollingThread) DEBUG - TeleBot: "Request: method=get url=https://api.telegram.org/bot498414385:AAFq0xDVzeW7DQilu6rMZer3NzRYHj5rrxs/getUpdates params={'offset': 191135243, 'timeout': 20} files=None"
Traceback (most recent call last):
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
    chunked=chunked)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Eren/Desktop/Projects/boats/cizmeci_V7.py", line 373, in <module>
    bot.polling(none_stop=True)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telebot\__init__.py", line 264, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telebot\__init__.py", line 288, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telebot\util.py", line 107, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telebot\util.py", line 58, in run
    task(*args, **kwargs)
  File "C:/Users/Eren/Desktop/Projects/boats/cizmeci_V7.py", line 87, in balances_cmd
    bot.reply_to(message, get_balances(), reply_markup=markup)
  File "C:/Users/Eren/Desktop/Projects/boats/cizmeci_V7.py", line 283, in get_balances
    balances['binance'] = my_binance.get_account()['balances']
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 1438, in get_account
    return self._get('account', True, data=params)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 206, in _get
    return self._request_api('get', path, signed, version, **kwargs)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 180, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\binance\client.py", line 174, in _request
    response = getattr(self.session, method)(uri, **kwargs)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Eren\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

Process finished with exit code 1

**Comment by eternnoir** [comment]
@eatbas It seems like network problem not package problem. Try some vps to test it.

**Comment by i3wangyi** [comment]
It's always happening on my side as well, I feel like polling method doesn't handle the network failure exception properly (as it only catches ApiException and KeyBoardInterrupt exception) , at least allow several retries is needed.

**Comment by AInsane** [comment]
Had the same problem!!!
if i don`t speak with my bot above 15min it 'sleep' and the first message give this error 
Mar 13 11:08:09 instance-1 python3.6[15983]: 2018-03-13 11:08:09,872 (util.py:65 WorkerThread1) ERROR - TeleBot: "ConnectionError occurred, args=(ProtocolError('Connect
ion aborted.', ConnectionResetError(104, 'Connection reset by peer')),)
.......
ConnectionError(err, request=request)
Mar 13 11:08:09 instance-1 python3.6[15983]: requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Mar 13 11:08:09 instance-1 python3.6[15983]: "

And wit the next messages - everything OK!

Mar 13 11:08:13 instance-1 python3.6[15983]: 149.154.167.226 - - [13/Mar/2018 11:08:13] "POST /TOKEN/ HTTP/1.1" 200 -

**Comment by Stihotvor** [comment]
Same as above. Tested on GCE Ubuntu 18.04

**Comment by Jekeam** [comment]
+1

**Comment by alexshavelev44** [comment]
+1 actual issue

`TeleBot - ERROR - ConnectionError occurred, args=(ProtocolError('Connection aborted.', OSError("(104, 'ECONNRESET')",)),)`

**Comment by haliliceylan** [comment]
+1

**Comment by aever32** [comment]
+1

**Comment by hieupmse05244** [comment]
+1

**Comment by Friedrich42** [comment]
+1

**Comment by LiadBarnes** [comment]
Hi same here but 104

**Comment by YurkaGagarin** [comment]
I have the issue too.
I work on Google DataLab and use telebot lib.
It happen just about after 10 minutes.
I don't use requests lib

**Comment by don-aks** [comment]
+1. This happens when I try to send a voice message.

**Comment by don-aks** [comment]
Solved the problem by sending a smaller file)))).

**Comment by Friedrich42** [comment]
Hello. I didn't find way to solve this problem yet. Maybe I'm gonna use webhooks, but I don't have time to do it nowOn Oct 4, 2019 12:42 PM, don-aks <notifications@github.com> wrote:+1. This happens when I try to send a voice message.

**Comment by tahirjalilov** [comment]
Hello, the same problem for my bit in google cloud vm. Previously my bot was on hetzner and everything was good. Does anyone know how to automatically restart bot if i catch this error?

**Comment by Friedrich42** [comment]
I also use google cloud vm. Dk how to fix it yet. We can use webhooks, i thinkOn Oct 5, 2019 10:43 AM, Tahir Jalilov <notifications@github.com> wrote:Hello, the same problem for my bit in google cloud vm. Previously my bot was on hetzner and everything was good. Does anyone know how to automatically restart bot if i catch this error?

**Comment by YurkaGagarin** [comment]
I solved the issue by following function:
```
def solver(text):
  try:
    msg = InvestingcomPythonEchoBot.send_message(chat_id=XXXXXXXXXXXXXXX, text=text)
  except OSError:
    msg = InvestingcomPythonEchoBot.send_message(chat_id=XXXXXXXXXXXXXXX, text=text)
solver('Problem solved')
```

**Comment by Friedrich42** [comment]
It was easy...On Oct 7, 2019 6:36 PM, YurkaGagarin <notifications@github.com> wrote:I solved the issue by following function:
def solver(text):
  try:
    msg = InvestingcomPythonEchoBot.send_message(chat_id=XXXXXXXXXXXXXXX, text=text)
  except OSError:
    msg = InvestingcomPythonEchoBot.send_message(chat_id=XXXXXXXXXXXXXXX, text=text)
solver('Problem solved')

**Comment by tahirjalilov** [comment]
> I solved the issue by following function:
> 
> ```
> def solver(text):
>   try:
>     msg = InvestingcomPythonEchoBot.send_message(chat_id=XXXXXXXXXXXXXXX, text=text)
>   except OSError:
>     msg = InvestingcomPythonEchoBot.send_message(chat_id=XXXXXXXXXXXXXXX, text=text)
> solver('Problem solved')
> ```

well, as I understood you try to catch OSError every time during sending a message. Correct?

**Comment by Friedrich42** [comment]
Maybe we can handle exception with callback? Idk, actually, I got no time nowOn Oct 7, 2019 9:34 PM, Tahir Jalilov <notifications@github.com> wrote:
I solved the issue by following function:
def solver(text):
  try:
    msg = InvestingcomPythonEchoBot.send_message(chat_id=XXXXXXXXXXXXXXX, text=text)
  except OSError:
    msg = InvestingcomPythonEchoBot.send_message(chat_id=XXXXXXXXXXXXXXX, text=text)
solver('Problem solved')


well, as I understood you try to catch OSError every time during sending a message. Correct?

**Comment by tahirjalilov** [comment]
I did like that:
```
def send_msg(telegram_id, msg):
    try:
        bot.send_message(telegram_id, msg)
    except ConnectionAbortedError:
        bot.send_message(telegram_id, msg)
    except ConnectionResetError:
        bot.send_message(telegram_id, msg)
    except ConnectionRefusedError:
        bot.send_message(telegram_id, msg)
    except ConnectionError:
        bot.send_message(telegram_id, msg)
```
Then I did testing with continuously sending a lot of messages to the bot and everything looks good.

**Comment by tahirjalilov** [comment]
also, you can create cron job which will be check if a bot is not running, start bot
`*/1 * * * * ps -aux | grep grep -v |grep bot.py > /home/user/cronresult.txt || python3 /home/user/TelegramBot/bot.py -args0 -args1`

**Comment by Friedrich42** [comment]
I use supervisor for it. U can bind all the things on itOn Oct 8, 2019 8:35 PM, Tahir Jalilov <notifications@github.com> wrote:also, you can create cron job which will be check if a bot is not running, start bot
*/1 * * * * ps -aux | grep grep -v |grep bot.py > /home/user/cronresult.txt || python3 /home/user/TelegramBot/bot.py -args0 -args1

**Comment by seriousidea** [comment]
I have the same problem on Google Compute Engine + Debian 9 + pyTelegramBotAPI 3.7.1

**Comment by raitonoberu** [comment]
My solution:

    telebot.apihelper.READ_TIMEOUT = 5

    def send_msg(text, id):
        try:
            bot.send_message(id, text)
        except Exception as e:
            logging.info(e)
            send_msg(text, id)

**Comment by janith989** [comment]
I also faced to this issue.any solution?

**Comment by mishagavura** [comment]
But when to call this function?

```

def send_msg(telegram_id, msg):
    try:
        bot.send_message(telegram_id, msg)
    except (ConnectionAbortedError, ConnectionResetError, ConnectionRefusedError, ConnectionError):
        print("ConnectionError - Sending again after 5 seconds!!!")
        time.sleep(5)
        bot.send_message(telegram_id, msg)
```

Like I understood the code, but when should I call this function? Can anybody send an example?

**Comment by camilo-cf** [comment]
I had the same issue. I adapted this solution to my requirements and worked very well.

> My solution:
> 
> ```
> telebot.apihelper.READ_TIMEOUT = 5
> 
> def send_msg(text, id):
>     try:
>         bot.send_message(id, text)
>     except Exception as e:
>         logging.info(e)
>         send_msg(text, id)
> ```

Thank you!!!

**Comment by alcortazzo** [comment]
> My solution:
> 
> ```
> telebot.apihelper.READ_TIMEOUT = 5
> 
> def send_msg(text, id):
>     try:
>         bot.send_message(id, text)
>     except Exception as e:
>         logging.info(e)
>         send_msg(text, id)
> ```

I think this way will be better
```python
def send_msg(text, id):
    try:
        bot.send_message(id, text)
    except Exception as e:
        if type(e).__name__ == 'ConnectionError':
            logging.info('text1')
            time.sleep(3)
            send_msg(text, id)
        logging.info('text2')
```

**Comment by amats6655** [comment]
None of these solutions helped .. every 10-15 minutes of inactivity connection rushes with an error =(

"Connectionerror Occurred, Args = (Protocolerror ('Connection ABORTED.", ConnectionReseTerror (104,' Connection Reset by Peer ')))

**Comment by Xh0st** [comment]
> None of these solutions helped .. every 10-15 minutes of inactivity connection rushes with an error =(
> 
> "Connectionerror Occurred, Args = (Protocolerror ('Connection ABORTED.", ConnectionReseTerror (104,' Connection Reset by Peer ')))

Have you solved? I'm having the same issue. 
working with bot.infinity_polling()
but after inactivity it need 2 or 3 command's to respond

**Comment by pompushko** [comment]
I have the same problem on Google Compute Engine + Debian 10 + pyTelegramBotAPI 3.8.2

**Comment by excitoon** [comment]
Why it is closed? What is the cause of it? Wrong default poll interval? @eternnoir

**Comment by excitoon** [comment]
I guess we can tune connection pool to solve this.

**Comment by excitoon** [comment]
Why `SESSION_TIME_TO_LIVE` is hard-coded to `None`?
