### ISSUE TITLE
Cannot use socks5 proxy

### ISSUE THREAD

**Issue by kmahyyg** [eternnoir/pyTelegramBotAPI#457]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?

Latest Version as I open this issue

2. What OS are you using?

Windows with Pycharm IDE, Production Environment will be Debian.

3. What version of python are you using?

3.6

4. Problem Details

I set the socks5 proxy as the corresponding part of this project README said.
I ensure that ``` pip install requests[socks] ``` successfully installed and can be used by other apps.
I also install PySocks before.

Now, I tried 3 methods as your README mentioned:

(1)  ``` telebot.apihelper.proxy = {'https': 'socks5://127.0.0.1:9099'} ```
(2)  ``` telebot.apihelper.proxy = {'https': 'http://127.0.0.1:9099'} ```
(3 ) ``` proxies = {
    'http': 'socks5://127.0.0.1:9099',
    'https': 'socks5://127.0.0.1:9099'
} ```

Only the second method worked,but if I used that, I'll need an extra polipo program to convert my socks5 proxy to http proxy.

I ensure that the socks5 proxy works fine.
How can I set this python bot working properly with socks5 proxy?

5. Command-Line-Interface StackTrace

```python
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files\Python36\Lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Program Files\Python36\Lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "C:\Program Files\Python36\Lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files\Python36\Lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:761: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files\Python36\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 349, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=3.5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\util.py", line 58, in run
    task(*args, **kwargs)
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=3.5)
"
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files\Python36\Lib\ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "C:\Program Files\Python36\Lib\ssl.py", line 814, in __init__
    self.do_handshake()
  File "C:\Program Files\Python36\Lib\ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "C:\Program Files\Python36\Lib\ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:761: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files\Python36\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 349, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Program Files\Python36\lib\site-packages\urllib3\connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=3.5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/datatrans/github/tg-tb-packagebot/Webflask/tgbot_fn.py", line 20, in <module>
    bot.polling()
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\__init__.py", line 264, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\__init__.py", line 287, in __threaded_polling
    polling_thread.raise_exceptions()
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\util.py", line 77, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\util.py", line 58, in run
    task(*args, **kwargs)
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\__init__.py", line 159, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\__init__.py", line 129, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\apihelper.py", line 175, in get_updates
    return _make_request(token, method_url, params=payload)
  File "E:\datatrans\github\tg-tb-packagebot\Webflask\venv\lib\site-packages\telebot\apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Python36\lib\site-packages\requests\adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=3.5)

Process finished with exit code 1
```

```sh
(venv) E:\datatrans\github\tg-tb-packagebot\Webflask>pip install requests[socks]
Requirement already satisfied: requests[socks] in c:\program files\python36\lib\site-packages
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\program files\python36\lib\site-packages (from requests[socks])
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\program files\python36\lib\site-packages (from requests[socks])
Requirement already satisfied: certifi>=2017.4.17 in e:\datatrans\github\tg-tb-packagebot\webflask\venv\lib\site-packages (from requ
ests[socks])
Requirement already satisfied: idna<2.7,>=2.5 in c:\program files\python36\lib\site-packages (from requests[socks])
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6; extra == "socks" in e:\datatrans\github\tg-tb-packagebot\webflask\venv\lib\si
te-packages (from requests[socks])
```

**Comment by LeoNeeDpk1** [comment]
#493
