### ISSUE TITLE
Error using Webhook (Flask) Example: "ValueError: json_type should be a json dict or string"

### ISSUE THREAD

**Issue by David-Lor** [eternnoir/pyTelegramBotAPI#485]
1. What version of pyTelegramBotAPI are you using? 3.6.2

2. What OS are you using? Ubuntu 16.04 LTS

3. What version of python are you using? 3.5.2

I'm trying to run this example: https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/webhook_examples/webhook_flask_echo_bot.py

But I get this error whenever I send some message or command to the bot:

```
Traceback (most recent call last):
  File "/home/david/.local/lib/python3.5/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/david/.local/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/david/.local/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/david/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/david/.local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/david/.local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/david/.local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/david/.local/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/david/.local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/david/.local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/david/Nextcloud/Codigos/Python/Telegram/VigoBus/Telegram_VigoBus_v2.0_Partido/TelegramBot/WebHook.py", line 46, in webhook
    update = telebot.types.Update.de_json(json_string)
  File "/home/david/.local/lib/python3.5/site-packages/telebot/types.py", line 95, in de_json
    obj = cls.check_json(json_type)
  File "/home/david/.local/lib/python3.5/site-packages/telebot/types.py", line 79, in check_json
    raise ValueError("json_type should be a json dict or string.")
ValueError: json_type should be a json dict or string.
```

**Comment by eternnoir** [comment]
Could your print `json_string` ?

**Comment by EnforcerZhukov** [comment]
I'm trying it again, but now I'm having this other issue, just when the script is starting up:

```
david@Main-Ubuntu:~/Nextcloud/Codigos/Python/Telegram/VigoBus/Telegram_VigoBus_v2.0_Partido/TelegramBot$ python3 WebHookExample.py
 * Running on https://0.0.0.0:8443/ (Press CTRL+C to quit)
 * Restarting with stat
Traceback (most recent call last):
  File "WebHookExample.py", line 78, in <module>
    certificate=open(WEBHOOK_SSL_CERT, 'r'))
  File "/usr/local/lib/python3.4/dist-packages/telebot/__init__.py", line 81, in set_webhook
    return apihelper.set_webhook(self.token, url, certificate, max_connections, allowed_updates)
  File "/usr/local/lib/python3.4/dist-packages/telebot/apihelper.py", line 138, in set_webhook
    return _make_request(token, method_url, params=payload, files=files)
  File "/usr/local/lib/python3.4/dist-packages/telebot/apihelper.py", line 44, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.4/dist-packages/telebot/apihelper.py", line 63, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 429 Too Many Requests. Response body:
[b'{"ok":false,"error_code":429,"description":"Too Many Requests: retry after 1","parameters":{"retry_after":1}}']
```

**Comment by sviat9440** [comment]
@EnforcerZhukov This is not a bug pyTelegramAPI. This is a bug in your code. The server has temporarily restricted access, because of the large number of requests simultaneously. To avoid this error, I recommend to pause between requests in one chat in 1 second.

**Comment by EnforcerZhukov** [comment]
@sviat9440 This isn't even my code, just copied [this example](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/webhook_examples/webhook_flask_echo_bot.py) and replaced the token and webhook_host.

**Comment by AInsane** [comment]
Same problem!!
it`s not workin`  even with time.sleep(2)

Help please
