### ISSUE TITLE
stop_bot method

### ISSUE THREAD

**Issue by RandyRomero** [eternnoir/pyTelegramBotAPI#489]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
v3.6.2

2. What OS are you using?
Windows 10

3. What version of python are you using?
v3.6

New stop_bot method gives me "RuntimeError: cannot join current thread".

**Comment by AlexPlayin** [comment]
Bump

Still getting this issue when trying to shut down the bot gracefully.

Using pyTelegramBotAPI 3.6.6 with python 3.7.1

Code that causes issue:
```import telebot

import json
import io
import threading
import time as time

chatids = []
privateids = []
queue = []
config = {}

endFunction = None

not_stopped = True

def saveConfig(config_temp):
    # param: config object
    # Writes into config.json file
    with open("config.json", "w") as outfile:
        json.dump(config_temp, outfile)


def loadConfig():
    # Reads from config.json file
    # Returns config as object
    with open("config.json") as data_file:
        config_temp = json.load(data_file)

    return config_temp



def loadUsers ():
    with open('users.json') as data_file:
        users = json.load(data_file)
    return users['sub'], users['private']
    

def saveUsers ():
    data = {}
    data['sub'] = chatids
    data['private'] = privateids
    with open('users.json', 'w') as outfile: 
      json.dump(data, outfile)

def listener (messages):
    for m in messages:
        chatid = m.chat.id
        if m.text == "/start":
            if chatids.count(chatid) == 1:
                tb.send_message(chatid, "You are already subscribed!")
            else:
                tb.send_message(chatid, "You are now subscribed!")
                chatids.append(chatid)
                saveUsers()
        if m.text == "/stop":
            if privateids.count(chatid) == 1:
                tb.send_message(chatid, "Bot is now shutting down!")
                #endFunction()
                print(1)
                time.sleep(5)
                print(2)
                tb.stop_bot()
                print(3)


def setEndFunction(function):
    global endFunction
    endFunction = function

def sendBroadcast (message):
    for uid in chatids:
        tb.send_message(uid, message)

def sendPrivate (message):
    for uid in privateids:
        tb.send_message(uid, message)

config = loadConfig()

TOKEN = config['telegram']['bot_token']

chatids, privateids = loadUsers()

tb = telebot.TeleBot(TOKEN)

tb.set_update_listener(listener)

#def toPoll():
tb.polling(none_stop=True, interval=3)


#t = threading.Thread(target=toPoll)
#t.start()
```

Runs within a larger project but error also happens when working solo.

How to reproduce: Send /stop to bot

Expected behavior: Graceful Shutdown

Actual behavior: this
```
bot_1  | 1
bot_1  | 2
bot_1  | 2019-05-15 17:09:12,198 (util.py:65 WorkerThread1) ERROR - TeleBot: "RuntimeError occurred, args=('cannot join current thread',)
bot_1  | Traceback (most recent call last):
bot_1  |   File "/usr/local/lib/python3.7/site-packages/telebot/util.py", line 59, in run
bot_1  |     task(*args, **kwargs)
bot_1  |   File "/app/telegrambot.py", line 64, in listener
bot_1  |     tb.stop_bot()
bot_1  |   File "/usr/local/lib/python3.7/site-packages/telebot/__init__.py", line 472, in stop_bot
bot_1  |     self.worker_pool.close()
bot_1  |   File "/usr/local/lib/python3.7/site-packages/telebot/util.py", line 117, in close
bot_1  |     worker.join()
bot_1  |   File "/usr/local/lib/python3.7/threading.py", line 1029, in join
bot_1  |     raise RuntimeError("cannot join current thread")
bot_1  | RuntimeError: cannot join current thread
bot_1  | "
bot_1  | Traceback (most recent call last):
bot_1  |   File "main.py", line 21, in <module>
bot_1  |     import telegrambot
bot_1  |   File "/app/telegrambot.py", line 91, in <module>
bot_1  |     tb.polling(none_stop=True, interval=3)
bot_1  |   File "/usr/local/lib/python3.7/site-packages/telebot/__init__.py", line 389, in polling
bot_1  |     self.__threaded_polling(none_stop, interval, timeout)
bot_1  |   File "/usr/local/lib/python3.7/site-packages/telebot/__init__.py", line 413, in __threaded_polling
bot_1  |     self.worker_pool.raise_exceptions()
bot_1  |   File "/usr/local/lib/python3.7/site-packages/telebot/util.py", line 108, in raise_exceptions
bot_1  |     six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
bot_1  |   File "/usr/local/lib/python3.7/site-packages/six.py", line 693, in reraise
bot_1  |     raise value
bot_1  |   File "/usr/local/lib/python3.7/site-packages/telebot/util.py", line 59, in run
bot_1  |     task(*args, **kwargs)
bot_1  |   File "/app/telegrambot.py", line 64, in listener
bot_1  |     tb.stop_bot()
bot_1  |   File "/usr/local/lib/python3.7/site-packages/telebot/__init__.py", line 472, in stop_bot
bot_1  |     self.worker_pool.close()
bot_1  |   File "/usr/local/lib/python3.7/site-packages/telebot/util.py", line 117, in close
bot_1  |     worker.join()
bot_1  |   File "/usr/local/lib/python3.7/threading.py", line 1029, in join
bot_1  |     raise RuntimeError("cannot join current thread")
bot_1  | RuntimeError: cannot join current thread

```
