### ISSUE TITLE
Socks5 proxy error

### ISSUE THREAD

**Issue by kostykoff** [eternnoir/pyTelegramBotAPI#499]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI==3.6.2
2. What OS are you using?
Linux Mint 18.3
3. What version of python are you using?
Python 2.7.12
4.
gunicorn==19.7.1
PySocks==1.6.8
requests==2.18.4
urllib3==1.22
in the code added

`from telebot import apihelper`
and after
`bot = telebot.TeleBot(token)`
added
apihelper.proxy = {'https': 'socks5://login:password@domain:1080'}

`Traceback (most recent call last):
  File "/home/kostykoff/scripts/python/guts/dev/guts_code.py", line 9, in <module>
    bot.send_message(log_channel, "❎ GUTS bot was launched ❎")
  File "/usr/local/lib/python2.7/dist-packages/telebot/__init__.py", line 470, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line 135, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botXXXXX:XXXXXXXXX/sendMessage?text=%E2%9D%8E+GUTS+bot+was+launched+%E2%9D%8E&chat_id=-XXXXXXXXXX (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'unknown protocol')],)",),))
[Finished in 0.9s with exit code 1]
[shell_cmd: python -u "/home/kostykoff/scripts/python/guts/dev/guts_code.py"]
[dir: /home/kostykoff/scripts/python/guts/dev]
[path: /home/kostykoff/bin:/home/kostykoff/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games]`

**Comment by kostykoff** [comment]
Traceback (most recent call last):
  File "guts_code.py", line 15, in <module>
    bot.send_message(log_channel, "❎ GUTS bot was launched ❎")
  File "/usr/local/lib/python2.7/dist-packages/telebot/__init__.py", line 470, in send_message
    reply_markup, parse_mode, disable_notification))
  File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line 136, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: SOCKSHTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /botXXXXXXXX:XXXXXXXX/sendMessage?text=%E2%9D%8E+GUTS+bot+was+launched+%E2%9D%8E&chat_id=-XXXXXXXXXX (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),))

**Comment by kostykoff** [comment]
solution:
delete the current requests
`pip unistall requests`
and put the working version - 
`pip install -Iv requests=2.10.0`
