### ISSUE TITLE
Don't work bot through socks5 (apihelper)

### ISSUE THREAD

**Issue by Cenzor** [eternnoir/pyTelegramBotAPI#517]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.6.3
2. What OS are you using?
Debian buster(sid)
3. What version of python are you using?
3.6

Hi.
I try to start bot with apihelper.proxy.
I adding string apihelper.proxy = {'https':'socks5://userproxy:password@proxy_address:port'}.
Try with webhook_cherrypy and appears this:
```
ENGINE Listening for SIGTERM.
ENGINE Listening for SIGHUP.
ENGINE Listening for SIGUSR1.
ENGINE Bus STARTING
ENGINE Started monitor thread 'Autoreloader'.
ENGINE Serving on https://0.0.0.0
ENGINE Bus STARTED
ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/cheroot/server.py", line 1538, in start
    self.tick()
  File "/usr/local/lib/python3.6/site-packages/cheroot/server.py", line 1622, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/local/lib/python3.6/site-packages/cheroot/ssl/builtin.py", line 72, in wrap
    sock, do_handshake_on_connect=True, server_side=True,
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```
When i pressing ctrl+c, then appears this:
```
ENGINE Keyboard Interrupt: shutting down bus
ENGINE Bus STOPPING
ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 443)) shut down
ENGINE Stopped thread 'Autoreloader'.
ENGINE Bus STOPPED
ENGINE Bus EXITING
ENGINE Bus EXITED
ENGINE Waiting for child threads to terminate...
```

Also i trying to start the bot with webhook_aiohttp and he is running:
```
======== Running on https://0.0.0.0:443 ========
(Press CTRL+C to quit)
```
But if i send a message to the bot, nothing happens.
Can you help me please?

**Comment by Onefivefournine** [comment]
Found solution here, thanks for @kostykoff
https://github.com/eternnoir/pyTelegramBotAPI/issues/499#issuecomment-387101672
You just need to install version 2.10.0 of requests
