### ISSUE TITLE
ENGINE Error in HTTPServer.tick

### ISSUE THREAD

**Issue by sshkrv** [eternnoir/pyTelegramBotAPI#530]
pyTelegramBotAPI (3.6.3)
ubuntu 18.04(x64)
python 3.6

Hello! I am simply launching the example from the webhook_examples folder (webhook_cherrypy_echo_bot.py). Added my token, server address and certificates. And I see this Traceback

`[08/Jul/2018:20:21:13] ENGINE Listening for SIGTERM.
[08/Jul/2018:20:21:13] ENGINE Listening for SIGHUP.
[08/Jul/2018:20:21:13] ENGINE Listening for SIGUSR1.
[08/Jul/2018:20:21:13] ENGINE Bus STARTING
[08/Jul/2018:20:21:13] ENGINE Started monitor thread 'Autoreloader'.
[08/Jul/2018:20:21:13] ENGINE Serving on https://0.0.0.0:8443
[08/Jul/2018:20:21:13] ENGINE Bus STARTED
[08/Jul/2018:20:21:13] ENGINE Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cheroot/server.py", line 1714, in start
    self.tick()
  File "/usr/local/lib/python3.6/dist-packages/cheroot/server.py", line 1811, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/local/lib/python3.6/dist-packages/cheroot/ssl/builtin.py", line 96, in wrap
    sock, do_handshake_on_connect=True, server_side=True,
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error`

What is wrong and what do I have to change?

**Comment by kor0p** [comment]
The same problem on my ubuntu 18.04, but on ubuntu 16.04 on my ssh server all is okay…
Call me, please, if you solve this!
