### ISSUE TITLE
Send file/sticker/audio by ID

### ISSUE THREAD

**Issue by HJulio** [eternnoir/pyTelegramBotAPI#59]
Is there some way to send a file/sticker/etc by ID (already stored in Telegram's server) instead of upload the file again?

**Comment by pevdh** [comment]
Simply provide a string instead of an actual file.
`bot.send_sticker(chat_id, "<SOME_ID>")`

**Comment by gashish1n** [comment]
> Simply provide a string instead of an actual file.
> `bot.send_sticker(chat_id, "<SOME_ID>")`

I get an error:
```
user@server:~$ python3 fdsfds.py
2019-07-03 03:41:20,925 (util.py:65 WorkerThread1) ERROR - TeleBot: "AttributeError occurred, args=("'TeleBot' object has no attribute 'photo'",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "fdsfds.py", line 43, in photo
    bot.photo(message.from_user.id, "AgADAgADbqsxG7kKcUi_CjymHgiEtX_Utw8ABNTJB6A9-S3OhCcAAgI")
AttributeError: 'TeleBot' object has no attribute 'photo'
"
Traceback (most recent call last):
  File "fdsfds.py", line 50, in <module>
    bot.polling(none_stop = True)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 389, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/usr/local/lib/python3.5/dist-packages/telebot/__init__.py", line 413, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 108, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "fdsfds.py", line 43, in photo
    bot.photo(message.from_user.id, "AgADAgADbqsxG7kKcUi_CjymHgiEtX_Utw8ABNTJB6A9-S3OhCcAAgI")
AttributeError: 'TeleBot' object has no attribute 'photo'
```
Even if you add <>, nothing changes.

**Comment by Badiboy** [comment]
` bot.photo(message.from_user.id, ...)`

Lol, you got AttributeError: _'TeleBot' object has no attribute 'photo'_ because... 'TeleBot' object has no attribute 'photo'. 

Even if you take a look on the main page (https://github.com/eternnoir/pyTelegramBotAPI) and search for the word "photo" you'll see...

```
# All send_xyz functions which can take a file as an argument, can also take a file_id instead of a file.
# sendPhoto
photo = open('/tmp/photo.png', 'rb')
tb.send_photo(chat_id, photo)
tb.send_photo(chat_id, "FILEID")
```

**Comment by gashish1n** [comment]
Apparently I accidentally deleted the "send_". Here is what I am trying to send:
if message.text == "Hello":
            bot.send_message(message.from_user.id, "Hello!")
            bot.send_video(message.from_user.id, "BAADAgADRAMAAvlk-Ejjn4i0OUcDewI")
It produces error 400.
