### ISSUE TITLE
TypeError: an integer is required (got type tuple)

### ISSUE THREAD

**Issue by naziks** [eternnoir/pyTelegramBotAPI#674]
_Versions:_
1.  pyTelegramBotAPI v3.6.6
2. OS Windows 10 x64
3. Python v3.7

My error:
```
2019-07-15 18:06:02,928 (util.py:65 PollingThread) ERROR - TeleBot: "TypeError occurred, args=('an integer is required (got type tuple)',)
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\telebot\util.py", line 59, in run
    task(*args, **kwargs)
  File "C:\Python\lib\site-packages\telebot\__init__.py", line 276, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Python\lib\site-packages\telebot\__init__.py", line 246, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Python\lib\site-packages\telebot\apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Python\lib\site-packages\telebot\apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 252, in request
    r.send(prefetch=prefetch)
  File "C:\Python\lib\site-packages\requests\models.py", line 620, in send
    timeout=self.timeout,
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 423, in urlopen
    body=body, headers=headers)
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 275, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Python\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 95, in connect
    sock = socket.create_connection((self.host, self.port), self.timeout)
  File "C:\Python\lib\socket.py", line 713, in create_connection
    sock.settimeout(timeout)
TypeError: an integer is required (got type tuple)
"
Traceback (most recent call last):
  File "C:\Users\Nazarko\Desktop\hikvision_tg_bot.py", line 155, in <module>
    bot.polling(none_stop = True)
  File "C:\Python\lib\site-packages\telebot\__init__.py", line 389, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "C:\Python\lib\site-packages\telebot\__init__.py", line 412, in __threaded_polling
    polling_thread.raise_exceptions()
  File "C:\Python\lib\site-packages\telebot\util.py", line 78, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "C:\Python\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Python\lib\site-packages\telebot\util.py", line 59, in run
    task(*args, **kwargs)
  File "C:\Python\lib\site-packages\telebot\__init__.py", line 276, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "C:\Python\lib\site-packages\telebot\__init__.py", line 246, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "C:\Python\lib\site-packages\telebot\apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "C:\Python\lib\site-packages\telebot\apihelper.py", line 54, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "C:\Python\lib\site-packages\requests\sessions.py", line 252, in request
    r.send(prefetch=prefetch)
  File "C:\Python\lib\site-packages\requests\models.py", line 620, in send
    timeout=self.timeout,
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 423, in urlopen
    body=body, headers=headers)
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 275, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Python\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Python\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Python\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 95, in connect
    sock = socket.create_connection((self.host, self.port), self.timeout)
  File "C:\Python\lib\socket.py", line 713, in create_connection
    sock.settimeout(timeout)
TypeError: an integer is required (got type tuple)
```

**Comment by naziks** [comment]
After reinstalling Python and the problem disappear :)
