### ISSUE TITLE
have error in util.py when try to search value in sqlite-database

### ISSUE THREAD

**Issue by bazhil** [eternnoir/pyTelegramBotAPI#696]
Please answer these questions before submitting your issue. Thanks!

1. I use pyTelegramBotAPI-3.6.6-py3.7.egg-info

2. Windows 7

3. Python 3.7

I have strange error in file util.py when run my code and don't understand what to do with it.

Code:
db = 'rutracker.sqlite'
    conn = sqlite3.connect(db)
    cursor = conn.cursor()
    answer = ''

    if (CATEGORY is not None) and (SUBCATEGORY is not None):
        try:
            cursor.execute(
                "SELECT * FROM torrents WHERE Category=? AND Subcategory=?", (CATEGORY, SUBCATEGORY)
            )
            result = cursor.fetchall()
            print(result)
            for i in result:
                name = list(i)[2]
                link = list(i)[3]
                if QUERY in name.lower():
                    answer += name + '\n' + link + '\n\n'
            bot.send_message(message.from_user.id, answer)
            conn.commit()
        except sqlite3.DatabaseError as err:
            print("Error: ", err)
        finally:
            conn.close()

Error text:
2019-09-30 20:18:31,384 (util.py:65 WorkerThread1) ERROR - TeleBot: "TypeError occurred, args=("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "C:\Users\home\PycharmProjects\torrent_bot\venv\lib\site-packages\telebot\util.py", line 59, in run
    task(*args, **kwargs)
TypeError: 'NoneType' object is not callable
"
2019-09-30 20:18:31,386 (util.py:65 WorkerThread1) ERROR - TeleBot: "TypeError occurred, args=("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "C:\Users\home\PycharmProjects\torrent_bot\venv\lib\site-packages\telebot\util.py", line 59, in run
    task(*args, **kwargs)
TypeError: 'NoneType' object is not callable
"
Traceback (most recent call last):
  File "C:/Users/home/PycharmProjects/torrent_bot/torrent_bot.py", line 5503, in <module>
2019-09-30 20:18:31,422 (util.py:65 WorkerThread2) ERROR - TeleBot: "TypeError occurred, args=("'NoneType' object is not callable",)
Traceback (most recent call last):
  File "C:\Users\home\PycharmProjects\torrent_bot\venv\lib\site-packages\telebot\util.py", line 59, in run
    task(*args, **kwargs)
TypeError: 'NoneType' object is not callable
"
    bot.polling(none_stop=True, interval=0, timeout=20)
  File "C:\Users\home\PycharmProjects\torrent_bot\venv\lib\site-packages\telebot\__init__.py", line 389, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "C:\Users\home\PycharmProjects\torrent_bot\venv\lib\site-packages\telebot\__init__.py", line 413, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\home\PycharmProjects\torrent_bot\venv\lib\site-packages\telebot\util.py", line 108, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "C:\Users\home\PycharmProjects\torrent_bot\venv\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\home\PycharmProjects\torrent_bot\venv\lib\site-packages\telebot\util.py", line 59, in run
    task(*args, **kwargs)
TypeError: 'NoneType' object is not callable

Debug result on photo.
![image](https://user-images.githubusercontent.com/31971067/65900907-b9faf080-e3bf-11e9-9b5c-e81491ec9fd4.png)

**Comment by Badiboy** [comment]
Problem is still actual?

**Comment by bazhil** [comment]
@Badiboy Yes, i don't understand this situation and can't resolve it.
