### ISSUE TITLE
Can't define token during runtime

### ISSUE THREAD

**Issue by YorozuyaDev** [eternnoir/pyTelegramBotAPI#720]
I am using pyTelegramBotAPI version 3.6.6, using Arch Linux (GNU/LInux) with python version 3.8.0
### What doesn't work?
I try to read the token from a config file. 
```python
#Creates the bot object and imports preferences
config = configparser.ConfigParser()
config.read('authbot.conf')
TOKEN = config['Security']['TOKEN']
bot.telebot.TeleBot(TOKEN)
```
It's return following error:
```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.telegram.org
DEBUG:requests.packages.urllib3.connectionpool:"GET /bot'1004654243:AAHsL1ZsPooeqF7W2G5fVbLelmMRw7uLtzs'/getUpdates?offset=1&timeout=20 HTTP/1.1" 404 55
ERROR:TeleBot:ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 404 Not Found. Response body:\n[b\'{"ok":false,"error_code":404,"description":"Not Found"}\']',)
Traceback (most recent call last):
  File "/home/yorozuya3/Desktop/authtelegrambot/env/lib/python3.8/site-packages/telebot/util.py", line 59, in run
    task(*args, **kwargs)
  File "/home/yorozuya3/Desktop/authtelegrambot/env/lib/python3.8/site-packages/telebot/__init__.py", line 276, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/yorozuya3/Desktop/authtelegrambot/env/lib/python3.8/site-packages/telebot/__init__.py", line 246, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/home/yorozuya3/Desktop/authtelegrambot/env/lib/python3.8/site-packages/telebot/apihelper.py", line 180, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/yorozuya3/Desktop/authtelegrambot/env/lib/python3.8/site-packages/telebot/apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "/home/yorozuya3/Desktop/authtelegrambot/env/lib/python3.8/site-packages/telebot/apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 404 Not Found. Response body:
[b'{"ok":false,"error_code":404,"description":"Not Found"}']

ERROR:TeleBot:A request to the Telegram API was unsuccessful. The server returned HTTP 404 Not Found. Response body:
[b'{"ok":false,"error_code":404,"description":"Not Found"}']

```
### What works?
```python
TOKEN = 'my token'
bot = telebot.TeleBot(TOKEN)
```

**Comment by Badiboy** [comment]
Token can be set only when creating TeleBot instance:
`bot = telebot.TeleBot(TOKEN)`
This:
`bot.telebot.TeleBot(TOKEN)`
is a very stange crap.

**Comment by ikasymov** [comment]
I've inherited TeleBot

class MyTeleBot(TeleBot):
    def set_token(self, new_token):
        self.token = new_token


bot = MyTeleBot(old_token)
bot.set_token(new_token)
