### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wmchina** [eternnoir/pyTelegramBotAPI#754]
Hello, how can I solve the following errors when running?

Traceback (most recent call last):
  File "main.py", line 187, in <module>
    tb.polling()
  File "/usr/local/lib/python3.8/site-packages/telebot/__init__.py", line 392, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/usr/local/lib/python3.8/site-packages/telebot/__init__.py", line 415, in __threaded_polling
    polling_thread.raise_exceptions()
  File "/usr/local/lib/python3.8/site-packages/telebot/util.py", line 79, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/usr/local/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/telebot/util.py", line 60, in run
    task(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/telebot/__init__.py", line 279, in __retrieve_updates
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/telebot/__init__.py", line 249, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout, allowed_updates)
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 194, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 57, in _make_request
    result = _get_req_session().request(method, request_url, params=params, files=files,
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.telegram.org', port=443): Read timed out. (read timeout=30)

**Comment by wmchina** [comment]
![c](https://user-images.githubusercontent.com/46123608/74666395-5f322c00-51dc-11ea-8bb1-5a261eea18bd.png)
Here is the error code section

**Comment by gashish1n** [comment]
I think [it will help you](https://github.com/eternnoir/pyTelegramBotAPI/issues/474).
