### ISSUE TITLE
Please answer these questions before submitting your issue. Thanks!

### ISSUE THREAD

**Issue by wmchina** [eternnoir/pyTelegramBotAPI#755]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
pyTelegramBotAPI 3.6.7
2. What OS are you using?
ubuntu18
3. What version of python are you using?
3.8
If the deleted message does not exist, the following error occurs. How to eliminate this?

Traceback (most recent call last):
  File "e.py", line 11, in <module>
    ab = tb.delete_message('-1001160301052','246697')
  File "/usr/local/lib/python3.8/site-packages/telebot/__init__.py", line 622, in delete_message
    return apihelper.delete_message(self.token, chat_id, message_id)
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 713, in delete_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 60, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python3.8/site-packages/telebot/apihelper.py", line 79, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: message to delete not found"}']

**Comment by Badiboy** [comment]
If the deleted message does not exist, the following error occurs. How to eliminate this?

"try / except"
