### ISSUE TITLE
HTTP 400 Bad Request: Bad Request: can't parse entities: Unexpected end of name token at byte offset 291

### ISSUE THREAD

**Issue by Nereg** [eternnoir/pyTelegramBotAPI#758]
1. What version of pyTelegramBotAPI are you using? **3.6.6**

2. What OS are you using? **Windows 10**

3. What version of python are you using? **3.8.0**

Hi! I just recived this error:
```
2020-02-23 19:33:38,069 (apihelper.py:55 WorkerThread2) DEBUG - TeleBot: "The server returned: 'b'{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse entities: Unexpected end of name token at byte offset 291"}''"
2020/02/23 19:33:38 apihelper,line: 55    DEBUG | The server returned: 'b'{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse entities: Unexpected end of name token at byte offset 291"}''
2020-02-23 19:33:38,070 (util.py:65 WorkerThread2) ERROR - TeleBot: "ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:\n[b\'{"ok":false,"error_code":400,"description":"Bad Request: can\\\'t parse entities: Unexpected end of name token at byte offset 291"}\']',)
Traceback (most recent call last):
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\util.py", line 59, in run
    task(*args, **kwargs)
  File "main.py", line 191, in handle_me
    bot.send_message(message.chat.id,Mymessage,parse_mode='html')
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\__init__.py", line 597, in send_message
    apihelper.send_message(self.token, chat_id, text, disable_web_page_preview, reply_to_message_id,
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse entities: Unexpected end of name token at byte offset 291"}']
"
2020/02/23 19:33:38 util,line: 65    ERROR | ApiException occurred, args=('A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:\n[b\'{"ok":false,"error_code":400,"description":"Bad Request: can\\\'t parse entities: Unexpected end of name token at byte offset 291"}\']',)
Traceback (most recent call last):
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\util.py", line 59, in run
    task(*args, **kwargs)
  File "main.py", line 191, in handle_me
    bot.send_message(message.chat.id,Mymessage,parse_mode='html')
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\__init__.py", line 597, in send_message
    apihelper.send_message(self.token, chat_id, text, disable_web_page_preview, reply_to_message_id,
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 140, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 56, in _make_request
    return _check_result(method_name, result)['result']
  File "C:\Users\Oleg\AppData\Local\Programs\Python\Python38-32\lib\site-packages\telebot\apihelper.py", line 75, in _check_result
    raise ApiException(msg, method_name, result)
telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse entities: Unexpected end of name token at byte offset 291"}']

2020-02-23 19:33:38,073 (__init__.py:417 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse entities: Unexpected end of name token at byte offset 291"}']"
2020/02/23 19:33:38 __init__,line: 417    ERROR | A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
[b'{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse entities: Unexpected end of name token at byte offset 291"}']
2020-02-23 19:33:38,073 (__init__.py:420 MainThread) INFO - TeleBot: "Exception occurred. Stopping."
2020/02/23 19:33:38 __init__,line: 420     INFO | Exception occurred. Stopping.
2020-02-23 19:33:38,073 (__init__.py:433 MainThread) INFO - TeleBot: "Stopped polling."
2020/02/23 19:33:38 __init__,line: 433     INFO | Stopped polling.
```
I'm sending message like 500 characters long so it isn't a problem.

**Comment by Nereg** [comment]
Any advice ?

**Comment by Badiboy** [comment]
What advice you want to hear? Just read the error message.

> telebot.apihelper.ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 400 Bad Request. Response body:
> [b'{"ok":false,"error_code":400,"description":"Bad Request: can\'t parse entities: Unexpected end of name token at byte offset 291"}']"

Everything is in the message: you sent bad formatted markdown/html.

**Comment by Nereg** [comment]
Oh ok I will review my html.
