### ISSUE TITLE
ValueError: json_type should be a json dict or string.

### ISSUE THREAD

**Issue by LGleba** [eternnoir/pyTelegramBotAPI#774]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using? 3.6.7

2. What OS are you using? Ubuntu 14.04

3. What version of python are you using? 3.4

My code
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

# This is a simple echo bot using decorators and webhook with BaseHTTPServer
# It echoes any incoming text messages and does not use the polling method.

from http.server import BaseHTTPRequestHandler, HTTPServer

import logging
import ssl
import config
import telebot

API_TOKEN = config.TOKEN

WEBHOOK_HOST = config.ip
WEBHOOK_PORT = 8443  # 443, 80, 88 or 8443 (port need to be 'open')
WEBHOOK_LISTEN = '0.0.0.0'  # In some VPS you may need to put here the IP addr

WEBHOOK_SSL_CERT = './webhook_cert.pem'  # Path to the ssl certificate
WEBHOOK_SSL_PRIV = './webhook_pkey.pem'  # Path to the ssl private key

# Quick'n'dirty SSL certificate generation:
#
# openssl genrsa -out webhook_pkey.pem 2048
# openssl req -new -x509 -days 3650 -key webhook_pkey.pem -out webhook_cert.pem
#
# When asked for "Common Name (e.g. server FQDN or YOUR name)" you should reply
# with the same value in you put in WEBHOOK_HOST

WEBHOOK_URL_BASE = "https://%s:%s" % (WEBHOOK_HOST, WEBHOOK_PORT)
WEBHOOK_URL_PATH = "/%s/" % (API_TOKEN)

logger = telebot.logger
telebot.logger.setLevel(logging.INFO)

bot = telebot.TeleBot(API_TOKEN)


# WebhookHandler, process webhook calls
class WebhookHandler(BaseHTTPRequestHandler):
    server_version = "WebhookHandler/1.0"

    def do_HEAD(self):
        self.send_response(200)
        self.end_headers()

    def do_GET(self):
        self.send_response(200)
        self.end_headers()

    def do_POST(self):
        if self.path == WEBHOOK_URL_PATH and \
           'content-type' in self.headers and \
           'content-length' in self.headers and \
           self.headers['content-type'] == 'application/json':
            json_string = self.rfile.read(int(self.headers['content-length']))

            self.send_response(200)
            self.end_headers()

            update = telebot.types.Update.de_json(json_string)
            bot.process_new_messages([update.message])
        else:
            self.send_error(403)
            self.end_headers()


# Handle '/start' and '/help'
@bot.message_handler(commands=['help', 'start'])
def send_welcome(message):
    bot.send_message(message.chat.id, 'Test 1 command')


# Handle all other messages
@bot.message_handler(func=lambda message: True, content_types=['text'])
def echo_message(message):
    bot.send_message(message.chat.id, 'Test 2 command')


# Remove webhook, it fails sometimes the set if there is a previous webhook
bot.remove_webhook()

# Set webhook
# Beacuse telegram bot api server will check webhook server is alive.
# Here we need set webhook after server started manually.
bot.set_webhook(url=WEBHOOK_URL_BASE + WEBHOOK_URL_PATH,
                certificate=open(WEBHOOK_SSL_CERT, 'r'))

# Start server
httpd = HTTPServer((WEBHOOK_LISTEN, WEBHOOK_PORT),
                   WebhookHandler)

httpd.socket = ssl.wrap_socket(httpd.socket,
                               certfile=WEBHOOK_SSL_CERT,
                               keyfile=WEBHOOK_SSL_PRIV,
                               server_side=True)

httpd.serve_forever()
```

Error
```
----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.4/socketserver.py", line 305, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 331, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.4/socketserver.py", line 673, in __init__
    self.handle()
  File "/usr/lib/python3.4/http/server.py", line 398, in handle
    self.handle_one_request()
  File "/usr/lib/python3.4/http/server.py", line 386, in handle_one_request
    method()
  File "main.py", line 62, in do_POST
    update = telebot.types.Update.de_json(json_string)
  File "/usr/local/lib/python3.4/dist-packages/telebot/types.py", line 95, in de_json
    obj = cls.check_json(json_type)
  File "/usr/local/lib/python3.4/dist-packages/telebot/types.py", line 79, in check_json
    raise ValueError("json_type should be a json dict or string.")
ValueError: json_type should be a json dict or string.
----------------------------------------
```

Where did I make a mistake?

**Comment by Badiboy** [comment]
I do not see anything relative to pyTelegramBotAPI here.

**Comment by LGleba** [comment]
I took the example from pyTelegramBotAPI/examples/webhook_examples/webhook_cpython_echo_bot.py/

pyTelegramBotAPI is installed

> I do not see anything relative to pyTelegramBotAPI here.
> 
> See exmaples how to use pyTelegramBotAPI.
> 
> And check that you installed **pyTelegramBotAPI** but not **telebot**.

**Comment by Badiboy** [comment]
Hm, you are right, sorry.  I did not see this example.

Cannot give any help. Use FLASK example, I use it even in production (I know that's not too good practice) and it's fine.

**Comment by underskys** [comment]
use json.dumps(json_string) before send it.
