### ISSUE TITLE
Unhandled exceptions in the polling Thread causes bot to stop working but the process doesn't die.

### ISSUE THREAD

**Issue by skgsergio** [eternnoir/pyTelegramBotAPI#78]
If an Exception occurs in the polling *Thread*, then the bot stays running but not receiving more updates, seems like the polling thread dies but doesn't exit the process.

More Info in https://github.com/eternnoir/pyTelegramBotAPI/issues/78#issuecomment-144653036

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/__init__.py", line 145, in __polling
    self.get_update()
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/__init__.py", line 87, in get_update
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=3)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/__init__.py", line 75, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 117, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 26, in _make_request
    result = requests.request(method, request_url, params=params, files=files)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 420, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:581)
```

**Comment by pevdh** [comment]
Does it still make getUpdates request to the Telegram servers?

**Comment by skgsergio** [comment]
@pevdh Not sure, because I didn't have the logger. But hours after the exception the bot did not react to commands.

**Comment by skgsergio** [comment]
Ok more info, If the main polling thread, *Thread-1*, sends an exception the polling stops but the process doesn't exits.

Example 1: Not forced exception, just happened tonight. No more responses from the bot since the exception, didn't have debug enabled so couldn't see more, but the lines in the buffer were this:

```
2015-09-30 23:56:17,083 (__init__.py:140) INFO - TeleBot: "Started polling."
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/__init__.py", line 145, in __polling
    self.get_update()
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/__init__.py", line 87, in get_update
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=3)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/__init__.py", line 75, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 117, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 26, in _make_request
    result = requests.request(method, request_url, params=params, files=files)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

Example 2: Forced error, I did MitM to the bot to cause an invalid certificate error, SSLError. This time debug enabled, when the exception triggers no more debug lines, don't make more requests to getUpdates, the Tread dies but the process keeps running:

```
2015-10-01 09:54:22,125 (__init__.py:140) INFO - TeleBot: "Started polling."
[...]
2015-10-01 09:58:21,262 (__init__.py:97) DEBUG - TeleBot: "Received 1 new messages"
2015-10-01 09:58:21,263 (apihelper.py:25) DEBUG - TeleBot: "Request: method=get url=https://api.telegram.org/bot123456789:THISISMYBOTTOKEN/getUpdates params={'timeout': 20, 'offset': 684153867} files=None"
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/__init__.py", line 150, in __polling
    self.get_update(timeout)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/__init__.py", line 91, in get_update
    updates = self.get_updates(offset=(self.last_update_id + 1), timeout=timeout)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/__init__.py", line 79, in get_updates
    json_updates = apihelper.get_updates(self.token, offset, limit, timeout)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 117, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/home/sergio/.local/lib/python2.7/site-packages/telebot/apihelper.py", line 26, in _make_request
    result = requests.request(method, request_url, params=params, files=files)
  File "/home/sergio/.local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/sergio/.local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/sergio/.local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/sergio/.local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

Now a separate question: If a *WorkerThread* sends an unhandled exception, like an ApiException, that worker die. Don't know if its intentional and left like that for the user to handle, can confirm? (I can just try/catch that exceptions when I call the api methods). Example: ```ApiException: A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[{"ok":false,"error_code":403,"description":"Error: Bot was kicked from a chat"}]```

**Comment by pevdh** [comment]
It's a bit ugly that a WorkerThread dies when an Exception is not handled, I must say, because the user cannot create a new WorkerThread to replace the old one. (Well one could, but one must know about the internals of TeleBot). The Thread not ending is a bit strange though, since the polling Thread (Thread-1) dies, after which [this line](https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/__init__.py#L135) should be False and the function should return. I have to investigate this issue more in depth to see why this does not happen.

**Comment by pevdh** [comment]
Do you have a suggestion for the WorkerThread issue (@eternnoir as well)?

**Comment by skgsergio** [comment]
@pevdh *maybe* the *WorkerThread* should catch all exceptions generated by the *task* and log it with level *ERROR* telling about the exception name and details. This will avoid the WorkerThread dying.

For example ApiExceptions may occur when bot kicked from a group immediately after one user use a command and the bot tries to reply, and it's kinda annoying because people is not aware this could happen.

Other source of Exceptions is, for example, file manipulation (don't exist, no permissions, etc...) but this kind of exceptions SHOULD be catch by the users but if its not this kills the WorkerThread (yep I did a quick'n'dirty bot code that had this problem xD).

**Comment by pevdh** [comment]
If one WorkerThread dies, as in your last example, should TeleBot stop polling and re-raise the Exception in the main Thread?

**Comment by skgsergio** [comment]
Well, if you refer to my example of file manipulation exception in a handler if you catch *all* exceptions in the *WorkerThread* code (where *task* is called) then the exception of the example will be caught too.

On the other hand if you only catch *ApiExceptions* then the *WorkerThread* will die and I don't know what should be the proper way to treat it, maybe raising it to the top and exit the process with the Exception.

I will be happy with the first option, log all the exceptions in a *WorkerThread* as an error. But maybe exceptions caused by user code should stop the bot and make the user fix his code. Don't know.

**Comment by pevdh** [comment]
Are you able to test out the develop branch? Just pushed an update.

**Comment by skgsergio** [comment]
@pevdh hmmm didn't test but... Is this fine? -> https://github.com/eternnoir/pyTelegramBotAPI/blob/develop/telebot/__init__.py#L95

**Comment by pevdh** [comment]
Oh sht, forgot to remove that, thanks

**Comment by skgsergio** [comment]
* SSLError/ConnectionError now kills the process.

* With none_stop=True the ApiException doesn't kill the *WorkerThread*:
```
2015-10-01 22:58:37,784 (__init__.py:127 MainThread) INFO - TeleBot: "Started polling."
2015-10-01 22:59:00,587 (__init__.py:149 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[{"ok":false,"error_code":403,"description":"Error: Bad Request: bot was kicked from the chat"}]"
2015-10-01 22:59:00,588 (__init__.py:156 MainThread) INFO - TeleBot: "Waiting for 0.25 seconds until retry"
```

* With default none_stop (False) the ApiException kills the process:
```
2015-10-01 23:00:49,608 (__init__.py:127 MainThread) INFO - TeleBot: "Started polling."
2015-10-01 23:01:12,031 (__init__.py:149 MainThread) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 403 Forbidden. Response body:
[{"ok":false,"error_code":403,"description":"Error: Bad Request: bot was kicked from the chat"}]"
2015-10-01 23:01:12,032 (__init__.py:152 MainThread) INFO - TeleBot: "Exception occurred. Stopping."
2015-10-01 23:01:12,032 (__init__.py:160 MainThread) INFO - TeleBot: "Stopped polling."
```

* No matter what none_stop you use the exceptions caused by user code kills the process.

Nice :+1:
