### ISSUE TITLE
Getting Unicode error

### ISSUE THREAD

**Issue by nd7141** [eternnoir/pyTelegramBotAPI#83]
I have the following error:

Traceback (most recent call last):
    updates = telebot.apihelper.get_updates(self.token, offset=(self.last_update_id + 1), timeout=20)
  File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line 129, in get_updates
    return _make_request(token, method_url, params=payload)
  File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line 28, in _make_request
    return _check_result(method_name, result)['result']
  File "/usr/local/lib/python2.7/dist-packages/telebot/apihelper.py", line 53, in _check_result
    .format(result.text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 4530: ordinal not in range(128)

**Comment by pevdh** [comment]
Thanks a lot, fortunately it was an easy fix.

**Comment by nd7141** [comment]
I fixed it. For me it was that I was reading token incorrectly.

**Comment by pevdh** [comment]
Well, you stumbled upon a bug by accident then. I'm glad it is resolved.
