### ISSUE TITLE
'ChatPermissions' object is not iterable"

### ISSUE THREAD

**Issue by ronmount** [eternnoir/pyTelegramBotAPI#855]
1. What version of pyTelegramBotAPI are you using?https://github.com/eternnoir/pyTelegramBotAPI/commit/dbff7cbb3ee7d38e8de6af86df15abc1209ea229
absolutely fresh and 5 minutes ago upgraded

2. What OS are you using?
ubuntu 16.04

3. What version of python are you using?
3.7.5

When I'm trying to do

```
permissions = ChatPermissions(can_send_messages=False)
bot.set_chat_permissions(message.chat.id, permissions)
```

python drops
```
2020-05-20 03:36:04,523 (util.py:68 WorkerThread1) ERROR - TeleBot: "TypeError occurred, args=("'ChatPermissions' object is not iterable",)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pyTelegramBotAPI-3.7.1-py3.7.egg/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "main.py", line 140, in check
    bot.set_chat_permissions(message.chat.id, permissions)
  File "/usr/local/lib/python3.7/dist-packages/pyTelegramBotAPI-3.7.1-py3.7.egg/telebot/__init__.py", line 1053, in set_chat_permissions
    return apihelper.set_chat_permissions(self.token, chat_id, permissions)
  File "/usr/local/lib/python3.7/dist-packages/pyTelegramBotAPI-3.7.1-py3.7.egg/telebot/apihelper.py", line 682, in set_chat_permissions
    'permissions': _convert_list_json_serializable(permissions)}
  File "/usr/local/lib/python3.7/dist-packages/pyTelegramBotAPI-3.7.1-py3.7.egg/telebot/apihelper.py", line 1140, in _convert_list_json_serializable
    for r in results:
TypeError: 'ChatPermissions' object is not iterable
```

**Comment by Badiboy** [comment]
I'll check

**Comment by Badiboy** [comment]
https://github.com/eternnoir/pyTelegramBotAPI/pull/856

Try now pls.

**Comment by ronmount** [comment]
Works fine! =)
