### ISSUE TITLE
The bot often stops suddenly

### ISSUE THREAD

**Issue by Liquid72** [eternnoir/pyTelegramBotAPI#870]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?
3.7.1
2. What OS are you using?
Ubuntu 18.04
3. What version of python are you using?
3.6.9

`
Traceback (most recent call last):
  File "tb.py", line 107, in <module>
    bot.polling()
  File "/home/rico/.local/lib/python3.6/site-packages/telebot/__init__.py", line 415, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/home/rico/.local/lib/python3.6/site-packages/telebot/__init__.py", line 439, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/home/rico/.local/lib/python3.6/site-packages/telebot/util.py", line 111, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/home/rico/.local/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/rico/.local/lib/python3.6/site-packages/telebot/util.py", line 62, in run
    task(*args, **kwargs)
  File "tb.py", line 54, in send_welcome
    bot.reply_to(message,'Average Fee : '+str(blinfo.json()['data']['medianfee']))
  File "/home/rico/.local/lib/python3.6/site-packages/telebot/__init__.py", line 1303, in reply_to
    return self.send_message(message.chat.id, text, reply_to_message_id=message.message_id, **kwargs)
  File "/home/rico/.local/lib/python3.6/site-packages/telebot/__init__.py", line 625, in send_message
    reply_markup, parse_mode, disable_notification, timeout))
  File "/home/rico/.local/lib/python3.6/site-packages/telebot/apihelper.py", line 159, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/home/rico/.local/lib/python3.6/site-packages/telebot/apihelper.py", line 63, in _make_request
    timeout=(connect_timeout, read_timeout), proxies=proxy)
  File "/home/rico/.local/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/rico/.local/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/rico/.local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', OSError("(110, 'ETIMEDOUT')",))
`

**Comment by rabx2i** [comment]
This is a common mistake. It will help you: #832.

**Comment by Liquid72** [comment]
> This is a common mistake. It will help you: #832.

Ahh Okay Thanks It Working Now
