### ISSUE TITLE
AttributeError: 'TeleBot' object has no attribute 'message_handler'

### ISSUE THREAD

**Issue by Josephobby** [eternnoir/pyTelegramBotAPI#876]
Please answer these questions before submitting your issue. Thanks!

1. What version of pyTelegramBotAPI are you using?  pyTelegramBotAPI==3.7.1

2. What OS are you using? Catalina

3. What version of python are you using? 3.8

It works locally (with polling) but with Webhook I get in the log this Problem:
           app[web.1]: @bot.message_handler(commands=['start'])
           app[web.1]: AttributeError: 'TeleBot' object has no attribute 'message_handler'
I tried a lot of things I found in internet, like install a 2.2.3 version of pyTelegramBotAPI, or use "worker" instead of "web" in the Procfile and other things, but I couldn't resolve the Problem.

could you help me?
here a part of the Heroku log:
`2020-06-09T15:19:21.385021+00:00 heroku[web.1]: Starting process with command `python3 DirasatBot1.py`
2020-06-09T15:19:24.025968+00:00 app[web.1]: Traceback (most recent call last):
2020-06-09T15:19:24.025997+00:00 app[web.1]: File "DirasatBot1.py", line 11, in <module>
2020-06-09T15:19:24.026207+00:00 app[web.1]: @bot.message_handler(commands=['start'])
2020-06-09T15:19:24.026267+00:00 app[web.1]: AttributeError: 'TeleBot' object has no attribute 'message_handler'
2020-06-09T15:19:24.109951+00:00 heroku[web.1]: Process exited with status 1
2020-06-09T15:19:24.141896+00:00 heroku[web.1]: State changed from starting to crashed
2020-06-09T15:19:24.144381+00:00 heroku[web.1]: State changed from crashed to starting
2020-06-09T15:19:26.000000+00:00 app[api]: Build succeeded
2020-06-09T15:19:27.765561+00:00 heroku[web.1]: Starting process with command `python3 DirasatBot1.py`
2020-06-09T15:19:30.266841+00:00 app[web.1]: Traceback (most recent call last):
2020-06-09T15:19:30.266869+00:00 app[web.1]: File "DirasatBot1.py", line 11, in <module>
2020-06-09T15:19:30.266996+00:00 app[web.1]: @bot.message_handler(commands=['start'])
2020-06-09T15:19:30.267014+00:00 app[web.1]: AttributeError: 'TeleBot' object has no attribute 'message_handler'
2020-06-09T15:19:30.380336+00:00 heroku[web.1]: Process exited with status 1
2020-06-09T15:19:30.412905+00:00 heroku[web.1]: State changed from starting to crashed
2020-06-09T15:23:52.655674+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=agile-river-78920.herokuapp.com request_id=4f74e1be-b445-465e-b6d7-3a72669dde24 fwd="160.179.145.2" dyno= connect= service= status=503 bytes= protocol=https
2020-06-09T15:43:11.882986+00:00 heroku[web.1]: State changed from crashed to starting
2020-06-09T15:43:16.496027+00:00 heroku[web.1]: Starting process with command `python3 DirasatBot1.py`
2020-06-09T15:43:20.053023+00:00 app[web.1]: Traceback (most recent call last):
2020-06-09T15:43:20.053042+00:00 app[web.1]: File "DirasatBot1.py", line 11, in <module>
2020-06-09T15:43:20.053339+00:00 app[web.1]: @bot.message_handler(commands=['start'])
2020-06-09T15:43:20.053385+00:00 app[web.1]: AttributeError: 'TeleBot' object has no attribute 'message_handler'
2020-06-09T15:43:20.136862+00:00 heroku[web.1]: Process exited with status 1
2020-06-09T15:43:20.166774+00:00 heroku[web.1]: State changed from starting to crashed`
and a the end of the log:
`2020-06-09T17:37:10.000000+00:00 app[api]: Build succeeded
2020-06-09T17:38:47.871899+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=agile-river-78920.herokuapp.com request_id=39cff666-de5b-4f31-9a85-3401fc832650 fwd="160.179.145.2" dyno= connect= service= status=503 bytes= protocol=https`

**Comment by luisfmontes** [comment]
I beleve this video can help you
https://youtu.be/O0MAWtbg34g

**Comment by Josephobby** [comment]
> I beleve this video can help you
> https://youtu.be/O0MAWtbg34g

Yes, I did all the steps mentioned in this video, but It doesn't work.
