### ISSUE TITLE
ERROR - TeleBot: "ConnectionError occurred, args=(ProtocolError('Connection aborted.', timeout('The write operation timed out')),)

### ISSUE THREAD

**Issue by retiolus** [eternnoir/pyTelegramBotAPI#984]
When running this program:

```
import telebot

TOKEN = '<TOKEN>'
tb = telebot.TeleBot(TOKEN)     #create a new Telegram Bot object

chat_id = '<chat_id>'

@tb.message_handler(commands=['docs'])
def docs(m):
    doc = open('/path/to/file.pdf', 'rd')
    tb.send_document(chat_id, doc)
    

tb.polling(none_stop=True)
```

I get this doing /docs command in the bot:

```
2020-10-05 00:55:54,773 (util.py:75 WorkerThread2) ERROR - TeleBot: "ConnectionError occurred, args=(ProtocolError('Connection aborted.', timeout('The write operation timed out')),)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1045, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 967, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1045, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 967, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docsrt1bot/.local/lib/python3.8/site-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "bot.py", line 11, in docs
    tb.send_document(chat_id, doc)
  File "/home/docsrt1bot/.local/lib/python3.8/site-packages/telebot/__init__.py", line 764, in send_document
    apihelper.send_data(self.token, chat_id, data, 'document', reply_to_message_id, reply_markup,
  File "/home/docsrt1bot/.local/lib/python3.8/site-packages/telebot/apihelper.py", line 675, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
  File "/home/docsrt1bot/.local/lib/python3.8/site-packages/telebot/apihelper.py", line 102, in _make_request
    result = _get_req_session().request(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out'))
"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1045, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 967, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 702, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1045, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 967, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bot.py", line 14, in <module>
    tb.polling(none_stop=True)
  File "/home/docsrt1bot/.local/lib/python3.8/site-packages/telebot/__init__.py", line 427, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "/home/docsrt1bot/.local/lib/python3.8/site-packages/telebot/__init__.py", line 451, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/home/docsrt1bot/.local/lib/python3.8/site-packages/telebot/util.py", line 118, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
    raise value
  File "/home/docsrt1bot/.local/lib/python3.8/site-packages/telebot/util.py", line 69, in run
    task(*args, **kwargs)
  File "bot.py", line 11, in docs
    tb.send_document(chat_id, doc)
  File "/home/docsrt1bot/.local/lib/python3.8/site-packages/telebot/__init__.py", line 764, in send_document
    apihelper.send_data(self.token, chat_id, data, 'document', reply_to_message_id, reply_markup,
  File "/home/docsrt1bot/.local/lib/python3.8/site-packages/telebot/apihelper.py", line 675, in send_data
    return _make_request(token, method_url, params=payload, files=files, method='post')
  File "/home/docsrt1bot/.local/lib/python3.8/site-packages/telebot/apihelper.py", line 102, in _make_request
    result = _get_req_session().request(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out'))
```

1. What version of pyTelegramBotAPI are you using? --> Last

2. What OS are you using? --> Ubuntu 20.04

3. What version of python are you using? --> Python 3

**Comment by Akmal1st** [comment]
open('file','rb')

**Comment by retiolus** [comment]
I just changed:

`open('path/to/file.doc','rd')` to `open('path/to/file.doc','rb')`

and

`tb.send_document(chat_id, doc)` to `tb.send_document(chat_id, doc, timeout=1000)`

Problem seems to be solved.
