### ISSUE TITLE
AttributeError: module 'PIL' has no attribute 'Image'

### ISSUE THREAD

**Issue by dav1dexe** [eternnoir/pyTelegramBotAPI#986]
When running program:

```
import telebot

bot = telebot.TeleBot(' ')

@bot.message_handler(commands=['start'])
def start_message(message):
     img = open('1.png', 'rb')
     bot.send_photo(message.chat.id, img)


bot.polling()
```

Error:

```
2020-10-07 13:22:55,190 (util.py:75 WorkerThread2) ERROR - TeleBot: "AttributeError occurred, args=("module 'PIL' has no attribute 'Image'",)
Traceback (most recent call last):
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:/Users/David/Desktop/x.py", line 8, in help_message
    bot.send_photo(message.chat.id, img)
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\telebot\__init__.py", line 699, in send_photo
    apihelper.send_photo(self.token, chat_id, photo, caption, reply_to_message_id, reply_markup,
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\telebot\apihelper.py", line 336, in send_photo
    elif util.is_pil_image(photo):
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\telebot\util.py", line 176, in is_pil_image
    return pil_imported and isinstance(var, PIL.Image.Image)
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\PIL\__init__.py", line 42, in __getattr__
    raise AttributeError("module '{}' has no attribute '{}'".format(__name__, name))
AttributeError: module 'PIL' has no attribute 'Image'
"
Traceback (most recent call last):
  File "C:/Users/David/Desktop/x.py", line 11, in <module>
    bot.polling()
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\telebot\__init__.py", line 427, in polling
    self.__threaded_polling(none_stop, interval, timeout)
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\telebot\__init__.py", line 451, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\telebot\util.py", line 118, in raise_exceptions
    six.reraise(self.exc_info[0], self.exc_info[1], self.exc_info[2])
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\telebot\util.py", line 69, in run
    task(*args, **kwargs)
  File "C:/Users/David/Desktop/x.py", line 8, in help_message
    bot.send_photo(message.chat.id, img)
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\telebot\__init__.py", line 699, in send_photo
    apihelper.send_photo(self.token, chat_id, photo, caption, reply_to_message_id, reply_markup,
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\telebot\apihelper.py", line 336, in send_photo
    elif util.is_pil_image(photo):
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\telebot\util.py", line 176, in is_pil_image
    return pil_imported and isinstance(var, PIL.Image.Image)
  File "C:\Users\David\Desktop\books\venv\lib\site-packages\PIL\__init__.py", line 42, in __getattr__
    raise AttributeError("module '{}' has no attribute '{}'".format(__name__, name))
AttributeError: module 'PIL' has no attribute 'Image'
```

1. What version of pyTelegramBotAPI are you using? = `3.7.3`

2. What OS are you using? = `Windows 10 LTSC`

3. What version of python are you using? = `3.8.2`

**Comment by dtalkachou** [comment]
Code is correct. This code worked on my PC.
Try execute this code with other PNG file and if you get success, the problem is in your file (maybe damaged)

**Comment by Badiboy** [comment]
Fix: https://github.com/eternnoir/pyTelegramBotAPI/issues/988#issuecomment-706698150
